// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: app_spec.proto

package xmeta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CRUDOperation int32

const (
	CRUDOperation_CRUDOperationUnknown CRUDOperation = 0
	CRUDOperation_CRUDOperationList    CRUDOperation = 1
	CRUDOperation_CRUDOperationRead    CRUDOperation = 2
	CRUDOperation_CRUDOperationCreate  CRUDOperation = 3
	CRUDOperation_CRUDOperationUpdate  CRUDOperation = 4
	CRUDOperation_CRUDOperationDelete  CRUDOperation = 5
)

// Enum value maps for CRUDOperation.
var (
	CRUDOperation_name = map[int32]string{
		0: "CRUDOperationUnknown",
		1: "CRUDOperationList",
		2: "CRUDOperationRead",
		3: "CRUDOperationCreate",
		4: "CRUDOperationUpdate",
		5: "CRUDOperationDelete",
	}
	CRUDOperation_value = map[string]int32{
		"CRUDOperationUnknown": 0,
		"CRUDOperationList":    1,
		"CRUDOperationRead":    2,
		"CRUDOperationCreate":  3,
		"CRUDOperationUpdate":  4,
		"CRUDOperationDelete":  5,
	}
)

func (x CRUDOperation) Enum() *CRUDOperation {
	p := new(CRUDOperation)
	*p = x
	return p
}

func (x CRUDOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CRUDOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_app_spec_proto_enumTypes[0].Descriptor()
}

func (CRUDOperation) Type() protoreflect.EnumType {
	return &file_app_spec_proto_enumTypes[0]
}

func (x CRUDOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CRUDOperation.Descriptor instead.
func (CRUDOperation) EnumDescriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{0}
}

type FKTraversalMode int32

const (
	FKTraversalMode_FKTraversalModeUnspecified         FKTraversalMode = 0
	FKTraversalMode_FKTraversalModeNone                FKTraversalMode = 1
	FKTraversalMode_FKTraversalModeAuthUserDescendants FKTraversalMode = 2
	FKTraversalMode_FKTraversalModeAllTables           FKTraversalMode = 3
)

// Enum value maps for FKTraversalMode.
var (
	FKTraversalMode_name = map[int32]string{
		0: "FKTraversalModeUnspecified",
		1: "FKTraversalModeNone",
		2: "FKTraversalModeAuthUserDescendants",
		3: "FKTraversalModeAllTables",
	}
	FKTraversalMode_value = map[string]int32{
		"FKTraversalModeUnspecified":         0,
		"FKTraversalModeNone":                1,
		"FKTraversalModeAuthUserDescendants": 2,
		"FKTraversalModeAllTables":           3,
	}
)

func (x FKTraversalMode) Enum() *FKTraversalMode {
	p := new(FKTraversalMode)
	*p = x
	return p
}

func (x FKTraversalMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FKTraversalMode) Descriptor() protoreflect.EnumDescriptor {
	return file_app_spec_proto_enumTypes[1].Descriptor()
}

func (FKTraversalMode) Type() protoreflect.EnumType {
	return &file_app_spec_proto_enumTypes[1]
}

func (x FKTraversalMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FKTraversalMode.Descriptor instead.
func (FKTraversalMode) EnumDescriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{1}
}

type FKTraversalDirection int32

const (
	FKTraversalDirection_FKTraversalDirectionUnspecified FKTraversalDirection = 0
	FKTraversalDirection_FKTraversalDirectionChildren    FKTraversalDirection = 1
	FKTraversalDirection_FKTraversalDirectionParents     FKTraversalDirection = 2
	FKTraversalDirection_FKTraversalDirectionBoth        FKTraversalDirection = 3
)

// Enum value maps for FKTraversalDirection.
var (
	FKTraversalDirection_name = map[int32]string{
		0: "FKTraversalDirectionUnspecified",
		1: "FKTraversalDirectionChildren",
		2: "FKTraversalDirectionParents",
		3: "FKTraversalDirectionBoth",
	}
	FKTraversalDirection_value = map[string]int32{
		"FKTraversalDirectionUnspecified": 0,
		"FKTraversalDirectionChildren":    1,
		"FKTraversalDirectionParents":     2,
		"FKTraversalDirectionBoth":        3,
	}
)

func (x FKTraversalDirection) Enum() *FKTraversalDirection {
	p := new(FKTraversalDirection)
	*p = x
	return p
}

func (x FKTraversalDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FKTraversalDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_app_spec_proto_enumTypes[2].Descriptor()
}

func (FKTraversalDirection) Type() protoreflect.EnumType {
	return &file_app_spec_proto_enumTypes[2]
}

func (x FKTraversalDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FKTraversalDirection.Descriptor instead.
func (FKTraversalDirection) EnumDescriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{2}
}

type AppSpec struct {
	state           protoimpl.MessageState       `protogen:"open.v1"`
	Name            string                       `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Datasource      *DatasourceMetadata          `protobuf:"bytes,2,opt,name=Datasource,proto3" json:"Datasource,omitempty"`
	Components      []*AppComponent              `protobuf:"bytes,3,rep,name=Components,proto3" json:"Components,omitempty"`
	Roles           []*AppRole                   `protobuf:"bytes,4,rep,name=Roles,proto3" json:"Roles,omitempty"`
	Options         map[string]string            `protobuf:"bytes,5,rep,name=Options,proto3" json:"Options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SchemaOverrides *SchemaRelationshipOverrides `protobuf:"bytes,6,opt,name=SchemaOverrides,proto3" json:"SchemaOverrides,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AppSpec) Reset() {
	*x = AppSpec{}
	mi := &file_app_spec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppSpec) ProtoMessage() {}

func (x *AppSpec) ProtoReflect() protoreflect.Message {
	mi := &file_app_spec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppSpec.ProtoReflect.Descriptor instead.
func (*AppSpec) Descriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{0}
}

func (x *AppSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppSpec) GetDatasource() *DatasourceMetadata {
	if x != nil {
		return x.Datasource
	}
	return nil
}

func (x *AppSpec) GetComponents() []*AppComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *AppSpec) GetRoles() []*AppRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AppSpec) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *AppSpec) GetSchemaOverrides() *SchemaRelationshipOverrides {
	if x != nil {
		return x.SchemaOverrides
	}
	return nil
}

type DatasourceMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=Driver,proto3" json:"Driver,omitempty"`
	Database      string                 `protobuf:"bytes,3,opt,name=Database,proto3" json:"Database,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=Options,proto3" json:"Options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasourceMetadata) Reset() {
	*x = DatasourceMetadata{}
	mi := &file_app_spec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasourceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasourceMetadata) ProtoMessage() {}

func (x *DatasourceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_app_spec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasourceMetadata.ProtoReflect.Descriptor instead.
func (*DatasourceMetadata) Descriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{1}
}

func (x *DatasourceMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DatasourceMetadata) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *DatasourceMetadata) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DatasourceMetadata) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type AppComponent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	TableName        *ObjectName            `protobuf:"bytes,2,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	PublicOperations []CRUDOperation        `protobuf:"varint,4,rep,packed,name=PublicOperations,proto3,enum=sqlmeta.CRUDOperation" json:"PublicOperations,omitempty"`
	Options          map[string]string      `protobuf:"bytes,5,rep,name=Options,proto3" json:"Options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AppComponent) Reset() {
	*x = AppComponent{}
	mi := &file_app_spec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppComponent) ProtoMessage() {}

func (x *AppComponent) ProtoReflect() protoreflect.Message {
	mi := &file_app_spec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppComponent.ProtoReflect.Descriptor instead.
func (*AppComponent) Descriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{2}
}

func (x *AppComponent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppComponent) GetTableName() *ObjectName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *AppComponent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AppComponent) GetPublicOperations() []CRUDOperation {
	if x != nil {
		return x.PublicOperations
	}
	return nil
}

func (x *AppComponent) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type AppRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	Auth          *AuthBinding           `protobuf:"bytes,3,opt,name=Auth,proto3" json:"Auth,omitempty"`
	CrudPolicy    *CRUDPolicy            `protobuf:"bytes,4,opt,name=CrudPolicy,proto3" json:"CrudPolicy,omitempty"`
	Scope         *RoleScope             `protobuf:"bytes,5,opt,name=Scope,proto3" json:"Scope,omitempty"`
	Options       map[string]string      `protobuf:"bytes,6,rep,name=Options,proto3" json:"Options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppRole) Reset() {
	*x = AppRole{}
	mi := &file_app_spec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppRole) ProtoMessage() {}

func (x *AppRole) ProtoReflect() protoreflect.Message {
	mi := &file_app_spec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppRole.ProtoReflect.Descriptor instead.
func (*AppRole) Descriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{3}
}

func (x *AppRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AppRole) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AppRole) GetAuth() *AuthBinding {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *AppRole) GetCrudPolicy() *CRUDPolicy {
	if x != nil {
		return x.CrudPolicy
	}
	return nil
}

func (x *AppRole) GetScope() *RoleScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *AppRole) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type AuthBinding struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserTable       *ObjectName            `protobuf:"bytes,1,opt,name=UserTable,proto3" json:"UserTable,omitempty"`
	UserIDColumn    string                 `protobuf:"bytes,2,opt,name=UserIDColumn,proto3" json:"UserIDColumn,omitempty"`
	LoginColumn     string                 `protobuf:"bytes,3,opt,name=LoginColumn,proto3" json:"LoginColumn,omitempty"`
	PasswordColumn  string                 `protobuf:"bytes,4,opt,name=PasswordColumn,proto3" json:"PasswordColumn,omitempty"`
	FirstNameColumn string                 `protobuf:"bytes,5,opt,name=FirstNameColumn,proto3" json:"FirstNameColumn,omitempty"`
	LastNameColumn  string                 `protobuf:"bytes,6,opt,name=LastNameColumn,proto3" json:"LastNameColumn,omitempty"`
	Options         map[string]string      `protobuf:"bytes,7,rep,name=Options,proto3" json:"Options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthBinding) Reset() {
	*x = AuthBinding{}
	mi := &file_app_spec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthBinding) ProtoMessage() {}

func (x *AuthBinding) ProtoReflect() protoreflect.Message {
	mi := &file_app_spec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthBinding.ProtoReflect.Descriptor instead.
func (*AuthBinding) Descriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{4}
}

func (x *AuthBinding) GetUserTable() *ObjectName {
	if x != nil {
		return x.UserTable
	}
	return nil
}

func (x *AuthBinding) GetUserIDColumn() string {
	if x != nil {
		return x.UserIDColumn
	}
	return ""
}

func (x *AuthBinding) GetLoginColumn() string {
	if x != nil {
		return x.LoginColumn
	}
	return ""
}

func (x *AuthBinding) GetPasswordColumn() string {
	if x != nil {
		return x.PasswordColumn
	}
	return ""
}

func (x *AuthBinding) GetFirstNameColumn() string {
	if x != nil {
		return x.FirstNameColumn
	}
	return ""
}

func (x *AuthBinding) GetLastNameColumn() string {
	if x != nil {
		return x.LastNameColumn
	}
	return ""
}

func (x *AuthBinding) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type CRUDPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []CRUDOperation        `protobuf:"varint,1,rep,packed,name=Operations,proto3,enum=sqlmeta.CRUDOperation" json:"Operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRUDPolicy) Reset() {
	*x = CRUDPolicy{}
	mi := &file_app_spec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRUDPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRUDPolicy) ProtoMessage() {}

func (x *CRUDPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_app_spec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRUDPolicy.ProtoReflect.Descriptor instead.
func (*CRUDPolicy) Descriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{5}
}

func (x *CRUDPolicy) GetOperations() []CRUDOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type RoleScope struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mode              FKTraversalMode        `protobuf:"varint,1,opt,name=Mode,proto3,enum=sqlmeta.FKTraversalMode" json:"Mode,omitempty"`
	Direction         FKTraversalDirection   `protobuf:"varint,2,opt,name=Direction,proto3,enum=sqlmeta.FKTraversalDirection" json:"Direction,omitempty"`
	MaxDepth          uint32                 `protobuf:"varint,3,opt,name=MaxDepth,proto3" json:"MaxDepth,omitempty"`
	IncludeTables     []*ObjectName          `protobuf:"bytes,4,rep,name=IncludeTables,proto3" json:"IncludeTables,omitempty"`
	ExcludeTables     []*ObjectName          `protobuf:"bytes,5,rep,name=ExcludeTables,proto3" json:"ExcludeTables,omitempty"`
	IncludeStartTable bool                   `protobuf:"varint,6,opt,name=IncludeStartTable,proto3" json:"IncludeStartTable,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RoleScope) Reset() {
	*x = RoleScope{}
	mi := &file_app_spec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleScope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleScope) ProtoMessage() {}

func (x *RoleScope) ProtoReflect() protoreflect.Message {
	mi := &file_app_spec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleScope.ProtoReflect.Descriptor instead.
func (*RoleScope) Descriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{6}
}

func (x *RoleScope) GetMode() FKTraversalMode {
	if x != nil {
		return x.Mode
	}
	return FKTraversalMode_FKTraversalModeUnspecified
}

func (x *RoleScope) GetDirection() FKTraversalDirection {
	if x != nil {
		return x.Direction
	}
	return FKTraversalDirection_FKTraversalDirectionUnspecified
}

func (x *RoleScope) GetMaxDepth() uint32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *RoleScope) GetIncludeTables() []*ObjectName {
	if x != nil {
		return x.IncludeTables
	}
	return nil
}

func (x *RoleScope) GetExcludeTables() []*ObjectName {
	if x != nil {
		return x.ExcludeTables
	}
	return nil
}

func (x *RoleScope) GetIncludeStartTable() bool {
	if x != nil {
		return x.IncludeStartTable
	}
	return false
}

type SchemaRelationshipOverrides struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrimaryKeys   []*ManualPrimaryKey    `protobuf:"bytes,1,rep,name=PrimaryKeys,proto3" json:"PrimaryKeys,omitempty"`
	ForeignKeys   []*ManualForeignKey    `protobuf:"bytes,2,rep,name=ForeignKeys,proto3" json:"ForeignKeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaRelationshipOverrides) Reset() {
	*x = SchemaRelationshipOverrides{}
	mi := &file_app_spec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRelationshipOverrides) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRelationshipOverrides) ProtoMessage() {}

func (x *SchemaRelationshipOverrides) ProtoReflect() protoreflect.Message {
	mi := &file_app_spec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRelationshipOverrides.ProtoReflect.Descriptor instead.
func (*SchemaRelationshipOverrides) Descriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{7}
}

func (x *SchemaRelationshipOverrides) GetPrimaryKeys() []*ManualPrimaryKey {
	if x != nil {
		return x.PrimaryKeys
	}
	return nil
}

func (x *SchemaRelationshipOverrides) GetForeignKeys() []*ManualForeignKey {
	if x != nil {
		return x.ForeignKeys
	}
	return nil
}

type ManualPrimaryKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	TableName     *ObjectName            `protobuf:"bytes,2,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Columns       []string               `protobuf:"bytes,3,rep,name=Columns,proto3" json:"Columns,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=Options,proto3" json:"Options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualPrimaryKey) Reset() {
	*x = ManualPrimaryKey{}
	mi := &file_app_spec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualPrimaryKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualPrimaryKey) ProtoMessage() {}

func (x *ManualPrimaryKey) ProtoReflect() protoreflect.Message {
	mi := &file_app_spec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualPrimaryKey.ProtoReflect.Descriptor instead.
func (*ManualPrimaryKey) Descriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{8}
}

func (x *ManualPrimaryKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManualPrimaryKey) GetTableName() *ObjectName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *ManualPrimaryKey) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ManualPrimaryKey) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ManualForeignKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ChildTable    *ObjectName            `protobuf:"bytes,2,opt,name=ChildTable,proto3" json:"ChildTable,omitempty"`
	ChildColumns  []string               `protobuf:"bytes,3,rep,name=ChildColumns,proto3" json:"ChildColumns,omitempty"`
	ParentTable   *ObjectName            `protobuf:"bytes,4,opt,name=ParentTable,proto3" json:"ParentTable,omitempty"`
	ParentColumns []string               `protobuf:"bytes,5,rep,name=ParentColumns,proto3" json:"ParentColumns,omitempty"`
	Options       map[string]string      `protobuf:"bytes,6,rep,name=Options,proto3" json:"Options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualForeignKey) Reset() {
	*x = ManualForeignKey{}
	mi := &file_app_spec_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualForeignKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualForeignKey) ProtoMessage() {}

func (x *ManualForeignKey) ProtoReflect() protoreflect.Message {
	mi := &file_app_spec_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualForeignKey.ProtoReflect.Descriptor instead.
func (*ManualForeignKey) Descriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{9}
}

func (x *ManualForeignKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManualForeignKey) GetChildTable() *ObjectName {
	if x != nil {
		return x.ChildTable
	}
	return nil
}

func (x *ManualForeignKey) GetChildColumns() []string {
	if x != nil {
		return x.ChildColumns
	}
	return nil
}

func (x *ManualForeignKey) GetParentTable() *ObjectName {
	if x != nil {
		return x.ParentTable
	}
	return nil
}

func (x *ManualForeignKey) GetParentColumns() []string {
	if x != nil {
		return x.ParentColumns
	}
	return nil
}

func (x *ManualForeignKey) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ExpandedAppSpec struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	Spec            *AppSpec                  `protobuf:"bytes,1,opt,name=Spec,proto3" json:"Spec,omitempty"`
	ComponentGrants []*ExpandedComponentGrant `protobuf:"bytes,2,rep,name=ComponentGrants,proto3" json:"ComponentGrants,omitempty"`
	TableGrants     []*ExpandedTableGrant     `protobuf:"bytes,3,rep,name=TableGrants,proto3" json:"TableGrants,omitempty"`
	Warnings        []string                  `protobuf:"bytes,4,rep,name=Warnings,proto3" json:"Warnings,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExpandedAppSpec) Reset() {
	*x = ExpandedAppSpec{}
	mi := &file_app_spec_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandedAppSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandedAppSpec) ProtoMessage() {}

func (x *ExpandedAppSpec) ProtoReflect() protoreflect.Message {
	mi := &file_app_spec_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandedAppSpec.ProtoReflect.Descriptor instead.
func (*ExpandedAppSpec) Descriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{10}
}

func (x *ExpandedAppSpec) GetSpec() *AppSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ExpandedAppSpec) GetComponentGrants() []*ExpandedComponentGrant {
	if x != nil {
		return x.ComponentGrants
	}
	return nil
}

func (x *ExpandedAppSpec) GetTableGrants() []*ExpandedTableGrant {
	if x != nil {
		return x.TableGrants
	}
	return nil
}

func (x *ExpandedAppSpec) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type ExpandedComponentGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
	ComponentName string                 `protobuf:"bytes,2,opt,name=ComponentName,proto3" json:"ComponentName,omitempty"`
	TableName     *ObjectName            `protobuf:"bytes,3,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Operations    []CRUDOperation        `protobuf:"varint,4,rep,packed,name=Operations,proto3,enum=sqlmeta.CRUDOperation" json:"Operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandedComponentGrant) Reset() {
	*x = ExpandedComponentGrant{}
	mi := &file_app_spec_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandedComponentGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandedComponentGrant) ProtoMessage() {}

func (x *ExpandedComponentGrant) ProtoReflect() protoreflect.Message {
	mi := &file_app_spec_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandedComponentGrant.ProtoReflect.Descriptor instead.
func (*ExpandedComponentGrant) Descriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{11}
}

func (x *ExpandedComponentGrant) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *ExpandedComponentGrant) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *ExpandedComponentGrant) GetTableName() *ObjectName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *ExpandedComponentGrant) GetOperations() []CRUDOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type ExpandedTableGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=RoleName,proto3" json:"RoleName,omitempty"`
	TableName     *ObjectName            `protobuf:"bytes,2,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Operations    []CRUDOperation        `protobuf:"varint,3,rep,packed,name=Operations,proto3,enum=sqlmeta.CRUDOperation" json:"Operations,omitempty"`
	TraversalPath []*ObjectName          `protobuf:"bytes,4,rep,name=TraversalPath,proto3" json:"TraversalPath,omitempty"`
	ScopeColumn   string                 `protobuf:"bytes,5,opt,name=ScopeColumn,proto3" json:"ScopeColumn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandedTableGrant) Reset() {
	*x = ExpandedTableGrant{}
	mi := &file_app_spec_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandedTableGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandedTableGrant) ProtoMessage() {}

func (x *ExpandedTableGrant) ProtoReflect() protoreflect.Message {
	mi := &file_app_spec_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandedTableGrant.ProtoReflect.Descriptor instead.
func (*ExpandedTableGrant) Descriptor() ([]byte, []int) {
	return file_app_spec_proto_rawDescGZIP(), []int{12}
}

func (x *ExpandedTableGrant) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *ExpandedTableGrant) GetTableName() *ObjectName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *ExpandedTableGrant) GetOperations() []CRUDOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *ExpandedTableGrant) GetTraversalPath() []*ObjectName {
	if x != nil {
		return x.TraversalPath
	}
	return nil
}

func (x *ExpandedTableGrant) GetScopeColumn() string {
	if x != nil {
		return x.ScopeColumn
	}
	return ""
}

var File_app_spec_proto protoreflect.FileDescriptor

const file_app_spec_proto_rawDesc = "" +
	"\n" +
	"\x0eapp_spec.proto\x12\asqlmeta\x1a\vtypes.proto\"\xfe\x02\n" +
	"\aAppSpec\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12;\n" +
	"\n" +
	"Datasource\x18\x02 \x01(\v2\x1b.sqlmeta.DatasourceMetadataR\n" +
	"Datasource\x125\n" +
	"\n" +
	"Components\x18\x03 \x03(\v2\x15.sqlmeta.AppComponentR\n" +
	"Components\x12&\n" +
	"\x05Roles\x18\x04 \x03(\v2\x10.sqlmeta.AppRoleR\x05Roles\x127\n" +
	"\aOptions\x18\x05 \x03(\v2\x1d.sqlmeta.AppSpec.OptionsEntryR\aOptions\x12N\n" +
	"\x0fSchemaOverrides\x18\x06 \x01(\v2$.sqlmeta.SchemaRelationshipOverridesR\x0fSchemaOverrides\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x01\n" +
	"\x12DatasourceMetadata\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Driver\x18\x02 \x01(\tR\x06Driver\x12\x1a\n" +
	"\bDatabase\x18\x03 \x01(\tR\bDatabase\x12B\n" +
	"\aOptions\x18\x04 \x03(\v2(.sqlmeta.DatasourceMetadata.OptionsEntryR\aOptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x02\n" +
	"\fAppComponent\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x121\n" +
	"\tTableName\x18\x02 \x01(\v2\x13.sqlmeta.ObjectNameR\tTableName\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x12B\n" +
	"\x10PublicOperations\x18\x04 \x03(\x0e2\x16.sqlmeta.CRUDOperationR\x10PublicOperations\x12<\n" +
	"\aOptions\x18\x05 \x03(\v2\".sqlmeta.AppComponent.OptionsEntryR\aOptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x02\n" +
	"\aAppRole\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12 \n" +
	"\vDescription\x18\x02 \x01(\tR\vDescription\x12(\n" +
	"\x04Auth\x18\x03 \x01(\v2\x14.sqlmeta.AuthBindingR\x04Auth\x123\n" +
	"\n" +
	"CrudPolicy\x18\x04 \x01(\v2\x13.sqlmeta.CRUDPolicyR\n" +
	"CrudPolicy\x12(\n" +
	"\x05Scope\x18\x05 \x01(\v2\x12.sqlmeta.RoleScopeR\x05Scope\x127\n" +
	"\aOptions\x18\x06 \x03(\v2\x1d.sqlmeta.AppRole.OptionsEntryR\aOptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x02\n" +
	"\vAuthBinding\x121\n" +
	"\tUserTable\x18\x01 \x01(\v2\x13.sqlmeta.ObjectNameR\tUserTable\x12\"\n" +
	"\fUserIDColumn\x18\x02 \x01(\tR\fUserIDColumn\x12 \n" +
	"\vLoginColumn\x18\x03 \x01(\tR\vLoginColumn\x12&\n" +
	"\x0ePasswordColumn\x18\x04 \x01(\tR\x0ePasswordColumn\x12(\n" +
	"\x0fFirstNameColumn\x18\x05 \x01(\tR\x0fFirstNameColumn\x12&\n" +
	"\x0eLastNameColumn\x18\x06 \x01(\tR\x0eLastNameColumn\x12;\n" +
	"\aOptions\x18\a \x03(\v2!.sqlmeta.AuthBinding.OptionsEntryR\aOptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\n" +
	"CRUDPolicy\x126\n" +
	"\n" +
	"Operations\x18\x01 \x03(\x0e2\x16.sqlmeta.CRUDOperationR\n" +
	"Operations\"\xb6\x02\n" +
	"\tRoleScope\x12,\n" +
	"\x04Mode\x18\x01 \x01(\x0e2\x18.sqlmeta.FKTraversalModeR\x04Mode\x12;\n" +
	"\tDirection\x18\x02 \x01(\x0e2\x1d.sqlmeta.FKTraversalDirectionR\tDirection\x12\x1a\n" +
	"\bMaxDepth\x18\x03 \x01(\rR\bMaxDepth\x129\n" +
	"\rIncludeTables\x18\x04 \x03(\v2\x13.sqlmeta.ObjectNameR\rIncludeTables\x129\n" +
	"\rExcludeTables\x18\x05 \x03(\v2\x13.sqlmeta.ObjectNameR\rExcludeTables\x12,\n" +
	"\x11IncludeStartTable\x18\x06 \x01(\bR\x11IncludeStartTable\"\x97\x01\n" +
	"\x1bSchemaRelationshipOverrides\x12;\n" +
	"\vPrimaryKeys\x18\x01 \x03(\v2\x19.sqlmeta.ManualPrimaryKeyR\vPrimaryKeys\x12;\n" +
	"\vForeignKeys\x18\x02 \x03(\v2\x19.sqlmeta.ManualForeignKeyR\vForeignKeys\"\xf1\x01\n" +
	"\x10ManualPrimaryKey\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x121\n" +
	"\tTableName\x18\x02 \x01(\v2\x13.sqlmeta.ObjectNameR\tTableName\x12\x18\n" +
	"\aColumns\x18\x03 \x03(\tR\aColumns\x12@\n" +
	"\aOptions\x18\x04 \x03(\v2&.sqlmeta.ManualPrimaryKey.OptionsEntryR\aOptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x02\n" +
	"\x10ManualForeignKey\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x123\n" +
	"\n" +
	"ChildTable\x18\x02 \x01(\v2\x13.sqlmeta.ObjectNameR\n" +
	"ChildTable\x12\"\n" +
	"\fChildColumns\x18\x03 \x03(\tR\fChildColumns\x125\n" +
	"\vParentTable\x18\x04 \x01(\v2\x13.sqlmeta.ObjectNameR\vParentTable\x12$\n" +
	"\rParentColumns\x18\x05 \x03(\tR\rParentColumns\x12@\n" +
	"\aOptions\x18\x06 \x03(\v2&.sqlmeta.ManualForeignKey.OptionsEntryR\aOptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x01\n" +
	"\x0fExpandedAppSpec\x12$\n" +
	"\x04Spec\x18\x01 \x01(\v2\x10.sqlmeta.AppSpecR\x04Spec\x12I\n" +
	"\x0fComponentGrants\x18\x02 \x03(\v2\x1f.sqlmeta.ExpandedComponentGrantR\x0fComponentGrants\x12=\n" +
	"\vTableGrants\x18\x03 \x03(\v2\x1b.sqlmeta.ExpandedTableGrantR\vTableGrants\x12\x1a\n" +
	"\bWarnings\x18\x04 \x03(\tR\bWarnings\"\xc5\x01\n" +
	"\x16ExpandedComponentGrant\x12\x1a\n" +
	"\bRoleName\x18\x01 \x01(\tR\bRoleName\x12$\n" +
	"\rComponentName\x18\x02 \x01(\tR\rComponentName\x121\n" +
	"\tTableName\x18\x03 \x01(\v2\x13.sqlmeta.ObjectNameR\tTableName\x126\n" +
	"\n" +
	"Operations\x18\x04 \x03(\x0e2\x16.sqlmeta.CRUDOperationR\n" +
	"Operations\"\xf8\x01\n" +
	"\x12ExpandedTableGrant\x12\x1a\n" +
	"\bRoleName\x18\x01 \x01(\tR\bRoleName\x121\n" +
	"\tTableName\x18\x02 \x01(\v2\x13.sqlmeta.ObjectNameR\tTableName\x126\n" +
	"\n" +
	"Operations\x18\x03 \x03(\x0e2\x16.sqlmeta.CRUDOperationR\n" +
	"Operations\x129\n" +
	"\rTraversalPath\x18\x04 \x03(\v2\x13.sqlmeta.ObjectNameR\rTraversalPath\x12 \n" +
	"\vScopeColumn\x18\x05 \x01(\tR\vScopeColumn*\xa2\x01\n" +
	"\rCRUDOperation\x12\x18\n" +
	"\x14CRUDOperationUnknown\x10\x00\x12\x15\n" +
	"\x11CRUDOperationList\x10\x01\x12\x15\n" +
	"\x11CRUDOperationRead\x10\x02\x12\x17\n" +
	"\x13CRUDOperationCreate\x10\x03\x12\x17\n" +
	"\x13CRUDOperationUpdate\x10\x04\x12\x17\n" +
	"\x13CRUDOperationDelete\x10\x05*\x90\x01\n" +
	"\x0fFKTraversalMode\x12\x1e\n" +
	"\x1aFKTraversalModeUnspecified\x10\x00\x12\x17\n" +
	"\x13FKTraversalModeNone\x10\x01\x12&\n" +
	"\"FKTraversalModeAuthUserDescendants\x10\x02\x12\x1c\n" +
	"\x18FKTraversalModeAllTables\x10\x03*\x9c\x01\n" +
	"\x14FKTraversalDirection\x12#\n" +
	"\x1fFKTraversalDirectionUnspecified\x10\x00\x12 \n" +
	"\x1cFKTraversalDirectionChildren\x10\x01\x12\x1f\n" +
	"\x1bFKTraversalDirectionParents\x10\x02\x12\x1c\n" +
	"\x18FKTraversalDirectionBoth\x10\x03B\"Z github.com/genelet/sqlmeta/xmetab\x06proto3"

var (
	file_app_spec_proto_rawDescOnce sync.Once
	file_app_spec_proto_rawDescData []byte
)

func file_app_spec_proto_rawDescGZIP() []byte {
	file_app_spec_proto_rawDescOnce.Do(func() {
		file_app_spec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_spec_proto_rawDesc), len(file_app_spec_proto_rawDesc)))
	})
	return file_app_spec_proto_rawDescData
}

var file_app_spec_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_app_spec_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_app_spec_proto_goTypes = []any{
	(CRUDOperation)(0),                  // 0: sqlmeta.CRUDOperation
	(FKTraversalMode)(0),                // 1: sqlmeta.FKTraversalMode
	(FKTraversalDirection)(0),           // 2: sqlmeta.FKTraversalDirection
	(*AppSpec)(nil),                     // 3: sqlmeta.AppSpec
	(*DatasourceMetadata)(nil),          // 4: sqlmeta.DatasourceMetadata
	(*AppComponent)(nil),                // 5: sqlmeta.AppComponent
	(*AppRole)(nil),                     // 6: sqlmeta.AppRole
	(*AuthBinding)(nil),                 // 7: sqlmeta.AuthBinding
	(*CRUDPolicy)(nil),                  // 8: sqlmeta.CRUDPolicy
	(*RoleScope)(nil),                   // 9: sqlmeta.RoleScope
	(*SchemaRelationshipOverrides)(nil), // 10: sqlmeta.SchemaRelationshipOverrides
	(*ManualPrimaryKey)(nil),            // 11: sqlmeta.ManualPrimaryKey
	(*ManualForeignKey)(nil),            // 12: sqlmeta.ManualForeignKey
	(*ExpandedAppSpec)(nil),             // 13: sqlmeta.ExpandedAppSpec
	(*ExpandedComponentGrant)(nil),      // 14: sqlmeta.ExpandedComponentGrant
	(*ExpandedTableGrant)(nil),          // 15: sqlmeta.ExpandedTableGrant
	nil,                                 // 16: sqlmeta.AppSpec.OptionsEntry
	nil,                                 // 17: sqlmeta.DatasourceMetadata.OptionsEntry
	nil,                                 // 18: sqlmeta.AppComponent.OptionsEntry
	nil,                                 // 19: sqlmeta.AppRole.OptionsEntry
	nil,                                 // 20: sqlmeta.AuthBinding.OptionsEntry
	nil,                                 // 21: sqlmeta.ManualPrimaryKey.OptionsEntry
	nil,                                 // 22: sqlmeta.ManualForeignKey.OptionsEntry
	(*ObjectName)(nil),                  // 23: sqlmeta.ObjectName
}
var file_app_spec_proto_depIdxs = []int32{
	4,  // 0: sqlmeta.AppSpec.Datasource:type_name -> sqlmeta.DatasourceMetadata
	5,  // 1: sqlmeta.AppSpec.Components:type_name -> sqlmeta.AppComponent
	6,  // 2: sqlmeta.AppSpec.Roles:type_name -> sqlmeta.AppRole
	16, // 3: sqlmeta.AppSpec.Options:type_name -> sqlmeta.AppSpec.OptionsEntry
	10, // 4: sqlmeta.AppSpec.SchemaOverrides:type_name -> sqlmeta.SchemaRelationshipOverrides
	17, // 5: sqlmeta.DatasourceMetadata.Options:type_name -> sqlmeta.DatasourceMetadata.OptionsEntry
	23, // 6: sqlmeta.AppComponent.TableName:type_name -> sqlmeta.ObjectName
	0,  // 7: sqlmeta.AppComponent.PublicOperations:type_name -> sqlmeta.CRUDOperation
	18, // 8: sqlmeta.AppComponent.Options:type_name -> sqlmeta.AppComponent.OptionsEntry
	7,  // 9: sqlmeta.AppRole.Auth:type_name -> sqlmeta.AuthBinding
	8,  // 10: sqlmeta.AppRole.CrudPolicy:type_name -> sqlmeta.CRUDPolicy
	9,  // 11: sqlmeta.AppRole.Scope:type_name -> sqlmeta.RoleScope
	19, // 12: sqlmeta.AppRole.Options:type_name -> sqlmeta.AppRole.OptionsEntry
	23, // 13: sqlmeta.AuthBinding.UserTable:type_name -> sqlmeta.ObjectName
	20, // 14: sqlmeta.AuthBinding.Options:type_name -> sqlmeta.AuthBinding.OptionsEntry
	0,  // 15: sqlmeta.CRUDPolicy.Operations:type_name -> sqlmeta.CRUDOperation
	1,  // 16: sqlmeta.RoleScope.Mode:type_name -> sqlmeta.FKTraversalMode
	2,  // 17: sqlmeta.RoleScope.Direction:type_name -> sqlmeta.FKTraversalDirection
	23, // 18: sqlmeta.RoleScope.IncludeTables:type_name -> sqlmeta.ObjectName
	23, // 19: sqlmeta.RoleScope.ExcludeTables:type_name -> sqlmeta.ObjectName
	11, // 20: sqlmeta.SchemaRelationshipOverrides.PrimaryKeys:type_name -> sqlmeta.ManualPrimaryKey
	12, // 21: sqlmeta.SchemaRelationshipOverrides.ForeignKeys:type_name -> sqlmeta.ManualForeignKey
	23, // 22: sqlmeta.ManualPrimaryKey.TableName:type_name -> sqlmeta.ObjectName
	21, // 23: sqlmeta.ManualPrimaryKey.Options:type_name -> sqlmeta.ManualPrimaryKey.OptionsEntry
	23, // 24: sqlmeta.ManualForeignKey.ChildTable:type_name -> sqlmeta.ObjectName
	23, // 25: sqlmeta.ManualForeignKey.ParentTable:type_name -> sqlmeta.ObjectName
	22, // 26: sqlmeta.ManualForeignKey.Options:type_name -> sqlmeta.ManualForeignKey.OptionsEntry
	3,  // 27: sqlmeta.ExpandedAppSpec.Spec:type_name -> sqlmeta.AppSpec
	14, // 28: sqlmeta.ExpandedAppSpec.ComponentGrants:type_name -> sqlmeta.ExpandedComponentGrant
	15, // 29: sqlmeta.ExpandedAppSpec.TableGrants:type_name -> sqlmeta.ExpandedTableGrant
	23, // 30: sqlmeta.ExpandedComponentGrant.TableName:type_name -> sqlmeta.ObjectName
	0,  // 31: sqlmeta.ExpandedComponentGrant.Operations:type_name -> sqlmeta.CRUDOperation
	23, // 32: sqlmeta.ExpandedTableGrant.TableName:type_name -> sqlmeta.ObjectName
	0,  // 33: sqlmeta.ExpandedTableGrant.Operations:type_name -> sqlmeta.CRUDOperation
	23, // 34: sqlmeta.ExpandedTableGrant.TraversalPath:type_name -> sqlmeta.ObjectName
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_app_spec_proto_init() }
func file_app_spec_proto_init() {
	if File_app_spec_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_spec_proto_rawDesc), len(file_app_spec_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_spec_proto_goTypes,
		DependencyIndexes: file_app_spec_proto_depIdxs,
		EnumInfos:         file_app_spec_proto_enumTypes,
		MessageInfos:      file_app_spec_proto_msgTypes,
	}.Build()
	File_app_spec_proto = out.File
	file_app_spec_proto_goTypes = nil
	file_app_spec_proto_depIdxs = nil
}
