// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: bq_meta.proto

package xmeta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a column in a BigQuery table
type BQColumn struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Name                   string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	DataType               *DataType              `protobuf:"bytes,2,opt,name=DataType,proto3" json:"DataType,omitempty"` // Supports STRUCT/ARRAY via sqlight.StructData/ArrayData
	Mode                   string                 `protobuf:"bytes,3,opt,name=Mode,proto3" json:"Mode,omitempty"`         // "NULLABLE", "REQUIRED", "REPEATED"
	Description            string                 `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	PolicyTags             []string               `protobuf:"bytes,5,rep,name=PolicyTags,proto3" json:"PolicyTags,omitempty"`
	DefaultValueExpression string                 `protobuf:"bytes,6,opt,name=DefaultValueExpression,proto3" json:"DefaultValueExpression,omitempty"`
	OrdinalPosition        int32                  `protobuf:"varint,7,opt,name=OrdinalPosition,proto3" json:"OrdinalPosition,omitempty"`
	Collation              string                 `protobuf:"bytes,8,opt,name=Collation,proto3" json:"Collation,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BQColumn) Reset() {
	*x = BQColumn{}
	mi := &file_bq_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BQColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BQColumn) ProtoMessage() {}

func (x *BQColumn) ProtoReflect() protoreflect.Message {
	mi := &file_bq_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BQColumn.ProtoReflect.Descriptor instead.
func (*BQColumn) Descriptor() ([]byte, []int) {
	return file_bq_meta_proto_rawDescGZIP(), []int{0}
}

func (x *BQColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BQColumn) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *BQColumn) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *BQColumn) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BQColumn) GetPolicyTags() []string {
	if x != nil {
		return x.PolicyTags
	}
	return nil
}

func (x *BQColumn) GetDefaultValueExpression() string {
	if x != nil {
		return x.DefaultValueExpression
	}
	return ""
}

func (x *BQColumn) GetOrdinalPosition() int32 {
	if x != nil {
		return x.OrdinalPosition
	}
	return 0
}

func (x *BQColumn) GetCollation() string {
	if x != nil {
		return x.Collation
	}
	return ""
}

// Time-unit partitioning configuration
type BQTimePartitioning struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Type                   string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`   // "DAY", "HOUR", "MONTH", "YEAR"
	Field                  string                 `protobuf:"bytes,2,opt,name=Field,proto3" json:"Field,omitempty"` // Column name
	ExpirationMs           int64                  `protobuf:"varint,3,opt,name=ExpirationMs,proto3" json:"ExpirationMs,omitempty"`
	RequirePartitionFilter bool                   `protobuf:"varint,4,opt,name=RequirePartitionFilter,proto3" json:"RequirePartitionFilter,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BQTimePartitioning) Reset() {
	*x = BQTimePartitioning{}
	mi := &file_bq_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BQTimePartitioning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BQTimePartitioning) ProtoMessage() {}

func (x *BQTimePartitioning) ProtoReflect() protoreflect.Message {
	mi := &file_bq_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BQTimePartitioning.ProtoReflect.Descriptor instead.
func (*BQTimePartitioning) Descriptor() ([]byte, []int) {
	return file_bq_meta_proto_rawDescGZIP(), []int{1}
}

func (x *BQTimePartitioning) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BQTimePartitioning) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *BQTimePartitioning) GetExpirationMs() int64 {
	if x != nil {
		return x.ExpirationMs
	}
	return 0
}

func (x *BQTimePartitioning) GetRequirePartitionFilter() bool {
	if x != nil {
		return x.RequirePartitionFilter
	}
	return false
}

// Integer range partitioning configuration
type BQRangePartitioning struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=Field,proto3" json:"Field,omitempty"`
	Start         int64                  `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	End           int64                  `protobuf:"varint,3,opt,name=End,proto3" json:"End,omitempty"`
	Interval      int64                  `protobuf:"varint,4,opt,name=Interval,proto3" json:"Interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BQRangePartitioning) Reset() {
	*x = BQRangePartitioning{}
	mi := &file_bq_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BQRangePartitioning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BQRangePartitioning) ProtoMessage() {}

func (x *BQRangePartitioning) ProtoReflect() protoreflect.Message {
	mi := &file_bq_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BQRangePartitioning.ProtoReflect.Descriptor instead.
func (*BQRangePartitioning) Descriptor() ([]byte, []int) {
	return file_bq_meta_proto_rawDescGZIP(), []int{2}
}

func (x *BQRangePartitioning) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *BQRangePartitioning) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *BQRangePartitioning) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *BQRangePartitioning) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

// Represents a BigQuery Table
type BQTable struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         *ObjectName            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // Project.Dataset.Table
	FriendlyName string                 `protobuf:"bytes,2,opt,name=FriendlyName,proto3" json:"FriendlyName,omitempty"`
	Type         string                 `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"` // "TABLE", "VIEW", "EXTERNAL", "SNAPSHOT"
	Schema       []*BQColumn            `protobuf:"bytes,4,rep,name=Schema,proto3" json:"Schema,omitempty"`
	// Partitioning
	//
	// Types that are valid to be assigned to Partitioning:
	//
	//	*BQTable_TimePartitioning
	//	*BQTable_RangePartitioning
	Partitioning   isBQTable_Partitioning `protobuf_oneof:"Partitioning"`
	Clustering     []string               `protobuf:"bytes,7,rep,name=Clustering,proto3" json:"Clustering,omitempty"` // Clustered columns
	NumRows        int64                  `protobuf:"varint,8,opt,name=NumRows,proto3" json:"NumRows,omitempty"`
	TotalBytes     int64                  `protobuf:"varint,9,opt,name=TotalBytes,proto3" json:"TotalBytes,omitempty"`
	CreationTime   string                 `protobuf:"bytes,10,opt,name=CreationTime,proto3" json:"CreationTime,omitempty"`
	ExpirationTime string                 `protobuf:"bytes,11,opt,name=ExpirationTime,proto3" json:"ExpirationTime,omitempty"`
	Description    string                 `protobuf:"bytes,12,opt,name=Description,proto3" json:"Description,omitempty"`
	Labels         map[string]string      `protobuf:"bytes,13,rep,name=Labels,proto3" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ViewQuery      string                 `protobuf:"bytes,14,opt,name=ViewQuery,proto3" json:"ViewQuery,omitempty"` // If Type == VIEW
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BQTable) Reset() {
	*x = BQTable{}
	mi := &file_bq_meta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BQTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BQTable) ProtoMessage() {}

func (x *BQTable) ProtoReflect() protoreflect.Message {
	mi := &file_bq_meta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BQTable.ProtoReflect.Descriptor instead.
func (*BQTable) Descriptor() ([]byte, []int) {
	return file_bq_meta_proto_rawDescGZIP(), []int{3}
}

func (x *BQTable) GetName() *ObjectName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *BQTable) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *BQTable) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BQTable) GetSchema() []*BQColumn {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *BQTable) GetPartitioning() isBQTable_Partitioning {
	if x != nil {
		return x.Partitioning
	}
	return nil
}

func (x *BQTable) GetTimePartitioning() *BQTimePartitioning {
	if x != nil {
		if x, ok := x.Partitioning.(*BQTable_TimePartitioning); ok {
			return x.TimePartitioning
		}
	}
	return nil
}

func (x *BQTable) GetRangePartitioning() *BQRangePartitioning {
	if x != nil {
		if x, ok := x.Partitioning.(*BQTable_RangePartitioning); ok {
			return x.RangePartitioning
		}
	}
	return nil
}

func (x *BQTable) GetClustering() []string {
	if x != nil {
		return x.Clustering
	}
	return nil
}

func (x *BQTable) GetNumRows() int64 {
	if x != nil {
		return x.NumRows
	}
	return 0
}

func (x *BQTable) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *BQTable) GetCreationTime() string {
	if x != nil {
		return x.CreationTime
	}
	return ""
}

func (x *BQTable) GetExpirationTime() string {
	if x != nil {
		return x.ExpirationTime
	}
	return ""
}

func (x *BQTable) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BQTable) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *BQTable) GetViewQuery() string {
	if x != nil {
		return x.ViewQuery
	}
	return ""
}

type isBQTable_Partitioning interface {
	isBQTable_Partitioning()
}

type BQTable_TimePartitioning struct {
	TimePartitioning *BQTimePartitioning `protobuf:"bytes,5,opt,name=TimePartitioning,proto3,oneof"`
}

type BQTable_RangePartitioning struct {
	RangePartitioning *BQRangePartitioning `protobuf:"bytes,6,opt,name=RangePartitioning,proto3,oneof"`
}

func (*BQTable_TimePartitioning) isBQTable_Partitioning() {}

func (*BQTable_RangePartitioning) isBQTable_Partitioning() {}

// Represents a BigQuery Dataset
type BQDataset struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Name                     *ObjectName            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`         // Project.Dataset
	Location                 string                 `protobuf:"bytes,2,opt,name=Location,proto3" json:"Location,omitempty"` // "US", "EU", etc.
	Description              string                 `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Labels                   map[string]string      `protobuf:"bytes,4,rep,name=Labels,proto3" json:"Labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DefaultTableExpirationMs int64                  `protobuf:"varint,5,opt,name=DefaultTableExpirationMs,proto3" json:"DefaultTableExpirationMs,omitempty"`
	Tables                   []*BQTable             `protobuf:"bytes,6,rep,name=Tables,proto3" json:"Tables,omitempty"`
	CreatorParameters        string                 `protobuf:"bytes,7,opt,name=CreatorParameters,proto3" json:"CreatorParameters,omitempty"` // Internal/Access info
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *BQDataset) Reset() {
	*x = BQDataset{}
	mi := &file_bq_meta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BQDataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BQDataset) ProtoMessage() {}

func (x *BQDataset) ProtoReflect() protoreflect.Message {
	mi := &file_bq_meta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BQDataset.ProtoReflect.Descriptor instead.
func (*BQDataset) Descriptor() ([]byte, []int) {
	return file_bq_meta_proto_rawDescGZIP(), []int{4}
}

func (x *BQDataset) GetName() *ObjectName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *BQDataset) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *BQDataset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BQDataset) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *BQDataset) GetDefaultTableExpirationMs() int64 {
	if x != nil {
		return x.DefaultTableExpirationMs
	}
	return 0
}

func (x *BQDataset) GetTables() []*BQTable {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *BQDataset) GetCreatorParameters() string {
	if x != nil {
		return x.CreatorParameters
	}
	return ""
}

// Represents a BigQuery Project / Catalogue
type BQProject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=ProjectId,proto3" json:"ProjectId,omitempty"`
	FriendlyName  string                 `protobuf:"bytes,2,opt,name=FriendlyName,proto3" json:"FriendlyName,omitempty"`
	Datasets      []*BQDataset           `protobuf:"bytes,3,rep,name=Datasets,proto3" json:"Datasets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BQProject) Reset() {
	*x = BQProject{}
	mi := &file_bq_meta_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BQProject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BQProject) ProtoMessage() {}

func (x *BQProject) ProtoReflect() protoreflect.Message {
	mi := &file_bq_meta_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BQProject.ProtoReflect.Descriptor instead.
func (*BQProject) Descriptor() ([]byte, []int) {
	return file_bq_meta_proto_rawDescGZIP(), []int{5}
}

func (x *BQProject) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *BQProject) GetFriendlyName() string {
	if x != nil {
		return x.FriendlyName
	}
	return ""
}

func (x *BQProject) GetDatasets() []*BQDataset {
	if x != nil {
		return x.Datasets
	}
	return nil
}

var File_bq_meta_proto protoreflect.FileDescriptor

const file_bq_meta_proto_rawDesc = "" +
	"\n" +
	"\rbq_meta.proto\x12\x06bqmeta\x1a\vtypes.proto\"\xa3\x02\n" +
	"\bBQColumn\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12-\n" +
	"\bDataType\x18\x02 \x01(\v2\x11.sqlmeta.DataTypeR\bDataType\x12\x12\n" +
	"\x04Mode\x18\x03 \x01(\tR\x04Mode\x12 \n" +
	"\vDescription\x18\x04 \x01(\tR\vDescription\x12\x1e\n" +
	"\n" +
	"PolicyTags\x18\x05 \x03(\tR\n" +
	"PolicyTags\x126\n" +
	"\x16DefaultValueExpression\x18\x06 \x01(\tR\x16DefaultValueExpression\x12(\n" +
	"\x0fOrdinalPosition\x18\a \x01(\x05R\x0fOrdinalPosition\x12\x1c\n" +
	"\tCollation\x18\b \x01(\tR\tCollation\"\x9a\x01\n" +
	"\x12BQTimePartitioning\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x12\x14\n" +
	"\x05Field\x18\x02 \x01(\tR\x05Field\x12\"\n" +
	"\fExpirationMs\x18\x03 \x01(\x03R\fExpirationMs\x126\n" +
	"\x16RequirePartitionFilter\x18\x04 \x01(\bR\x16RequirePartitionFilter\"o\n" +
	"\x13BQRangePartitioning\x12\x14\n" +
	"\x05Field\x18\x01 \x01(\tR\x05Field\x12\x14\n" +
	"\x05Start\x18\x02 \x01(\x03R\x05Start\x12\x10\n" +
	"\x03End\x18\x03 \x01(\x03R\x03End\x12\x1a\n" +
	"\bInterval\x18\x04 \x01(\x03R\bInterval\"\x91\x05\n" +
	"\aBQTable\x12'\n" +
	"\x04Name\x18\x01 \x01(\v2\x13.sqlmeta.ObjectNameR\x04Name\x12\"\n" +
	"\fFriendlyName\x18\x02 \x01(\tR\fFriendlyName\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\tR\x04Type\x12(\n" +
	"\x06Schema\x18\x04 \x03(\v2\x10.bqmeta.BQColumnR\x06Schema\x12H\n" +
	"\x10TimePartitioning\x18\x05 \x01(\v2\x1a.bqmeta.BQTimePartitioningH\x00R\x10TimePartitioning\x12K\n" +
	"\x11RangePartitioning\x18\x06 \x01(\v2\x1b.bqmeta.BQRangePartitioningH\x00R\x11RangePartitioning\x12\x1e\n" +
	"\n" +
	"Clustering\x18\a \x03(\tR\n" +
	"Clustering\x12\x18\n" +
	"\aNumRows\x18\b \x01(\x03R\aNumRows\x12\x1e\n" +
	"\n" +
	"TotalBytes\x18\t \x01(\x03R\n" +
	"TotalBytes\x12\"\n" +
	"\fCreationTime\x18\n" +
	" \x01(\tR\fCreationTime\x12&\n" +
	"\x0eExpirationTime\x18\v \x01(\tR\x0eExpirationTime\x12 \n" +
	"\vDescription\x18\f \x01(\tR\vDescription\x123\n" +
	"\x06Labels\x18\r \x03(\v2\x1b.bqmeta.BQTable.LabelsEntryR\x06Labels\x12\x1c\n" +
	"\tViewQuery\x18\x0e \x01(\tR\tViewQuery\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\fPartitioning\"\xf7\x02\n" +
	"\tBQDataset\x12'\n" +
	"\x04Name\x18\x01 \x01(\v2\x13.sqlmeta.ObjectNameR\x04Name\x12\x1a\n" +
	"\bLocation\x18\x02 \x01(\tR\bLocation\x12 \n" +
	"\vDescription\x18\x03 \x01(\tR\vDescription\x125\n" +
	"\x06Labels\x18\x04 \x03(\v2\x1d.bqmeta.BQDataset.LabelsEntryR\x06Labels\x12:\n" +
	"\x18DefaultTableExpirationMs\x18\x05 \x01(\x03R\x18DefaultTableExpirationMs\x12'\n" +
	"\x06Tables\x18\x06 \x03(\v2\x0f.bqmeta.BQTableR\x06Tables\x12,\n" +
	"\x11CreatorParameters\x18\a \x01(\tR\x11CreatorParameters\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"|\n" +
	"\tBQProject\x12\x1c\n" +
	"\tProjectId\x18\x01 \x01(\tR\tProjectId\x12\"\n" +
	"\fFriendlyName\x18\x02 \x01(\tR\fFriendlyName\x12-\n" +
	"\bDatasets\x18\x03 \x03(\v2\x11.bqmeta.BQDatasetR\bDatasetsB\"Z github.com/genelet/sqlmeta/xmetab\x06proto3"

var (
	file_bq_meta_proto_rawDescOnce sync.Once
	file_bq_meta_proto_rawDescData []byte
)

func file_bq_meta_proto_rawDescGZIP() []byte {
	file_bq_meta_proto_rawDescOnce.Do(func() {
		file_bq_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bq_meta_proto_rawDesc), len(file_bq_meta_proto_rawDesc)))
	})
	return file_bq_meta_proto_rawDescData
}

var file_bq_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_bq_meta_proto_goTypes = []any{
	(*BQColumn)(nil),            // 0: bqmeta.BQColumn
	(*BQTimePartitioning)(nil),  // 1: bqmeta.BQTimePartitioning
	(*BQRangePartitioning)(nil), // 2: bqmeta.BQRangePartitioning
	(*BQTable)(nil),             // 3: bqmeta.BQTable
	(*BQDataset)(nil),           // 4: bqmeta.BQDataset
	(*BQProject)(nil),           // 5: bqmeta.BQProject
	nil,                         // 6: bqmeta.BQTable.LabelsEntry
	nil,                         // 7: bqmeta.BQDataset.LabelsEntry
	(*DataType)(nil),            // 8: sqlmeta.DataType
	(*ObjectName)(nil),          // 9: sqlmeta.ObjectName
}
var file_bq_meta_proto_depIdxs = []int32{
	8,  // 0: bqmeta.BQColumn.DataType:type_name -> sqlmeta.DataType
	9,  // 1: bqmeta.BQTable.Name:type_name -> sqlmeta.ObjectName
	0,  // 2: bqmeta.BQTable.Schema:type_name -> bqmeta.BQColumn
	1,  // 3: bqmeta.BQTable.TimePartitioning:type_name -> bqmeta.BQTimePartitioning
	2,  // 4: bqmeta.BQTable.RangePartitioning:type_name -> bqmeta.BQRangePartitioning
	6,  // 5: bqmeta.BQTable.Labels:type_name -> bqmeta.BQTable.LabelsEntry
	9,  // 6: bqmeta.BQDataset.Name:type_name -> sqlmeta.ObjectName
	7,  // 7: bqmeta.BQDataset.Labels:type_name -> bqmeta.BQDataset.LabelsEntry
	3,  // 8: bqmeta.BQDataset.Tables:type_name -> bqmeta.BQTable
	4,  // 9: bqmeta.BQProject.Datasets:type_name -> bqmeta.BQDataset
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_bq_meta_proto_init() }
func file_bq_meta_proto_init() {
	if File_bq_meta_proto != nil {
		return
	}
	file_types_proto_init()
	file_bq_meta_proto_msgTypes[3].OneofWrappers = []any{
		(*BQTable_TimePartitioning)(nil),
		(*BQTable_RangePartitioning)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bq_meta_proto_rawDesc), len(file_bq_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bq_meta_proto_goTypes,
		DependencyIndexes: file_bq_meta_proto_depIdxs,
		MessageInfos:      file_bq_meta_proto_msgTypes,
	}.Build()
	File_bq_meta_proto = out.File
	file_bq_meta_proto_goTypes = nil
	file_bq_meta_proto_depIdxs = nil
}
