// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: my_meta.proto

package xmeta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a column in a MySQL table
type MYColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	DataType      *DataType              `protobuf:"bytes,2,opt,name=DataType,proto3" json:"DataType,omitempty"`
	IsNullable    bool                   `protobuf:"varint,3,opt,name=IsNullable,proto3" json:"IsNullable,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,4,opt,name=DefaultValue,proto3" json:"DefaultValue,omitempty"`
	IsPrimaryKey  bool                   `protobuf:"varint,5,opt,name=IsPrimaryKey,proto3" json:"IsPrimaryKey,omitempty"`
	AutoIncrement bool                   `protobuf:"varint,6,opt,name=AutoIncrement,proto3" json:"AutoIncrement,omitempty"`
	Charset       string                 `protobuf:"bytes,7,opt,name=Charset,proto3" json:"Charset,omitempty"`
	Collation     string                 `protobuf:"bytes,8,opt,name=Collation,proto3" json:"Collation,omitempty"`
	Comment       string                 `protobuf:"bytes,9,opt,name=Comment,proto3" json:"Comment,omitempty"`
	IsUnsigned    bool                   `protobuf:"varint,10,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
	DisplayWidth  uint32                 `protobuf:"varint,11,opt,name=DisplayWidth,proto3" json:"DisplayWidth,omitempty"` // e.g., int(11)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MYColumn) Reset() {
	*x = MYColumn{}
	mi := &file_my_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MYColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MYColumn) ProtoMessage() {}

func (x *MYColumn) ProtoReflect() protoreflect.Message {
	mi := &file_my_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MYColumn.ProtoReflect.Descriptor instead.
func (*MYColumn) Descriptor() ([]byte, []int) {
	return file_my_meta_proto_rawDescGZIP(), []int{0}
}

func (x *MYColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MYColumn) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *MYColumn) GetIsNullable() bool {
	if x != nil {
		return x.IsNullable
	}
	return false
}

func (x *MYColumn) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *MYColumn) GetIsPrimaryKey() bool {
	if x != nil {
		return x.IsPrimaryKey
	}
	return false
}

func (x *MYColumn) GetAutoIncrement() bool {
	if x != nil {
		return x.AutoIncrement
	}
	return false
}

func (x *MYColumn) GetCharset() string {
	if x != nil {
		return x.Charset
	}
	return ""
}

func (x *MYColumn) GetCollation() string {
	if x != nil {
		return x.Collation
	}
	return ""
}

func (x *MYColumn) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *MYColumn) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

func (x *MYColumn) GetDisplayWidth() uint32 {
	if x != nil {
		return x.DisplayWidth
	}
	return 0
}

// Represents an index in a MySQL table
type MYIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	TableName     *ObjectName            `protobuf:"bytes,2,opt,name=TableName,proto3" json:"TableName,omitempty"`
	IsUnique      bool                   `protobuf:"varint,3,opt,name=IsUnique,proto3" json:"IsUnique,omitempty"`
	IndexType     string                 `protobuf:"bytes,4,opt,name=IndexType,proto3" json:"IndexType,omitempty"` // BTREE, HASH, FULLTEXT, SPATIAL
	Columns       []string               `protobuf:"bytes,5,rep,name=Columns,proto3" json:"Columns,omitempty"`
	IndexComment  string                 `protobuf:"bytes,6,opt,name=IndexComment,proto3" json:"IndexComment,omitempty"`
	PrefixLengths []uint32               `protobuf:"varint,7,rep,packed,name=PrefixLengths,proto3" json:"PrefixLengths,omitempty"` // Prefix length per column (0 = no prefix)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MYIndex) Reset() {
	*x = MYIndex{}
	mi := &file_my_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MYIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MYIndex) ProtoMessage() {}

func (x *MYIndex) ProtoReflect() protoreflect.Message {
	mi := &file_my_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MYIndex.ProtoReflect.Descriptor instead.
func (*MYIndex) Descriptor() ([]byte, []int) {
	return file_my_meta_proto_rawDescGZIP(), []int{1}
}

func (x *MYIndex) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MYIndex) GetTableName() *ObjectName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *MYIndex) GetIsUnique() bool {
	if x != nil {
		return x.IsUnique
	}
	return false
}

func (x *MYIndex) GetIndexType() string {
	if x != nil {
		return x.IndexType
	}
	return ""
}

func (x *MYIndex) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *MYIndex) GetIndexComment() string {
	if x != nil {
		return x.IndexComment
	}
	return ""
}

func (x *MYIndex) GetPrefixLengths() []uint32 {
	if x != nil {
		return x.PrefixLengths
	}
	return nil
}

// Represents a foreign key constraint in MySQL
type MYForeignKey struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	TableName      *ObjectName            `protobuf:"bytes,2,opt,name=TableName,proto3" json:"TableName,omitempty"`
	LocalColumns   []string               `protobuf:"bytes,3,rep,name=LocalColumns,proto3" json:"LocalColumns,omitempty"`
	ForeignTable   *ObjectName            `protobuf:"bytes,4,opt,name=ForeignTable,proto3" json:"ForeignTable,omitempty"`
	ForeignColumns []string               `protobuf:"bytes,5,rep,name=ForeignColumns,proto3" json:"ForeignColumns,omitempty"`
	OnUpdate       string                 `protobuf:"bytes,6,opt,name=OnUpdate,proto3" json:"OnUpdate,omitempty"` // CASCADE, SET NULL, NO ACTION, RESTRICT
	OnDelete       string                 `protobuf:"bytes,7,opt,name=OnDelete,proto3" json:"OnDelete,omitempty"` // CASCADE, SET NULL, NO ACTION, RESTRICT
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MYForeignKey) Reset() {
	*x = MYForeignKey{}
	mi := &file_my_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MYForeignKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MYForeignKey) ProtoMessage() {}

func (x *MYForeignKey) ProtoReflect() protoreflect.Message {
	mi := &file_my_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MYForeignKey.ProtoReflect.Descriptor instead.
func (*MYForeignKey) Descriptor() ([]byte, []int) {
	return file_my_meta_proto_rawDescGZIP(), []int{2}
}

func (x *MYForeignKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MYForeignKey) GetTableName() *ObjectName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *MYForeignKey) GetLocalColumns() []string {
	if x != nil {
		return x.LocalColumns
	}
	return nil
}

func (x *MYForeignKey) GetForeignTable() *ObjectName {
	if x != nil {
		return x.ForeignTable
	}
	return nil
}

func (x *MYForeignKey) GetForeignColumns() []string {
	if x != nil {
		return x.ForeignColumns
	}
	return nil
}

func (x *MYForeignKey) GetOnUpdate() string {
	if x != nil {
		return x.OnUpdate
	}
	return ""
}

func (x *MYForeignKey) GetOnDelete() string {
	if x != nil {
		return x.OnDelete
	}
	return ""
}

// Represents a MySQL table
type MYTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *ObjectName            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Engine        string                 `protobuf:"bytes,2,opt,name=Engine,proto3" json:"Engine,omitempty"` // InnoDB, MyISAM, etc.
	Charset       string                 `protobuf:"bytes,3,opt,name=Charset,proto3" json:"Charset,omitempty"`
	Collation     string                 `protobuf:"bytes,4,opt,name=Collation,proto3" json:"Collation,omitempty"`
	Columns       []*MYColumn            `protobuf:"bytes,5,rep,name=Columns,proto3" json:"Columns,omitempty"`
	Indexes       []*MYIndex             `protobuf:"bytes,6,rep,name=Indexes,proto3" json:"Indexes,omitempty"`
	ForeignKeys   []*MYForeignKey        `protobuf:"bytes,7,rep,name=ForeignKeys,proto3" json:"ForeignKeys,omitempty"`
	Comment       string                 `protobuf:"bytes,8,opt,name=Comment,proto3" json:"Comment,omitempty"`
	AutoIncrement int64                  `protobuf:"varint,9,opt,name=AutoIncrement,proto3" json:"AutoIncrement,omitempty"` // Next auto_increment value
	CreateOptions string                 `protobuf:"bytes,10,opt,name=CreateOptions,proto3" json:"CreateOptions,omitempty"` // row_format=DYNAMIC, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MYTable) Reset() {
	*x = MYTable{}
	mi := &file_my_meta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MYTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MYTable) ProtoMessage() {}

func (x *MYTable) ProtoReflect() protoreflect.Message {
	mi := &file_my_meta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MYTable.ProtoReflect.Descriptor instead.
func (*MYTable) Descriptor() ([]byte, []int) {
	return file_my_meta_proto_rawDescGZIP(), []int{3}
}

func (x *MYTable) GetName() *ObjectName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *MYTable) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *MYTable) GetCharset() string {
	if x != nil {
		return x.Charset
	}
	return ""
}

func (x *MYTable) GetCollation() string {
	if x != nil {
		return x.Collation
	}
	return ""
}

func (x *MYTable) GetColumns() []*MYColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *MYTable) GetIndexes() []*MYIndex {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *MYTable) GetForeignKeys() []*MYForeignKey {
	if x != nil {
		return x.ForeignKeys
	}
	return nil
}

func (x *MYTable) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *MYTable) GetAutoIncrement() int64 {
	if x != nil {
		return x.AutoIncrement
	}
	return 0
}

func (x *MYTable) GetCreateOptions() string {
	if x != nil {
		return x.CreateOptions
	}
	return ""
}

// Represents a MySQL database (schema)
type MYDatabase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Tables        []*MYTable             `protobuf:"bytes,2,rep,name=Tables,proto3" json:"Tables,omitempty"` // Views, routines, etc. can be added later
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MYDatabase) Reset() {
	*x = MYDatabase{}
	mi := &file_my_meta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MYDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MYDatabase) ProtoMessage() {}

func (x *MYDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_my_meta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MYDatabase.ProtoReflect.Descriptor instead.
func (*MYDatabase) Descriptor() ([]byte, []int) {
	return file_my_meta_proto_rawDescGZIP(), []int{4}
}

func (x *MYDatabase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MYDatabase) GetTables() []*MYTable {
	if x != nil {
		return x.Tables
	}
	return nil
}

var File_my_meta_proto protoreflect.FileDescriptor

const file_my_meta_proto_rawDesc = "" +
	"\n" +
	"\rmy_meta.proto\x12\x06mymeta\x1a\vtypes.proto\"\xf1\x02\n" +
	"\bMYColumn\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12-\n" +
	"\bDataType\x18\x02 \x01(\v2\x11.sqlmeta.DataTypeR\bDataType\x12\x1e\n" +
	"\n" +
	"IsNullable\x18\x03 \x01(\bR\n" +
	"IsNullable\x12\"\n" +
	"\fDefaultValue\x18\x04 \x01(\tR\fDefaultValue\x12\"\n" +
	"\fIsPrimaryKey\x18\x05 \x01(\bR\fIsPrimaryKey\x12$\n" +
	"\rAutoIncrement\x18\x06 \x01(\bR\rAutoIncrement\x12\x18\n" +
	"\aCharset\x18\a \x01(\tR\aCharset\x12\x1c\n" +
	"\tCollation\x18\b \x01(\tR\tCollation\x12\x18\n" +
	"\aComment\x18\t \x01(\tR\aComment\x12\x1e\n" +
	"\n" +
	"IsUnsigned\x18\n" +
	" \x01(\bR\n" +
	"IsUnsigned\x12\"\n" +
	"\fDisplayWidth\x18\v \x01(\rR\fDisplayWidth\"\xee\x01\n" +
	"\aMYIndex\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x121\n" +
	"\tTableName\x18\x02 \x01(\v2\x13.sqlmeta.ObjectNameR\tTableName\x12\x1a\n" +
	"\bIsUnique\x18\x03 \x01(\bR\bIsUnique\x12\x1c\n" +
	"\tIndexType\x18\x04 \x01(\tR\tIndexType\x12\x18\n" +
	"\aColumns\x18\x05 \x03(\tR\aColumns\x12\"\n" +
	"\fIndexComment\x18\x06 \x01(\tR\fIndexComment\x12$\n" +
	"\rPrefixLengths\x18\a \x03(\rR\rPrefixLengths\"\x92\x02\n" +
	"\fMYForeignKey\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x121\n" +
	"\tTableName\x18\x02 \x01(\v2\x13.sqlmeta.ObjectNameR\tTableName\x12\"\n" +
	"\fLocalColumns\x18\x03 \x03(\tR\fLocalColumns\x127\n" +
	"\fForeignTable\x18\x04 \x01(\v2\x13.sqlmeta.ObjectNameR\fForeignTable\x12&\n" +
	"\x0eForeignColumns\x18\x05 \x03(\tR\x0eForeignColumns\x12\x1a\n" +
	"\bOnUpdate\x18\x06 \x01(\tR\bOnUpdate\x12\x1a\n" +
	"\bOnDelete\x18\a \x01(\tR\bOnDelete\"\xf7\x02\n" +
	"\aMYTable\x12'\n" +
	"\x04Name\x18\x01 \x01(\v2\x13.sqlmeta.ObjectNameR\x04Name\x12\x16\n" +
	"\x06Engine\x18\x02 \x01(\tR\x06Engine\x12\x18\n" +
	"\aCharset\x18\x03 \x01(\tR\aCharset\x12\x1c\n" +
	"\tCollation\x18\x04 \x01(\tR\tCollation\x12*\n" +
	"\aColumns\x18\x05 \x03(\v2\x10.mymeta.MYColumnR\aColumns\x12)\n" +
	"\aIndexes\x18\x06 \x03(\v2\x0f.mymeta.MYIndexR\aIndexes\x126\n" +
	"\vForeignKeys\x18\a \x03(\v2\x14.mymeta.MYForeignKeyR\vForeignKeys\x12\x18\n" +
	"\aComment\x18\b \x01(\tR\aComment\x12$\n" +
	"\rAutoIncrement\x18\t \x01(\x03R\rAutoIncrement\x12$\n" +
	"\rCreateOptions\x18\n" +
	" \x01(\tR\rCreateOptions\"I\n" +
	"\n" +
	"MYDatabase\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12'\n" +
	"\x06Tables\x18\x02 \x03(\v2\x0f.mymeta.MYTableR\x06TablesB\"Z github.com/genelet/sqlmeta/xmetab\x06proto3"

var (
	file_my_meta_proto_rawDescOnce sync.Once
	file_my_meta_proto_rawDescData []byte
)

func file_my_meta_proto_rawDescGZIP() []byte {
	file_my_meta_proto_rawDescOnce.Do(func() {
		file_my_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_my_meta_proto_rawDesc), len(file_my_meta_proto_rawDesc)))
	})
	return file_my_meta_proto_rawDescData
}

var file_my_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_my_meta_proto_goTypes = []any{
	(*MYColumn)(nil),     // 0: mymeta.MYColumn
	(*MYIndex)(nil),      // 1: mymeta.MYIndex
	(*MYForeignKey)(nil), // 2: mymeta.MYForeignKey
	(*MYTable)(nil),      // 3: mymeta.MYTable
	(*MYDatabase)(nil),   // 4: mymeta.MYDatabase
	(*DataType)(nil),     // 5: sqlmeta.DataType
	(*ObjectName)(nil),   // 6: sqlmeta.ObjectName
}
var file_my_meta_proto_depIdxs = []int32{
	5, // 0: mymeta.MYColumn.DataType:type_name -> sqlmeta.DataType
	6, // 1: mymeta.MYIndex.TableName:type_name -> sqlmeta.ObjectName
	6, // 2: mymeta.MYForeignKey.TableName:type_name -> sqlmeta.ObjectName
	6, // 3: mymeta.MYForeignKey.ForeignTable:type_name -> sqlmeta.ObjectName
	6, // 4: mymeta.MYTable.Name:type_name -> sqlmeta.ObjectName
	0, // 5: mymeta.MYTable.Columns:type_name -> mymeta.MYColumn
	1, // 6: mymeta.MYTable.Indexes:type_name -> mymeta.MYIndex
	2, // 7: mymeta.MYTable.ForeignKeys:type_name -> mymeta.MYForeignKey
	3, // 8: mymeta.MYDatabase.Tables:type_name -> mymeta.MYTable
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_my_meta_proto_init() }
func file_my_meta_proto_init() {
	if File_my_meta_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_my_meta_proto_rawDesc), len(file_my_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_my_meta_proto_goTypes,
		DependencyIndexes: file_my_meta_proto_depIdxs,
		MessageInfos:      file_my_meta_proto_msgTypes,
	}.Build()
	File_my_meta_proto = out.File
	file_my_meta_proto_goTypes = nil
	file_my_meta_proto_depIdxs = nil
}
