// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: pg_meta.proto

package xmeta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a column in a PostgreSQL table
type PGColumn struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	DataType             *DataType              `protobuf:"bytes,2,opt,name=DataType,proto3" json:"DataType,omitempty"` // Uses sqlight.Type to capture full type info (size, precision, etc.)
	IsNullable           bool                   `protobuf:"varint,3,opt,name=IsNullable,proto3" json:"IsNullable,omitempty"`
	DefaultValue         string                 `protobuf:"bytes,4,opt,name=DefaultValue,proto3" json:"DefaultValue,omitempty"` // Default expression string (e.g. "nextval('seq')")
	OrdinalPosition      int32                  `protobuf:"varint,8,opt,name=OrdinalPosition,proto3" json:"OrdinalPosition,omitempty"`
	IsIdentity           bool                   `protobuf:"varint,9,opt,name=IsIdentity,proto3" json:"IsIdentity,omitempty"`
	IdentityGeneration   string                 `protobuf:"bytes,10,opt,name=IdentityGeneration,proto3" json:"IdentityGeneration,omitempty"` // "ALWAYS" or "BY DEFAULT"
	IdentitySequence     string                 `protobuf:"bytes,11,opt,name=IdentitySequence,proto3" json:"IdentitySequence,omitempty"`
	IsGenerated          bool                   `protobuf:"varint,12,opt,name=IsGenerated,proto3" json:"IsGenerated,omitempty"`
	GenerationExpression string                 `protobuf:"bytes,13,opt,name=GenerationExpression,proto3" json:"GenerationExpression,omitempty"`
	Comment              string                 `protobuf:"bytes,14,opt,name=Comment,proto3" json:"Comment,omitempty"`
	IsPrimaryKey         bool                   `protobuf:"varint,15,opt,name=IsPrimaryKey,proto3" json:"IsPrimaryKey,omitempty"` // Column is part of primary key
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PGColumn) Reset() {
	*x = PGColumn{}
	mi := &file_pg_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGColumn) ProtoMessage() {}

func (x *PGColumn) ProtoReflect() protoreflect.Message {
	mi := &file_pg_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGColumn.ProtoReflect.Descriptor instead.
func (*PGColumn) Descriptor() ([]byte, []int) {
	return file_pg_meta_proto_rawDescGZIP(), []int{0}
}

func (x *PGColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PGColumn) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *PGColumn) GetIsNullable() bool {
	if x != nil {
		return x.IsNullable
	}
	return false
}

func (x *PGColumn) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *PGColumn) GetOrdinalPosition() int32 {
	if x != nil {
		return x.OrdinalPosition
	}
	return 0
}

func (x *PGColumn) GetIsIdentity() bool {
	if x != nil {
		return x.IsIdentity
	}
	return false
}

func (x *PGColumn) GetIdentityGeneration() string {
	if x != nil {
		return x.IdentityGeneration
	}
	return ""
}

func (x *PGColumn) GetIdentitySequence() string {
	if x != nil {
		return x.IdentitySequence
	}
	return ""
}

func (x *PGColumn) GetIsGenerated() bool {
	if x != nil {
		return x.IsGenerated
	}
	return false
}

func (x *PGColumn) GetGenerationExpression() string {
	if x != nil {
		return x.GenerationExpression
	}
	return ""
}

func (x *PGColumn) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *PGColumn) GetIsPrimaryKey() bool {
	if x != nil {
		return x.IsPrimaryKey
	}
	return false
}

// Represents an index on a PostgreSQL table
type PGIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	TableName     *ObjectName            `protobuf:"bytes,2,opt,name=TableName,proto3" json:"TableName,omitempty"` // Includes Schema if present
	IsUnique      bool                   `protobuf:"varint,4,opt,name=IsUnique,proto3" json:"IsUnique,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,5,opt,name=IsPrimary,proto3" json:"IsPrimary,omitempty"`
	IsClustered   bool                   `protobuf:"varint,6,opt,name=IsClustered,proto3" json:"IsClustered,omitempty"`
	IsValid       bool                   `protobuf:"varint,7,opt,name=IsValid,proto3" json:"IsValid,omitempty"`
	AccessMethod  string                 `protobuf:"bytes,8,opt,name=AccessMethod,proto3" json:"AccessMethod,omitempty"` // e.g., "btree"
	Columns       []string               `protobuf:"bytes,9,rep,name=Columns,proto3" json:"Columns,omitempty"`
	Definition    string                 `protobuf:"bytes,10,opt,name=Definition,proto3" json:"Definition,omitempty"`
	Comment       string                 `protobuf:"bytes,11,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PGIndex) Reset() {
	*x = PGIndex{}
	mi := &file_pg_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGIndex) ProtoMessage() {}

func (x *PGIndex) ProtoReflect() protoreflect.Message {
	mi := &file_pg_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGIndex.ProtoReflect.Descriptor instead.
func (*PGIndex) Descriptor() ([]byte, []int) {
	return file_pg_meta_proto_rawDescGZIP(), []int{1}
}

func (x *PGIndex) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PGIndex) GetTableName() *ObjectName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *PGIndex) GetIsUnique() bool {
	if x != nil {
		return x.IsUnique
	}
	return false
}

func (x *PGIndex) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *PGIndex) GetIsClustered() bool {
	if x != nil {
		return x.IsClustered
	}
	return false
}

func (x *PGIndex) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *PGIndex) GetAccessMethod() string {
	if x != nil {
		return x.AccessMethod
	}
	return ""
}

func (x *PGIndex) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *PGIndex) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *PGIndex) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// Represents a foreign key constraint
type PGForeignKey struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	TableName      *ObjectName            `protobuf:"bytes,2,opt,name=TableName,proto3" json:"TableName,omitempty"` // Source Table
	LocalColumns   []string               `protobuf:"bytes,4,rep,name=LocalColumns,proto3" json:"LocalColumns,omitempty"`
	ForeignTable   *ObjectName            `protobuf:"bytes,5,opt,name=ForeignTable,proto3" json:"ForeignTable,omitempty"` // Target Table
	ForeignColumns []string               `protobuf:"bytes,7,rep,name=ForeignColumns,proto3" json:"ForeignColumns,omitempty"`
	OnUpdate       string                 `protobuf:"bytes,8,opt,name=OnUpdate,proto3" json:"OnUpdate,omitempty"`
	OnDelete       string                 `protobuf:"bytes,9,opt,name=OnDelete,proto3" json:"OnDelete,omitempty"`
	MatchOption    string                 `protobuf:"bytes,10,opt,name=MatchOption,proto3" json:"MatchOption,omitempty"`
	Definition     string                 `protobuf:"bytes,11,opt,name=Definition,proto3" json:"Definition,omitempty"`
	Comment        string                 `protobuf:"bytes,12,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PGForeignKey) Reset() {
	*x = PGForeignKey{}
	mi := &file_pg_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGForeignKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGForeignKey) ProtoMessage() {}

func (x *PGForeignKey) ProtoReflect() protoreflect.Message {
	mi := &file_pg_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGForeignKey.ProtoReflect.Descriptor instead.
func (*PGForeignKey) Descriptor() ([]byte, []int) {
	return file_pg_meta_proto_rawDescGZIP(), []int{2}
}

func (x *PGForeignKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PGForeignKey) GetTableName() *ObjectName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *PGForeignKey) GetLocalColumns() []string {
	if x != nil {
		return x.LocalColumns
	}
	return nil
}

func (x *PGForeignKey) GetForeignTable() *ObjectName {
	if x != nil {
		return x.ForeignTable
	}
	return nil
}

func (x *PGForeignKey) GetForeignColumns() []string {
	if x != nil {
		return x.ForeignColumns
	}
	return nil
}

func (x *PGForeignKey) GetOnUpdate() string {
	if x != nil {
		return x.OnUpdate
	}
	return ""
}

func (x *PGForeignKey) GetOnDelete() string {
	if x != nil {
		return x.OnDelete
	}
	return ""
}

func (x *PGForeignKey) GetMatchOption() string {
	if x != nil {
		return x.MatchOption
	}
	return ""
}

func (x *PGForeignKey) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *PGForeignKey) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// Represents other constraints (Primary Key, Unique, Check, Exclusion)
type PGConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	TableName     *ObjectName            `protobuf:"bytes,3,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"` // "p", "u", "c", "x"
	Columns       []string               `protobuf:"bytes,5,rep,name=Columns,proto3" json:"Columns,omitempty"`
	Definition    string                 `protobuf:"bytes,6,opt,name=Definition,proto3" json:"Definition,omitempty"`
	Comment       string                 `protobuf:"bytes,7,opt,name=Comment,proto3" json:"Comment,omitempty"`
	IsDeferrable  bool                   `protobuf:"varint,8,opt,name=IsDeferrable,proto3" json:"IsDeferrable,omitempty"`
	IsDeferred    bool                   `protobuf:"varint,9,opt,name=IsDeferred,proto3" json:"IsDeferred,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PGConstraint) Reset() {
	*x = PGConstraint{}
	mi := &file_pg_meta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGConstraint) ProtoMessage() {}

func (x *PGConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_pg_meta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGConstraint.ProtoReflect.Descriptor instead.
func (*PGConstraint) Descriptor() ([]byte, []int) {
	return file_pg_meta_proto_rawDescGZIP(), []int{3}
}

func (x *PGConstraint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PGConstraint) GetTableName() *ObjectName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *PGConstraint) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PGConstraint) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *PGConstraint) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *PGConstraint) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *PGConstraint) GetIsDeferrable() bool {
	if x != nil {
		return x.IsDeferrable
	}
	return false
}

func (x *PGConstraint) GetIsDeferred() bool {
	if x != nil {
		return x.IsDeferred
	}
	return false
}

// Represents a PostgreSQL Sequence
type PGSequence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *ObjectName            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	DataType      *DataType              `protobuf:"bytes,3,opt,name=DataType,proto3" json:"DataType,omitempty"`
	StartValue    int64                  `protobuf:"varint,4,opt,name=StartValue,proto3" json:"StartValue,omitempty"`
	MinValue      int64                  `protobuf:"varint,5,opt,name=MinValue,proto3" json:"MinValue,omitempty"`
	MaxValue      int64                  `protobuf:"varint,6,opt,name=MaxValue,proto3" json:"MaxValue,omitempty"`
	IncrementBy   int64                  `protobuf:"varint,7,opt,name=IncrementBy,proto3" json:"IncrementBy,omitempty"`
	Cycle         bool                   `protobuf:"varint,8,opt,name=Cycle,proto3" json:"Cycle,omitempty"`
	CacheSize     int64                  `protobuf:"varint,9,opt,name=CacheSize,proto3" json:"CacheSize,omitempty"`
	LastValue     int64                  `protobuf:"varint,10,opt,name=LastValue,proto3" json:"LastValue,omitempty"`
	OwnerTable    *ObjectName            `protobuf:"bytes,11,opt,name=OwnerTable,proto3" json:"OwnerTable,omitempty"`
	OwnerColumn   string                 `protobuf:"bytes,12,opt,name=OwnerColumn,proto3" json:"OwnerColumn,omitempty"`
	Comment       string                 `protobuf:"bytes,13,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PGSequence) Reset() {
	*x = PGSequence{}
	mi := &file_pg_meta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGSequence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGSequence) ProtoMessage() {}

func (x *PGSequence) ProtoReflect() protoreflect.Message {
	mi := &file_pg_meta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGSequence.ProtoReflect.Descriptor instead.
func (*PGSequence) Descriptor() ([]byte, []int) {
	return file_pg_meta_proto_rawDescGZIP(), []int{4}
}

func (x *PGSequence) GetName() *ObjectName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *PGSequence) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *PGSequence) GetStartValue() int64 {
	if x != nil {
		return x.StartValue
	}
	return 0
}

func (x *PGSequence) GetMinValue() int64 {
	if x != nil {
		return x.MinValue
	}
	return 0
}

func (x *PGSequence) GetMaxValue() int64 {
	if x != nil {
		return x.MaxValue
	}
	return 0
}

func (x *PGSequence) GetIncrementBy() int64 {
	if x != nil {
		return x.IncrementBy
	}
	return 0
}

func (x *PGSequence) GetCycle() bool {
	if x != nil {
		return x.Cycle
	}
	return false
}

func (x *PGSequence) GetCacheSize() int64 {
	if x != nil {
		return x.CacheSize
	}
	return 0
}

func (x *PGSequence) GetLastValue() int64 {
	if x != nil {
		return x.LastValue
	}
	return 0
}

func (x *PGSequence) GetOwnerTable() *ObjectName {
	if x != nil {
		return x.OwnerTable
	}
	return nil
}

func (x *PGSequence) GetOwnerColumn() string {
	if x != nil {
		return x.OwnerColumn
	}
	return ""
}

func (x *PGSequence) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// Represents a PostgreSQL Table
type PGTable struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              *ObjectName            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // Includes Schema
	Owner             string                 `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`
	TableType         string                 `protobuf:"bytes,4,opt,name=TableType,proto3" json:"TableType,omitempty"` // "BASE TABLE", "VIEW", etc.
	Columns           []*PGColumn            `protobuf:"bytes,5,rep,name=Columns,proto3" json:"Columns,omitempty"`
	Indexes           []*PGIndex             `protobuf:"bytes,6,rep,name=Indexes,proto3" json:"Indexes,omitempty"`
	Constraints       []*PGConstraint        `protobuf:"bytes,7,rep,name=Constraints,proto3" json:"Constraints,omitempty"`
	ForeignKeys       []*PGForeignKey        `protobuf:"bytes,8,rep,name=ForeignKeys,proto3" json:"ForeignKeys,omitempty"`
	Triggers          []string               `protobuf:"bytes,9,rep,name=Triggers,proto3" json:"Triggers,omitempty"`
	Persistence       string                 `protobuf:"bytes,10,opt,name=Persistence,proto3" json:"Persistence,omitempty"`
	HasRowSecurity    bool                   `protobuf:"varint,11,opt,name=HasRowSecurity,proto3" json:"HasRowSecurity,omitempty"`
	RowSecurityForced bool                   `protobuf:"varint,12,opt,name=RowSecurityForced,proto3" json:"RowSecurityForced,omitempty"`
	Comment           string                 `protobuf:"bytes,13,opt,name=Comment,proto3" json:"Comment,omitempty"`
	EstimatedRows     int64                  `protobuf:"varint,14,opt,name=EstimatedRows,proto3" json:"EstimatedRows,omitempty"`
	TotalBytes        int64                  `protobuf:"varint,15,opt,name=TotalBytes,proto3" json:"TotalBytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PGTable) Reset() {
	*x = PGTable{}
	mi := &file_pg_meta_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGTable) ProtoMessage() {}

func (x *PGTable) ProtoReflect() protoreflect.Message {
	mi := &file_pg_meta_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGTable.ProtoReflect.Descriptor instead.
func (*PGTable) Descriptor() ([]byte, []int) {
	return file_pg_meta_proto_rawDescGZIP(), []int{5}
}

func (x *PGTable) GetName() *ObjectName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *PGTable) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PGTable) GetTableType() string {
	if x != nil {
		return x.TableType
	}
	return ""
}

func (x *PGTable) GetColumns() []*PGColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *PGTable) GetIndexes() []*PGIndex {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *PGTable) GetConstraints() []*PGConstraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *PGTable) GetForeignKeys() []*PGForeignKey {
	if x != nil {
		return x.ForeignKeys
	}
	return nil
}

func (x *PGTable) GetTriggers() []string {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *PGTable) GetPersistence() string {
	if x != nil {
		return x.Persistence
	}
	return ""
}

func (x *PGTable) GetHasRowSecurity() bool {
	if x != nil {
		return x.HasRowSecurity
	}
	return false
}

func (x *PGTable) GetRowSecurityForced() bool {
	if x != nil {
		return x.RowSecurityForced
	}
	return false
}

func (x *PGTable) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *PGTable) GetEstimatedRows() int64 {
	if x != nil {
		return x.EstimatedRows
	}
	return 0
}

func (x *PGTable) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

// Represents a PostgreSQL View
type PGView struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           *ObjectName            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Owner          string                 `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Definition     string                 `protobuf:"bytes,4,opt,name=Definition,proto3" json:"Definition,omitempty"`
	IsMaterialized bool                   `protobuf:"varint,5,opt,name=IsMaterialized,proto3" json:"IsMaterialized,omitempty"`
	Columns        []*PGColumn            `protobuf:"bytes,6,rep,name=Columns,proto3" json:"Columns,omitempty"`
	Comment        string                 `protobuf:"bytes,7,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PGView) Reset() {
	*x = PGView{}
	mi := &file_pg_meta_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGView) ProtoMessage() {}

func (x *PGView) ProtoReflect() protoreflect.Message {
	mi := &file_pg_meta_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGView.ProtoReflect.Descriptor instead.
func (*PGView) Descriptor() ([]byte, []int) {
	return file_pg_meta_proto_rawDescGZIP(), []int{6}
}

func (x *PGView) GetName() *ObjectName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *PGView) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PGView) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *PGView) GetIsMaterialized() bool {
	if x != nil {
		return x.IsMaterialized
	}
	return false
}

func (x *PGView) GetColumns() []*PGColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *PGView) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// Represents a PostgreSQL Schema (Namespace)
type PGSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Tables        []*PGTable             `protobuf:"bytes,3,rep,name=Tables,proto3" json:"Tables,omitempty"`
	Views         []*PGView              `protobuf:"bytes,4,rep,name=Views,proto3" json:"Views,omitempty"`
	Sequences     []*PGSequence          `protobuf:"bytes,5,rep,name=Sequences,proto3" json:"Sequences,omitempty"`
	Domains       []*PGConstraint        `protobuf:"bytes,6,rep,name=Domains,proto3" json:"Domains,omitempty"`
	Comment       string                 `protobuf:"bytes,7,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PGSchema) Reset() {
	*x = PGSchema{}
	mi := &file_pg_meta_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGSchema) ProtoMessage() {}

func (x *PGSchema) ProtoReflect() protoreflect.Message {
	mi := &file_pg_meta_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGSchema.ProtoReflect.Descriptor instead.
func (*PGSchema) Descriptor() ([]byte, []int) {
	return file_pg_meta_proto_rawDescGZIP(), []int{7}
}

func (x *PGSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PGSchema) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *PGSchema) GetTables() []*PGTable {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *PGSchema) GetViews() []*PGView {
	if x != nil {
		return x.Views
	}
	return nil
}

func (x *PGSchema) GetSequences() []*PGSequence {
	if x != nil {
		return x.Sequences
	}
	return nil
}

func (x *PGSchema) GetDomains() []*PGConstraint {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *PGSchema) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type PGDatabase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=Version,proto3" json:"Version,omitempty"`
	Schemas       []*PGSchema            `protobuf:"bytes,3,rep,name=Schemas,proto3" json:"Schemas,omitempty"`
	Extensions    []string               `protobuf:"bytes,4,rep,name=Extensions,proto3" json:"Extensions,omitempty"`
	Comment       string                 `protobuf:"bytes,5,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PGDatabase) Reset() {
	*x = PGDatabase{}
	mi := &file_pg_meta_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PGDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PGDatabase) ProtoMessage() {}

func (x *PGDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_pg_meta_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PGDatabase.ProtoReflect.Descriptor instead.
func (*PGDatabase) Descriptor() ([]byte, []int) {
	return file_pg_meta_proto_rawDescGZIP(), []int{8}
}

func (x *PGDatabase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PGDatabase) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PGDatabase) GetSchemas() []*PGSchema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

func (x *PGDatabase) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *PGDatabase) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_pg_meta_proto protoreflect.FileDescriptor

const file_pg_meta_proto_rawDesc = "" +
	"\n" +
	"\rpg_meta.proto\x12\x06pgmeta\x1a\vtypes.proto\"\xcb\x03\n" +
	"\bPGColumn\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12-\n" +
	"\bDataType\x18\x02 \x01(\v2\x11.sqlmeta.DataTypeR\bDataType\x12\x1e\n" +
	"\n" +
	"IsNullable\x18\x03 \x01(\bR\n" +
	"IsNullable\x12\"\n" +
	"\fDefaultValue\x18\x04 \x01(\tR\fDefaultValue\x12(\n" +
	"\x0fOrdinalPosition\x18\b \x01(\x05R\x0fOrdinalPosition\x12\x1e\n" +
	"\n" +
	"IsIdentity\x18\t \x01(\bR\n" +
	"IsIdentity\x12.\n" +
	"\x12IdentityGeneration\x18\n" +
	" \x01(\tR\x12IdentityGeneration\x12*\n" +
	"\x10IdentitySequence\x18\v \x01(\tR\x10IdentitySequence\x12 \n" +
	"\vIsGenerated\x18\f \x01(\bR\vIsGenerated\x122\n" +
	"\x14GenerationExpression\x18\r \x01(\tR\x14GenerationExpression\x12\x18\n" +
	"\aComment\x18\x0e \x01(\tR\aComment\x12\"\n" +
	"\fIsPrimaryKey\x18\x0f \x01(\bR\fIsPrimaryKey\"\xbe\x02\n" +
	"\aPGIndex\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x121\n" +
	"\tTableName\x18\x02 \x01(\v2\x13.sqlmeta.ObjectNameR\tTableName\x12\x1a\n" +
	"\bIsUnique\x18\x04 \x01(\bR\bIsUnique\x12\x1c\n" +
	"\tIsPrimary\x18\x05 \x01(\bR\tIsPrimary\x12 \n" +
	"\vIsClustered\x18\x06 \x01(\bR\vIsClustered\x12\x18\n" +
	"\aIsValid\x18\a \x01(\bR\aIsValid\x12\"\n" +
	"\fAccessMethod\x18\b \x01(\tR\fAccessMethod\x12\x18\n" +
	"\aColumns\x18\t \x03(\tR\aColumns\x12\x1e\n" +
	"\n" +
	"Definition\x18\n" +
	" \x01(\tR\n" +
	"Definition\x12\x18\n" +
	"\aComment\x18\v \x01(\tR\aComment\"\xee\x02\n" +
	"\fPGForeignKey\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x121\n" +
	"\tTableName\x18\x02 \x01(\v2\x13.sqlmeta.ObjectNameR\tTableName\x12\"\n" +
	"\fLocalColumns\x18\x04 \x03(\tR\fLocalColumns\x127\n" +
	"\fForeignTable\x18\x05 \x01(\v2\x13.sqlmeta.ObjectNameR\fForeignTable\x12&\n" +
	"\x0eForeignColumns\x18\a \x03(\tR\x0eForeignColumns\x12\x1a\n" +
	"\bOnUpdate\x18\b \x01(\tR\bOnUpdate\x12\x1a\n" +
	"\bOnDelete\x18\t \x01(\tR\bOnDelete\x12 \n" +
	"\vMatchOption\x18\n" +
	" \x01(\tR\vMatchOption\x12\x1e\n" +
	"\n" +
	"Definition\x18\v \x01(\tR\n" +
	"Definition\x12\x18\n" +
	"\aComment\x18\f \x01(\tR\aComment\"\x81\x02\n" +
	"\fPGConstraint\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x121\n" +
	"\tTableName\x18\x03 \x01(\v2\x13.sqlmeta.ObjectNameR\tTableName\x12\x12\n" +
	"\x04Type\x18\x04 \x01(\tR\x04Type\x12\x18\n" +
	"\aColumns\x18\x05 \x03(\tR\aColumns\x12\x1e\n" +
	"\n" +
	"Definition\x18\x06 \x01(\tR\n" +
	"Definition\x12\x18\n" +
	"\aComment\x18\a \x01(\tR\aComment\x12\"\n" +
	"\fIsDeferrable\x18\b \x01(\bR\fIsDeferrable\x12\x1e\n" +
	"\n" +
	"IsDeferred\x18\t \x01(\bR\n" +
	"IsDeferred\"\xa1\x03\n" +
	"\n" +
	"PGSequence\x12'\n" +
	"\x04Name\x18\x01 \x01(\v2\x13.sqlmeta.ObjectNameR\x04Name\x12-\n" +
	"\bDataType\x18\x03 \x01(\v2\x11.sqlmeta.DataTypeR\bDataType\x12\x1e\n" +
	"\n" +
	"StartValue\x18\x04 \x01(\x03R\n" +
	"StartValue\x12\x1a\n" +
	"\bMinValue\x18\x05 \x01(\x03R\bMinValue\x12\x1a\n" +
	"\bMaxValue\x18\x06 \x01(\x03R\bMaxValue\x12 \n" +
	"\vIncrementBy\x18\a \x01(\x03R\vIncrementBy\x12\x14\n" +
	"\x05Cycle\x18\b \x01(\bR\x05Cycle\x12\x1c\n" +
	"\tCacheSize\x18\t \x01(\x03R\tCacheSize\x12\x1c\n" +
	"\tLastValue\x18\n" +
	" \x01(\x03R\tLastValue\x123\n" +
	"\n" +
	"OwnerTable\x18\v \x01(\v2\x13.sqlmeta.ObjectNameR\n" +
	"OwnerTable\x12 \n" +
	"\vOwnerColumn\x18\f \x01(\tR\vOwnerColumn\x12\x18\n" +
	"\aComment\x18\r \x01(\tR\aComment\"\xa1\x04\n" +
	"\aPGTable\x12'\n" +
	"\x04Name\x18\x01 \x01(\v2\x13.sqlmeta.ObjectNameR\x04Name\x12\x14\n" +
	"\x05Owner\x18\x03 \x01(\tR\x05Owner\x12\x1c\n" +
	"\tTableType\x18\x04 \x01(\tR\tTableType\x12*\n" +
	"\aColumns\x18\x05 \x03(\v2\x10.pgmeta.PGColumnR\aColumns\x12)\n" +
	"\aIndexes\x18\x06 \x03(\v2\x0f.pgmeta.PGIndexR\aIndexes\x126\n" +
	"\vConstraints\x18\a \x03(\v2\x14.pgmeta.PGConstraintR\vConstraints\x126\n" +
	"\vForeignKeys\x18\b \x03(\v2\x14.pgmeta.PGForeignKeyR\vForeignKeys\x12\x1a\n" +
	"\bTriggers\x18\t \x03(\tR\bTriggers\x12 \n" +
	"\vPersistence\x18\n" +
	" \x01(\tR\vPersistence\x12&\n" +
	"\x0eHasRowSecurity\x18\v \x01(\bR\x0eHasRowSecurity\x12,\n" +
	"\x11RowSecurityForced\x18\f \x01(\bR\x11RowSecurityForced\x12\x18\n" +
	"\aComment\x18\r \x01(\tR\aComment\x12$\n" +
	"\rEstimatedRows\x18\x0e \x01(\x03R\rEstimatedRows\x12\x1e\n" +
	"\n" +
	"TotalBytes\x18\x0f \x01(\x03R\n" +
	"TotalBytes\"\xd5\x01\n" +
	"\x06PGView\x12'\n" +
	"\x04Name\x18\x01 \x01(\v2\x13.sqlmeta.ObjectNameR\x04Name\x12\x14\n" +
	"\x05Owner\x18\x03 \x01(\tR\x05Owner\x12\x1e\n" +
	"\n" +
	"Definition\x18\x04 \x01(\tR\n" +
	"Definition\x12&\n" +
	"\x0eIsMaterialized\x18\x05 \x01(\bR\x0eIsMaterialized\x12*\n" +
	"\aColumns\x18\x06 \x03(\v2\x10.pgmeta.PGColumnR\aColumns\x12\x18\n" +
	"\aComment\x18\a \x01(\tR\aComment\"\xff\x01\n" +
	"\bPGSchema\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Owner\x18\x02 \x01(\tR\x05Owner\x12'\n" +
	"\x06Tables\x18\x03 \x03(\v2\x0f.pgmeta.PGTableR\x06Tables\x12$\n" +
	"\x05Views\x18\x04 \x03(\v2\x0e.pgmeta.PGViewR\x05Views\x120\n" +
	"\tSequences\x18\x05 \x03(\v2\x12.pgmeta.PGSequenceR\tSequences\x12.\n" +
	"\aDomains\x18\x06 \x03(\v2\x14.pgmeta.PGConstraintR\aDomains\x12\x18\n" +
	"\aComment\x18\a \x01(\tR\aComment\"\xa0\x01\n" +
	"\n" +
	"PGDatabase\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x18\n" +
	"\aVersion\x18\x02 \x01(\tR\aVersion\x12*\n" +
	"\aSchemas\x18\x03 \x03(\v2\x10.pgmeta.PGSchemaR\aSchemas\x12\x1e\n" +
	"\n" +
	"Extensions\x18\x04 \x03(\tR\n" +
	"Extensions\x12\x18\n" +
	"\aComment\x18\x05 \x01(\tR\aCommentB\"Z github.com/genelet/sqlmeta/xmetab\x06proto3"

var (
	file_pg_meta_proto_rawDescOnce sync.Once
	file_pg_meta_proto_rawDescData []byte
)

func file_pg_meta_proto_rawDescGZIP() []byte {
	file_pg_meta_proto_rawDescOnce.Do(func() {
		file_pg_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pg_meta_proto_rawDesc), len(file_pg_meta_proto_rawDesc)))
	})
	return file_pg_meta_proto_rawDescData
}

var file_pg_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pg_meta_proto_goTypes = []any{
	(*PGColumn)(nil),     // 0: pgmeta.PGColumn
	(*PGIndex)(nil),      // 1: pgmeta.PGIndex
	(*PGForeignKey)(nil), // 2: pgmeta.PGForeignKey
	(*PGConstraint)(nil), // 3: pgmeta.PGConstraint
	(*PGSequence)(nil),   // 4: pgmeta.PGSequence
	(*PGTable)(nil),      // 5: pgmeta.PGTable
	(*PGView)(nil),       // 6: pgmeta.PGView
	(*PGSchema)(nil),     // 7: pgmeta.PGSchema
	(*PGDatabase)(nil),   // 8: pgmeta.PGDatabase
	(*DataType)(nil),     // 9: sqlmeta.DataType
	(*ObjectName)(nil),   // 10: sqlmeta.ObjectName
}
var file_pg_meta_proto_depIdxs = []int32{
	9,  // 0: pgmeta.PGColumn.DataType:type_name -> sqlmeta.DataType
	10, // 1: pgmeta.PGIndex.TableName:type_name -> sqlmeta.ObjectName
	10, // 2: pgmeta.PGForeignKey.TableName:type_name -> sqlmeta.ObjectName
	10, // 3: pgmeta.PGForeignKey.ForeignTable:type_name -> sqlmeta.ObjectName
	10, // 4: pgmeta.PGConstraint.TableName:type_name -> sqlmeta.ObjectName
	10, // 5: pgmeta.PGSequence.Name:type_name -> sqlmeta.ObjectName
	9,  // 6: pgmeta.PGSequence.DataType:type_name -> sqlmeta.DataType
	10, // 7: pgmeta.PGSequence.OwnerTable:type_name -> sqlmeta.ObjectName
	10, // 8: pgmeta.PGTable.Name:type_name -> sqlmeta.ObjectName
	0,  // 9: pgmeta.PGTable.Columns:type_name -> pgmeta.PGColumn
	1,  // 10: pgmeta.PGTable.Indexes:type_name -> pgmeta.PGIndex
	3,  // 11: pgmeta.PGTable.Constraints:type_name -> pgmeta.PGConstraint
	2,  // 12: pgmeta.PGTable.ForeignKeys:type_name -> pgmeta.PGForeignKey
	10, // 13: pgmeta.PGView.Name:type_name -> sqlmeta.ObjectName
	0,  // 14: pgmeta.PGView.Columns:type_name -> pgmeta.PGColumn
	5,  // 15: pgmeta.PGSchema.Tables:type_name -> pgmeta.PGTable
	6,  // 16: pgmeta.PGSchema.Views:type_name -> pgmeta.PGView
	4,  // 17: pgmeta.PGSchema.Sequences:type_name -> pgmeta.PGSequence
	3,  // 18: pgmeta.PGSchema.Domains:type_name -> pgmeta.PGConstraint
	7,  // 19: pgmeta.PGDatabase.Schemas:type_name -> pgmeta.PGSchema
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_pg_meta_proto_init() }
func file_pg_meta_proto_init() {
	if File_pg_meta_proto != nil {
		return
	}
	file_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pg_meta_proto_rawDesc), len(file_pg_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pg_meta_proto_goTypes,
		DependencyIndexes: file_pg_meta_proto_depIdxs,
		MessageInfos:      file_pg_meta_proto_msgTypes,
	}.Build()
	File_pg_meta_proto = out.File
	file_pg_meta_proto_goTypes = nil
	file_pg_meta_proto_depIdxs = nil
}
