// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/sqlite_meta.proto

package xmeta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a column in SQLite
type SQLiteColumn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	DataType      *DataType              `protobuf:"bytes,2,opt,name=DataType,proto3" json:"DataType,omitempty"` // SQLite types are affinity-based (INT, TEXT, BLOB, REAL, NUMERIC)
	IsNullable    bool                   `protobuf:"varint,3,opt,name=IsNullable,proto3" json:"IsNullable,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,4,opt,name=DefaultValue,proto3" json:"DefaultValue,omitempty"`
	IsPrimaryKey  bool                   `protobuf:"varint,5,opt,name=IsPrimaryKey,proto3" json:"IsPrimaryKey,omitempty"`
	AutoIncrement bool                   `protobuf:"varint,6,opt,name=AutoIncrement,proto3" json:"AutoIncrement,omitempty"`
	Collation     string                 `protobuf:"bytes,7,opt,name=Collation,proto3" json:"Collation,omitempty"` // BINARY, NOCASE, RTRIM
	Comment       string                 `protobuf:"bytes,8,opt,name=Comment,proto3" json:"Comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLiteColumn) Reset() {
	*x = SQLiteColumn{}
	mi := &file_proto_sqlite_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLiteColumn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLiteColumn) ProtoMessage() {}

func (x *SQLiteColumn) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlite_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLiteColumn.ProtoReflect.Descriptor instead.
func (*SQLiteColumn) Descriptor() ([]byte, []int) {
	return file_proto_sqlite_meta_proto_rawDescGZIP(), []int{0}
}

func (x *SQLiteColumn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SQLiteColumn) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *SQLiteColumn) GetIsNullable() bool {
	if x != nil {
		return x.IsNullable
	}
	return false
}

func (x *SQLiteColumn) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *SQLiteColumn) GetIsPrimaryKey() bool {
	if x != nil {
		return x.IsPrimaryKey
	}
	return false
}

func (x *SQLiteColumn) GetAutoIncrement() bool {
	if x != nil {
		return x.AutoIncrement
	}
	return false
}

func (x *SQLiteColumn) GetCollation() string {
	if x != nil {
		return x.Collation
	}
	return ""
}

func (x *SQLiteColumn) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

// Represents an index in SQLite
type SQLiteIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	TableName     string                 `protobuf:"bytes,2,opt,name=TableName,proto3" json:"TableName,omitempty"`
	IsUnique      bool                   `protobuf:"varint,3,opt,name=IsUnique,proto3" json:"IsUnique,omitempty"`
	Columns       []string               `protobuf:"bytes,4,rep,name=Columns,proto3" json:"Columns,omitempty"`
	PartialWhere  string                 `protobuf:"bytes,5,opt,name=PartialWhere,proto3" json:"PartialWhere,omitempty"` // Support for Partial Indexes (WHERE expression)
	Origin        string                 `protobuf:"bytes,6,opt,name=Origin,proto3" json:"Origin,omitempty"`             // "c" (create index), "u" (unique constraint), "pk" (primary key)
	Definition    string                 `protobuf:"bytes,7,opt,name=Definition,proto3" json:"Definition,omitempty"`     // SQL definition
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLiteIndex) Reset() {
	*x = SQLiteIndex{}
	mi := &file_proto_sqlite_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLiteIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLiteIndex) ProtoMessage() {}

func (x *SQLiteIndex) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlite_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLiteIndex.ProtoReflect.Descriptor instead.
func (*SQLiteIndex) Descriptor() ([]byte, []int) {
	return file_proto_sqlite_meta_proto_rawDescGZIP(), []int{1}
}

func (x *SQLiteIndex) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SQLiteIndex) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *SQLiteIndex) GetIsUnique() bool {
	if x != nil {
		return x.IsUnique
	}
	return false
}

func (x *SQLiteIndex) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *SQLiteIndex) GetPartialWhere() string {
	if x != nil {
		return x.PartialWhere
	}
	return ""
}

func (x *SQLiteIndex) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *SQLiteIndex) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

// Represents a Table in SQLite
type SQLiteTable struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type    string                 `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"` // "table", "view", "shadow", "virtual"
	Columns []*SQLiteColumn        `protobuf:"bytes,3,rep,name=Columns,proto3" json:"Columns,omitempty"`
	Indexes []*SQLiteIndex         `protobuf:"bytes,4,rep,name=Indexes,proto3" json:"Indexes,omitempty"`
	// SQLite Specific Options
	WithoutRowId  bool   `protobuf:"varint,5,opt,name=WithoutRowId,proto3" json:"WithoutRowId,omitempty"` // WITHOUT ROWID optimization
	Strict        bool   `protobuf:"varint,6,opt,name=Strict,proto3" json:"Strict,omitempty"`             // STRICT tables (SQLite 3.37+)
	Definition    string `protobuf:"bytes,7,opt,name=Definition,proto3" json:"Definition,omitempty"`      // Original CREATE statement
	RootPage      int64  `protobuf:"varint,8,opt,name=RootPage,proto3" json:"RootPage,omitempty"`         // Root page number in DB file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLiteTable) Reset() {
	*x = SQLiteTable{}
	mi := &file_proto_sqlite_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLiteTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLiteTable) ProtoMessage() {}

func (x *SQLiteTable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlite_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLiteTable.ProtoReflect.Descriptor instead.
func (*SQLiteTable) Descriptor() ([]byte, []int) {
	return file_proto_sqlite_meta_proto_rawDescGZIP(), []int{2}
}

func (x *SQLiteTable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SQLiteTable) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SQLiteTable) GetColumns() []*SQLiteColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *SQLiteTable) GetIndexes() []*SQLiteIndex {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *SQLiteTable) GetWithoutRowId() bool {
	if x != nil {
		return x.WithoutRowId
	}
	return false
}

func (x *SQLiteTable) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

func (x *SQLiteTable) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *SQLiteTable) GetRootPage() int64 {
	if x != nil {
		return x.RootPage
	}
	return 0
}

// Represents a View
type SQLiteView struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Definition    string                 `protobuf:"bytes,2,opt,name=Definition,proto3" json:"Definition,omitempty"`
	Columns       []*SQLiteColumn        `protobuf:"bytes,3,rep,name=Columns,proto3" json:"Columns,omitempty"` // Inferred columns
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLiteView) Reset() {
	*x = SQLiteView{}
	mi := &file_proto_sqlite_meta_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLiteView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLiteView) ProtoMessage() {}

func (x *SQLiteView) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlite_meta_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLiteView.ProtoReflect.Descriptor instead.
func (*SQLiteView) Descriptor() ([]byte, []int) {
	return file_proto_sqlite_meta_proto_rawDescGZIP(), []int{3}
}

func (x *SQLiteView) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SQLiteView) GetDefinition() string {
	if x != nil {
		return x.Definition
	}
	return ""
}

func (x *SQLiteView) GetColumns() []*SQLiteColumn {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Represents a Database File (or Attached DB)
type SQLiteDatabase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"` // "main", "temp", or attached name
	FilePath      string                 `protobuf:"bytes,2,opt,name=FilePath,proto3" json:"FilePath,omitempty"`
	Tables        []*SQLiteTable         `protobuf:"bytes,3,rep,name=Tables,proto3" json:"Tables,omitempty"`
	Views         []*SQLiteView          `protobuf:"bytes,4,rep,name=Views,proto3" json:"Views,omitempty"`
	Triggers      []string               `protobuf:"bytes,5,rep,name=Triggers,proto3" json:"Triggers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SQLiteDatabase) Reset() {
	*x = SQLiteDatabase{}
	mi := &file_proto_sqlite_meta_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SQLiteDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SQLiteDatabase) ProtoMessage() {}

func (x *SQLiteDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sqlite_meta_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SQLiteDatabase.ProtoReflect.Descriptor instead.
func (*SQLiteDatabase) Descriptor() ([]byte, []int) {
	return file_proto_sqlite_meta_proto_rawDescGZIP(), []int{4}
}

func (x *SQLiteDatabase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SQLiteDatabase) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *SQLiteDatabase) GetTables() []*SQLiteTable {
	if x != nil {
		return x.Tables
	}
	return nil
}

func (x *SQLiteDatabase) GetViews() []*SQLiteView {
	if x != nil {
		return x.Views
	}
	return nil
}

func (x *SQLiteDatabase) GetTriggers() []string {
	if x != nil {
		return x.Triggers
	}
	return nil
}

var File_proto_sqlite_meta_proto protoreflect.FileDescriptor

const file_proto_sqlite_meta_proto_rawDesc = "" +
	"\n" +
	"\x17proto/sqlite_meta.proto\x12\n" +
	"sqlitemeta\x1a\x11proto/types.proto\"\x97\x02\n" +
	"\fSQLiteColumn\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12-\n" +
	"\bDataType\x18\x02 \x01(\v2\x11.sqlmeta.DataTypeR\bDataType\x12\x1e\n" +
	"\n" +
	"IsNullable\x18\x03 \x01(\bR\n" +
	"IsNullable\x12\"\n" +
	"\fDefaultValue\x18\x04 \x01(\tR\fDefaultValue\x12\"\n" +
	"\fIsPrimaryKey\x18\x05 \x01(\bR\fIsPrimaryKey\x12$\n" +
	"\rAutoIncrement\x18\x06 \x01(\bR\rAutoIncrement\x12\x1c\n" +
	"\tCollation\x18\a \x01(\tR\tCollation\x12\x18\n" +
	"\aComment\x18\b \x01(\tR\aComment\"\xd1\x01\n" +
	"\vSQLiteIndex\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1c\n" +
	"\tTableName\x18\x02 \x01(\tR\tTableName\x12\x1a\n" +
	"\bIsUnique\x18\x03 \x01(\bR\bIsUnique\x12\x18\n" +
	"\aColumns\x18\x04 \x03(\tR\aColumns\x12\"\n" +
	"\fPartialWhere\x18\x05 \x01(\tR\fPartialWhere\x12\x16\n" +
	"\x06Origin\x18\x06 \x01(\tR\x06Origin\x12\x1e\n" +
	"\n" +
	"Definition\x18\a \x01(\tR\n" +
	"Definition\"\x94\x02\n" +
	"\vSQLiteTable\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\tR\x04Type\x122\n" +
	"\aColumns\x18\x03 \x03(\v2\x18.sqlitemeta.SQLiteColumnR\aColumns\x121\n" +
	"\aIndexes\x18\x04 \x03(\v2\x17.sqlitemeta.SQLiteIndexR\aIndexes\x12\"\n" +
	"\fWithoutRowId\x18\x05 \x01(\bR\fWithoutRowId\x12\x16\n" +
	"\x06Strict\x18\x06 \x01(\bR\x06Strict\x12\x1e\n" +
	"\n" +
	"Definition\x18\a \x01(\tR\n" +
	"Definition\x12\x1a\n" +
	"\bRootPage\x18\b \x01(\x03R\bRootPage\"t\n" +
	"\n" +
	"SQLiteView\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"Definition\x18\x02 \x01(\tR\n" +
	"Definition\x122\n" +
	"\aColumns\x18\x03 \x03(\v2\x18.sqlitemeta.SQLiteColumnR\aColumns\"\xbb\x01\n" +
	"\x0eSQLiteDatabase\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1a\n" +
	"\bFilePath\x18\x02 \x01(\tR\bFilePath\x12/\n" +
	"\x06Tables\x18\x03 \x03(\v2\x17.sqlitemeta.SQLiteTableR\x06Tables\x12,\n" +
	"\x05Views\x18\x04 \x03(\v2\x16.sqlitemeta.SQLiteViewR\x05Views\x12\x1a\n" +
	"\bTriggers\x18\x05 \x03(\tR\bTriggersB\"Z github.com/genelet/sqlmeta/xmetab\x06proto3"

var (
	file_proto_sqlite_meta_proto_rawDescOnce sync.Once
	file_proto_sqlite_meta_proto_rawDescData []byte
)

func file_proto_sqlite_meta_proto_rawDescGZIP() []byte {
	file_proto_sqlite_meta_proto_rawDescOnce.Do(func() {
		file_proto_sqlite_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sqlite_meta_proto_rawDesc), len(file_proto_sqlite_meta_proto_rawDesc)))
	})
	return file_proto_sqlite_meta_proto_rawDescData
}

var file_proto_sqlite_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_sqlite_meta_proto_goTypes = []any{
	(*SQLiteColumn)(nil),   // 0: sqlitemeta.SQLiteColumn
	(*SQLiteIndex)(nil),    // 1: sqlitemeta.SQLiteIndex
	(*SQLiteTable)(nil),    // 2: sqlitemeta.SQLiteTable
	(*SQLiteView)(nil),     // 3: sqlitemeta.SQLiteView
	(*SQLiteDatabase)(nil), // 4: sqlitemeta.SQLiteDatabase
	(*DataType)(nil),       // 5: sqlmeta.DataType
}
var file_proto_sqlite_meta_proto_depIdxs = []int32{
	5, // 0: sqlitemeta.SQLiteColumn.DataType:type_name -> sqlmeta.DataType
	0, // 1: sqlitemeta.SQLiteTable.Columns:type_name -> sqlitemeta.SQLiteColumn
	1, // 2: sqlitemeta.SQLiteTable.Indexes:type_name -> sqlitemeta.SQLiteIndex
	0, // 3: sqlitemeta.SQLiteView.Columns:type_name -> sqlitemeta.SQLiteColumn
	2, // 4: sqlitemeta.SQLiteDatabase.Tables:type_name -> sqlitemeta.SQLiteTable
	3, // 5: sqlitemeta.SQLiteDatabase.Views:type_name -> sqlitemeta.SQLiteView
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_sqlite_meta_proto_init() }
func file_proto_sqlite_meta_proto_init() {
	if File_proto_sqlite_meta_proto != nil {
		return
	}
	file_proto_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sqlite_meta_proto_rawDesc), len(file_proto_sqlite_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sqlite_meta_proto_goTypes,
		DependencyIndexes: file_proto_sqlite_meta_proto_depIdxs,
		MessageInfos:      file_proto_sqlite_meta_proto_msgTypes,
	}.Build()
	File_proto_sqlite_meta_proto = out.File
	file_proto_sqlite_meta_proto_goTypes = nil
	file_proto_sqlite_meta_proto_depIdxs = nil
}
