// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: proto/types.proto

package xmeta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataTypeSingle int32

const (
	DataTypeSingle_DataTypeSingleUnknown DataTypeSingle = 0
	DataTypeSingle_Double                DataTypeSingle = 1
	DataTypeSingle_Boolean               DataTypeSingle = 2
	DataTypeSingle_Time                  DataTypeSingle = 3
	DataTypeSingle_Date                  DataTypeSingle = 4
	DataTypeSingle_Bytea                 DataTypeSingle = 5
	DataTypeSingle_Text                  DataTypeSingle = 6
	DataTypeSingle_Regclass              DataTypeSingle = 7
	DataTypeSingle_UUID                  DataTypeSingle = 8
)

// Enum value maps for DataTypeSingle.
var (
	DataTypeSingle_name = map[int32]string{
		0: "DataTypeSingleUnknown",
		1: "Double",
		2: "Boolean",
		3: "Time",
		4: "Date",
		5: "Bytea",
		6: "Text",
		7: "Regclass",
		8: "UUID",
	}
	DataTypeSingle_value = map[string]int32{
		"DataTypeSingleUnknown": 0,
		"Double":                1,
		"Boolean":               2,
		"Time":                  3,
		"Date":                  4,
		"Bytea":                 5,
		"Text":                  6,
		"Regclass":              7,
		"UUID":                  8,
	}
)

func (x DataTypeSingle) Enum() *DataTypeSingle {
	p := new(DataTypeSingle)
	*p = x
	return p
}

func (x DataTypeSingle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataTypeSingle) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[0].Descriptor()
}

func (DataTypeSingle) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[0]
}

func (x DataTypeSingle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataTypeSingle.Descriptor instead.
func (DataTypeSingle) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{0}
}

type ObjectName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idents []string `protobuf:"bytes,1,rep,name=Idents,proto3" json:"Idents,omitempty"`
}

func (x *ObjectName) Reset() {
	*x = ObjectName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectName) ProtoMessage() {}

func (x *ObjectName) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectName.ProtoReflect.Descriptor instead.
func (*ObjectName) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectName) GetIdents() []string {
	if x != nil {
		return x.Idents
	}
	return nil
}

type BigInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsUnsigned bool `protobuf:"varint,1,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
}

func (x *BigInt) Reset() {
	*x = BigInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BigInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigInt) ProtoMessage() {}

func (x *BigInt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigInt.ProtoReflect.Descriptor instead.
func (*BigInt) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{1}
}

func (x *BigInt) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

type SmallInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsUnsigned bool `protobuf:"varint,1,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
}

func (x *SmallInt) Reset() {
	*x = SmallInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmallInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmallInt) ProtoMessage() {}

func (x *SmallInt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmallInt.ProtoReflect.Descriptor instead.
func (*SmallInt) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{2}
}

func (x *SmallInt) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

type Int struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsUnsigned bool `protobuf:"varint,1,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
}

func (x *Int) Reset() {
	*x = Int{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int) ProtoMessage() {}

func (x *Int) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int.ProtoReflect.Descriptor instead.
func (*Int) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{3}
}

func (x *Int) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

type Real struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsUnsigned bool `protobuf:"varint,1,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
}

func (x *Real) Reset() {
	*x = Real{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Real) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Real) ProtoMessage() {}

func (x *Real) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Real.ProtoReflect.Descriptor instead.
func (*Real) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{4}
}

func (x *Real) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

type Float struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size       uint32 `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	IsUnsigned bool   `protobuf:"varint,2,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
}

func (x *Float) Reset() {
	*x = Float{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Float) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float) ProtoMessage() {}

func (x *Float) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float.ProtoReflect.Descriptor instead.
func (*Float) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{5}
}

func (x *Float) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Float) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

type Decimal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Precision  uint32 `protobuf:"varint,1,opt,name=Precision,proto3" json:"Precision,omitempty"`
	Scale      uint32 `protobuf:"varint,2,opt,name=Scale,proto3" json:"Scale,omitempty"`
	IsUnsigned bool   `protobuf:"varint,3,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{6}
}

func (x *Decimal) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *Decimal) GetScale() uint32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *Decimal) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

type CharType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size uint32 `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *CharType) Reset() {
	*x = CharType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CharType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharType) ProtoMessage() {}

func (x *CharType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharType.ProtoReflect.Descriptor instead.
func (*CharType) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{7}
}

func (x *CharType) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type VarcharType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size uint32 `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
}

func (x *VarcharType) Reset() {
	*x = VarcharType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VarcharType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarcharType) ProtoMessage() {}

func (x *VarcharType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarcharType.ProtoReflect.Descriptor instead.
func (*VarcharType) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{8}
}

func (x *VarcharType) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Timestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WithTimeZone bool `protobuf:"varint,1,opt,name=WithTimeZone,proto3" json:"WithTimeZone,omitempty"`
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{9}
}

func (x *Timestamp) GetWithTimeZone() bool {
	if x != nil {
		return x.WithTimeZone
	}
	return false
}

type BitType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size    uint32 `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	Varying bool   `protobuf:"varint,2,opt,name=Varying,proto3" json:"Varying,omitempty"`
}

func (x *BitType) Reset() {
	*x = BitType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BitType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitType) ProtoMessage() {}

func (x *BitType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitType.ProtoReflect.Descriptor instead.
func (*BitType) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{10}
}

func (x *BitType) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BitType) GetVarying() bool {
	if x != nil {
		return x.Varying
	}
	return false
}

type DoubleType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsDoublePrecision bool `protobuf:"varint,1,opt,name=is_double_precision,json=isDoublePrecision,proto3" json:"is_double_precision,omitempty"`
}

func (x *DoubleType) Reset() {
	*x = DoubleType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoubleType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleType) ProtoMessage() {}

func (x *DoubleType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleType.ProtoReflect.Descriptor instead.
func (*DoubleType) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{11}
}

func (x *DoubleType) GetIsDoublePrecision() bool {
	if x != nil {
		return x.IsDoublePrecision
	}
	return false
}

type CollateType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type          *DataType `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	CollationName string    `protobuf:"bytes,2,opt,name=CollationName,proto3" json:"CollationName,omitempty"`
}

func (x *CollateType) Reset() {
	*x = CollateType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollateType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollateType) ProtoMessage() {}

func (x *CollateType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollateType.ProtoReflect.Descriptor instead.
func (*CollateType) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{12}
}

func (x *CollateType) GetType() *DataType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *CollateType) GetCollationName() string {
	if x != nil {
		return x.CollationName
	}
	return ""
}

type MetaColumnDef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	DataType *DataType `protobuf:"bytes,2,opt,name=DataType,proto3" json:"DataType,omitempty"`
}

func (x *MetaColumnDef) Reset() {
	*x = MetaColumnDef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetaColumnDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaColumnDef) ProtoMessage() {}

func (x *MetaColumnDef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaColumnDef.ProtoReflect.Descriptor instead.
func (*MetaColumnDef) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{13}
}

func (x *MetaColumnDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetaColumnDef) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

type StructData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fields []*MetaColumnDef `protobuf:"bytes,1,rep,name=Fields,proto3" json:"Fields,omitempty"`
}

func (x *StructData) Reset() {
	*x = StructData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StructData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructData) ProtoMessage() {}

func (x *StructData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructData.ProtoReflect.Descriptor instead.
func (*StructData) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{14}
}

func (x *StructData) GetFields() []*MetaColumnDef {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ArrayData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *DataType `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *ArrayData) Reset() {
	*x = ArrayData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayData) ProtoMessage() {}

func (x *ArrayData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayData.ProtoReflect.Descriptor instead.
func (*ArrayData) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{15}
}

func (x *ArrayData) GetType() *DataType {
	if x != nil {
		return x.Type
	}
	return nil
}

type DataType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to TypeClause:
	//
	//	*DataType_IntData
	//	*DataType_SmallIntData
	//	*DataType_BigIntData
	//	*DataType_DecimalData
	//	*DataType_CharData
	//	*DataType_VarcharData
	//	*DataType_CustomData
	//	*DataType_ArrayData
	//	*DataType_StructData
	//	*DataType_UUIDData
	//	*DataType_TimestampData
	//	*DataType_BooleanData
	//	*DataType_DateData
	//	*DataType_TimeData
	//	*DataType_DoubleData
	//	*DataType_FloatData
	//	*DataType_RealData
	//	*DataType_TextData
	//	*DataType_BitData
	//	*DataType_RegclassData
	//	*DataType_ByteaData
	//	*DataType_CollateData
	TypeClause isDataType_TypeClause `protobuf_oneof:"TypeClause"`
}

func (x *DataType) Reset() {
	*x = DataType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_types_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType) ProtoMessage() {}

func (x *DataType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType.ProtoReflect.Descriptor instead.
func (*DataType) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{16}
}

func (m *DataType) GetTypeClause() isDataType_TypeClause {
	if m != nil {
		return m.TypeClause
	}
	return nil
}

func (x *DataType) GetIntData() *Int {
	if x, ok := x.GetTypeClause().(*DataType_IntData); ok {
		return x.IntData
	}
	return nil
}

func (x *DataType) GetSmallIntData() *SmallInt {
	if x, ok := x.GetTypeClause().(*DataType_SmallIntData); ok {
		return x.SmallIntData
	}
	return nil
}

func (x *DataType) GetBigIntData() *BigInt {
	if x, ok := x.GetTypeClause().(*DataType_BigIntData); ok {
		return x.BigIntData
	}
	return nil
}

func (x *DataType) GetDecimalData() *Decimal {
	if x, ok := x.GetTypeClause().(*DataType_DecimalData); ok {
		return x.DecimalData
	}
	return nil
}

func (x *DataType) GetCharData() *CharType {
	if x, ok := x.GetTypeClause().(*DataType_CharData); ok {
		return x.CharData
	}
	return nil
}

func (x *DataType) GetVarcharData() *VarcharType {
	if x, ok := x.GetTypeClause().(*DataType_VarcharData); ok {
		return x.VarcharData
	}
	return nil
}

func (x *DataType) GetCustomData() *ObjectName {
	if x, ok := x.GetTypeClause().(*DataType_CustomData); ok {
		return x.CustomData
	}
	return nil
}

func (x *DataType) GetArrayData() *ArrayData {
	if x, ok := x.GetTypeClause().(*DataType_ArrayData); ok {
		return x.ArrayData
	}
	return nil
}

func (x *DataType) GetStructData() *StructData {
	if x, ok := x.GetTypeClause().(*DataType_StructData); ok {
		return x.StructData
	}
	return nil
}

func (x *DataType) GetUUIDData() DataTypeSingle {
	if x, ok := x.GetTypeClause().(*DataType_UUIDData); ok {
		return x.UUIDData
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

func (x *DataType) GetTimestampData() *Timestamp {
	if x, ok := x.GetTypeClause().(*DataType_TimestampData); ok {
		return x.TimestampData
	}
	return nil
}

func (x *DataType) GetBooleanData() DataTypeSingle {
	if x, ok := x.GetTypeClause().(*DataType_BooleanData); ok {
		return x.BooleanData
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

func (x *DataType) GetDateData() DataTypeSingle {
	if x, ok := x.GetTypeClause().(*DataType_DateData); ok {
		return x.DateData
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

func (x *DataType) GetTimeData() DataTypeSingle {
	if x, ok := x.GetTypeClause().(*DataType_TimeData); ok {
		return x.TimeData
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

func (x *DataType) GetDoubleData() *DoubleType {
	if x, ok := x.GetTypeClause().(*DataType_DoubleData); ok {
		return x.DoubleData
	}
	return nil
}

func (x *DataType) GetFloatData() *Float {
	if x, ok := x.GetTypeClause().(*DataType_FloatData); ok {
		return x.FloatData
	}
	return nil
}

func (x *DataType) GetRealData() *Real {
	if x, ok := x.GetTypeClause().(*DataType_RealData); ok {
		return x.RealData
	}
	return nil
}

func (x *DataType) GetTextData() DataTypeSingle {
	if x, ok := x.GetTypeClause().(*DataType_TextData); ok {
		return x.TextData
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

func (x *DataType) GetBitData() *BitType {
	if x, ok := x.GetTypeClause().(*DataType_BitData); ok {
		return x.BitData
	}
	return nil
}

func (x *DataType) GetRegclassData() DataTypeSingle {
	if x, ok := x.GetTypeClause().(*DataType_RegclassData); ok {
		return x.RegclassData
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

func (x *DataType) GetByteaData() DataTypeSingle {
	if x, ok := x.GetTypeClause().(*DataType_ByteaData); ok {
		return x.ByteaData
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

func (x *DataType) GetCollateData() *CollateType {
	if x, ok := x.GetTypeClause().(*DataType_CollateData); ok {
		return x.CollateData
	}
	return nil
}

type isDataType_TypeClause interface {
	isDataType_TypeClause()
}

type DataType_IntData struct {
	IntData *Int `protobuf:"bytes,1,opt,name=IntData,proto3,oneof"`
}

type DataType_SmallIntData struct {
	SmallIntData *SmallInt `protobuf:"bytes,2,opt,name=SmallIntData,proto3,oneof"`
}

type DataType_BigIntData struct {
	BigIntData *BigInt `protobuf:"bytes,3,opt,name=BigIntData,proto3,oneof"`
}

type DataType_DecimalData struct {
	DecimalData *Decimal `protobuf:"bytes,4,opt,name=DecimalData,proto3,oneof"`
}

type DataType_CharData struct {
	CharData *CharType `protobuf:"bytes,8,opt,name=CharData,proto3,oneof"`
}

type DataType_VarcharData struct {
	VarcharData *VarcharType `protobuf:"bytes,9,opt,name=VarcharData,proto3,oneof"`
}

type DataType_CustomData struct {
	CustomData *ObjectName `protobuf:"bytes,10,opt,name=CustomData,proto3,oneof"`
}

type DataType_ArrayData struct {
	ArrayData *ArrayData `protobuf:"bytes,11,opt,name=ArrayData,proto3,oneof"`
}

type DataType_StructData struct {
	StructData *StructData `protobuf:"bytes,12,opt,name=StructData,proto3,oneof"`
}

type DataType_UUIDData struct {
	UUIDData DataTypeSingle `protobuf:"varint,14,opt,name=UUIDData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

type DataType_TimestampData struct {
	TimestampData *Timestamp `protobuf:"bytes,15,opt,name=TimestampData,proto3,oneof"`
}

type DataType_BooleanData struct {
	BooleanData DataTypeSingle `protobuf:"varint,13,opt,name=BooleanData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

type DataType_DateData struct {
	DateData DataTypeSingle `protobuf:"varint,16,opt,name=DateData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

type DataType_TimeData struct {
	TimeData DataTypeSingle `protobuf:"varint,17,opt,name=TimeData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

type DataType_DoubleData struct {
	DoubleData *DoubleType `protobuf:"bytes,18,opt,name=DoubleData,proto3,oneof"`
}

type DataType_FloatData struct {
	FloatData *Float `protobuf:"bytes,19,opt,name=FloatData,proto3,oneof"`
}

type DataType_RealData struct {
	RealData *Real `protobuf:"bytes,20,opt,name=RealData,proto3,oneof"`
}

type DataType_TextData struct {
	TextData DataTypeSingle `protobuf:"varint,21,opt,name=TextData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

type DataType_BitData struct {
	BitData *BitType `protobuf:"bytes,22,opt,name=BitData,proto3,oneof"`
}

type DataType_RegclassData struct {
	RegclassData DataTypeSingle `protobuf:"varint,23,opt,name=RegclassData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

type DataType_ByteaData struct {
	ByteaData DataTypeSingle `protobuf:"varint,24,opt,name=ByteaData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

type DataType_CollateData struct {
	CollateData *CollateType `protobuf:"bytes,25,opt,name=CollateData,proto3,oneof"`
}

func (*DataType_IntData) isDataType_TypeClause() {}

func (*DataType_SmallIntData) isDataType_TypeClause() {}

func (*DataType_BigIntData) isDataType_TypeClause() {}

func (*DataType_DecimalData) isDataType_TypeClause() {}

func (*DataType_CharData) isDataType_TypeClause() {}

func (*DataType_VarcharData) isDataType_TypeClause() {}

func (*DataType_CustomData) isDataType_TypeClause() {}

func (*DataType_ArrayData) isDataType_TypeClause() {}

func (*DataType_StructData) isDataType_TypeClause() {}

func (*DataType_UUIDData) isDataType_TypeClause() {}

func (*DataType_TimestampData) isDataType_TypeClause() {}

func (*DataType_BooleanData) isDataType_TypeClause() {}

func (*DataType_DateData) isDataType_TypeClause() {}

func (*DataType_TimeData) isDataType_TypeClause() {}

func (*DataType_DoubleData) isDataType_TypeClause() {}

func (*DataType_FloatData) isDataType_TypeClause() {}

func (*DataType_RealData) isDataType_TypeClause() {}

func (*DataType_TextData) isDataType_TypeClause() {}

func (*DataType_BitData) isDataType_TypeClause() {}

func (*DataType_RegclassData) isDataType_TypeClause() {}

func (*DataType_ByteaData) isDataType_TypeClause() {}

func (*DataType_CollateData) isDataType_TypeClause() {}

var File_proto_types_proto protoreflect.FileDescriptor

var file_proto_types_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x22, 0x24, 0x0a, 0x0a,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x73, 0x22, 0x28, 0x0a, 0x06, 0x42, 0x69, 0x67, 0x49, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a,
	0x49, 0x73, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0a, 0x49, 0x73, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x22, 0x2a, 0x0a, 0x08,
	0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x73, 0x55, 0x6e,
	0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x49, 0x73,
	0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x22, 0x25, 0x0a, 0x03, 0x49, 0x6e, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x49, 0x73, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x49, 0x73, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x22,
	0x26, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x73, 0x55, 0x6e, 0x73,
	0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x49, 0x73, 0x55,
	0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x22, 0x3b, 0x0a, 0x05, 0x46, 0x6c, 0x6f, 0x61, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x73, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x49, 0x73, 0x55, 0x6e, 0x73, 0x69,
	0x67, 0x6e, 0x65, 0x64, 0x22, 0x5d, 0x0a, 0x07, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x12,
	0x1c, 0x0a, 0x09, 0x50, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x50, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a,
	0x05, 0x53, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x53, 0x63,
	0x61, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x73, 0x55, 0x6e, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x49, 0x73, 0x55, 0x6e, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x22, 0x1e, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x21, 0x0a, 0x0b, 0x56, 0x61, 0x72, 0x63, 0x68, 0x61, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x2f, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x22, 0x0a, 0x0c, 0x57, 0x69, 0x74, 0x68, 0x54, 0x69, 0x6d, 0x65, 0x5a,
	0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x57, 0x69, 0x74, 0x68, 0x54,
	0x69, 0x6d, 0x65, 0x5a, 0x6f, 0x6e, 0x65, 0x22, 0x37, 0x0a, 0x07, 0x42, 0x69, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x61, 0x72, 0x79, 0x69, 0x6e,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x56, 0x61, 0x72, 0x79, 0x69, 0x6e, 0x67,
	0x22, 0x3c, 0x0a, 0x0a, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2e,
	0x0a, 0x13, 0x69, 0x73, 0x5f, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x5f, 0x70, 0x72, 0x65, 0x63,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x69, 0x73, 0x44,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x5a,
	0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x25, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x71,
	0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x43, 0x6f, 0x6c,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x52, 0x0a, 0x0d, 0x4d, 0x65,
	0x74, 0x61, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x44, 0x65, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x2d, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x22, 0x3c,
	0x0a, 0x0a, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x06,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73,
	0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
	0x6e, 0x44, 0x65, 0x66, 0x52, 0x06, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22, 0x32, 0x0a, 0x09,
	0x41, 0x72, 0x72, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12, 0x25, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74,
	0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65,
	0x22, 0xba, 0x09, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a,
	0x07, 0x49, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x49, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x07,
	0x49, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x0c, 0x53, 0x6d, 0x61, 0x6c, 0x6c,
	0x49, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x0c, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x31, 0x0a, 0x0a, 0x42, 0x69, 0x67, 0x49, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x42,
	0x69, 0x67, 0x49, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x42, 0x69, 0x67, 0x49, 0x6e, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x34, 0x0a, 0x0b, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x0b, 0x44, 0x65,
	0x63, 0x69, 0x6d, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2f, 0x0a, 0x08, 0x43, 0x68, 0x61,
	0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x71,
	0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00,
	0x52, 0x08, 0x43, 0x68, 0x61, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x0b, 0x56, 0x61,
	0x72, 0x63, 0x68, 0x61, 0x72, 0x44, 0x61, 0x74, 0x61, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x56, 0x61, 0x72, 0x63, 0x68, 0x61,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x56, 0x61, 0x72, 0x63, 0x68, 0x61, 0x72,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52,
	0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x32, 0x0a, 0x09, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x44, 0x61,
	0x74, 0x61, 0x48, 0x00, 0x52, 0x09, 0x41, 0x72, 0x72, 0x61, 0x79, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x35, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x53, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0a, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x08, 0x55, 0x55, 0x49, 0x44, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x48, 0x00, 0x52, 0x08, 0x55, 0x55, 0x49, 0x44, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3a, 0x0a,
	0x0d, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x48, 0x00, 0x52, 0x0d, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3b, 0x0a, 0x0b, 0x42, 0x6f, 0x6f,
	0x6c, 0x65, 0x61, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17,
	0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70,
	0x65, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x42, 0x6f, 0x6f, 0x6c, 0x65,
	0x61, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x53, 0x69, 0x6e, 0x67, 0x6c,
	0x65, 0x48, 0x00, 0x52, 0x08, 0x44, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a,
	0x08, 0x54, 0x69, 0x6d, 0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x08, 0x54, 0x69, 0x6d, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x0a, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65,
	0x74, 0x61, 0x2e, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52,
	0x0a, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x09, 0x46,
	0x6c, 0x6f, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x13, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x48, 0x00,
	0x52, 0x09, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x2b, 0x0a, 0x08, 0x52,
	0x65, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x18, 0x14, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x48, 0x00, 0x52, 0x08,
	0x52, 0x65, 0x61, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x35, 0x0a, 0x08, 0x54, 0x65, 0x78, 0x74,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x15, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x71, 0x6c,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x08, 0x54, 0x65, 0x78, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x2c, 0x0a, 0x07, 0x42, 0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x18, 0x16, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x42, 0x69, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x48, 0x00, 0x52, 0x07, 0x42, 0x69, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x3d, 0x0a,
	0x0c, 0x52, 0x65, 0x67, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61, 0x18, 0x17, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x0c,
	0x52, 0x65, 0x67, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x37, 0x0a, 0x09,
	0x42, 0x79, 0x74, 0x65, 0x61, 0x44, 0x61, 0x74, 0x61, 0x18, 0x18, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x17, 0x2e, 0x73, 0x71, 0x6c, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x48, 0x00, 0x52, 0x09, 0x42, 0x79, 0x74, 0x65,
	0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x0b, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x19, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x71, 0x6c,
	0x6d, 0x65, 0x74, 0x61, 0x2e, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x48, 0x00, 0x52, 0x0b, 0x43, 0x6f, 0x6c, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x42,
	0x0c, 0x0a, 0x0a, 0x54, 0x79, 0x70, 0x65, 0x43, 0x6c, 0x61, 0x75, 0x73, 0x65, 0x2a, 0x85, 0x01,
	0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65,
	0x12, 0x19, 0x0a, 0x15, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x53, 0x69, 0x6e, 0x67,
	0x6c, 0x65, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x44,
	0x6f, 0x75, 0x62, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x6f, 0x6f, 0x6c, 0x65,
	0x61, 0x6e, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x10, 0x03, 0x12, 0x08,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x79, 0x74, 0x65,
	0x61, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x10, 0x06, 0x12, 0x0c, 0x0a,
	0x08, 0x52, 0x65, 0x67, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x10, 0x07, 0x12, 0x08, 0x0a, 0x04, 0x55,
	0x55, 0x49, 0x44, 0x10, 0x08, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x6c, 0x65, 0x74, 0x2f, 0x73, 0x71, 0x6c, 0x6d,
	0x65, 0x74, 0x61, 0x2f, 0x78, 0x6d, 0x65, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_types_proto_rawDescOnce sync.Once
	file_proto_types_proto_rawDescData = file_proto_types_proto_rawDesc
)

func file_proto_types_proto_rawDescGZIP() []byte {
	file_proto_types_proto_rawDescOnce.Do(func() {
		file_proto_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_types_proto_rawDescData)
	})
	return file_proto_types_proto_rawDescData
}

var file_proto_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_types_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_types_proto_goTypes = []interface{}{
	(DataTypeSingle)(0),   // 0: sqlmeta.DataTypeSingle
	(*ObjectName)(nil),    // 1: sqlmeta.ObjectName
	(*BigInt)(nil),        // 2: sqlmeta.BigInt
	(*SmallInt)(nil),      // 3: sqlmeta.SmallInt
	(*Int)(nil),           // 4: sqlmeta.Int
	(*Real)(nil),          // 5: sqlmeta.Real
	(*Float)(nil),         // 6: sqlmeta.Float
	(*Decimal)(nil),       // 7: sqlmeta.Decimal
	(*CharType)(nil),      // 8: sqlmeta.CharType
	(*VarcharType)(nil),   // 9: sqlmeta.VarcharType
	(*Timestamp)(nil),     // 10: sqlmeta.Timestamp
	(*BitType)(nil),       // 11: sqlmeta.BitType
	(*DoubleType)(nil),    // 12: sqlmeta.DoubleType
	(*CollateType)(nil),   // 13: sqlmeta.CollateType
	(*MetaColumnDef)(nil), // 14: sqlmeta.MetaColumnDef
	(*StructData)(nil),    // 15: sqlmeta.StructData
	(*ArrayData)(nil),     // 16: sqlmeta.ArrayData
	(*DataType)(nil),      // 17: sqlmeta.DataType
}
var file_proto_types_proto_depIdxs = []int32{
	17, // 0: sqlmeta.CollateType.Type:type_name -> sqlmeta.DataType
	17, // 1: sqlmeta.MetaColumnDef.DataType:type_name -> sqlmeta.DataType
	14, // 2: sqlmeta.StructData.Fields:type_name -> sqlmeta.MetaColumnDef
	17, // 3: sqlmeta.ArrayData.Type:type_name -> sqlmeta.DataType
	4,  // 4: sqlmeta.DataType.IntData:type_name -> sqlmeta.Int
	3,  // 5: sqlmeta.DataType.SmallIntData:type_name -> sqlmeta.SmallInt
	2,  // 6: sqlmeta.DataType.BigIntData:type_name -> sqlmeta.BigInt
	7,  // 7: sqlmeta.DataType.DecimalData:type_name -> sqlmeta.Decimal
	8,  // 8: sqlmeta.DataType.CharData:type_name -> sqlmeta.CharType
	9,  // 9: sqlmeta.DataType.VarcharData:type_name -> sqlmeta.VarcharType
	1,  // 10: sqlmeta.DataType.CustomData:type_name -> sqlmeta.ObjectName
	16, // 11: sqlmeta.DataType.ArrayData:type_name -> sqlmeta.ArrayData
	15, // 12: sqlmeta.DataType.StructData:type_name -> sqlmeta.StructData
	0,  // 13: sqlmeta.DataType.UUIDData:type_name -> sqlmeta.DataTypeSingle
	10, // 14: sqlmeta.DataType.TimestampData:type_name -> sqlmeta.Timestamp
	0,  // 15: sqlmeta.DataType.BooleanData:type_name -> sqlmeta.DataTypeSingle
	0,  // 16: sqlmeta.DataType.DateData:type_name -> sqlmeta.DataTypeSingle
	0,  // 17: sqlmeta.DataType.TimeData:type_name -> sqlmeta.DataTypeSingle
	12, // 18: sqlmeta.DataType.DoubleData:type_name -> sqlmeta.DoubleType
	6,  // 19: sqlmeta.DataType.FloatData:type_name -> sqlmeta.Float
	5,  // 20: sqlmeta.DataType.RealData:type_name -> sqlmeta.Real
	0,  // 21: sqlmeta.DataType.TextData:type_name -> sqlmeta.DataTypeSingle
	11, // 22: sqlmeta.DataType.BitData:type_name -> sqlmeta.BitType
	0,  // 23: sqlmeta.DataType.RegclassData:type_name -> sqlmeta.DataTypeSingle
	0,  // 24: sqlmeta.DataType.ByteaData:type_name -> sqlmeta.DataTypeSingle
	13, // 25: sqlmeta.DataType.CollateData:type_name -> sqlmeta.CollateType
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_proto_types_proto_init() }
func file_proto_types_proto_init() {
	if File_proto_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BigInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmallInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Int); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Real); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Float); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Decimal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CharType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VarcharType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timestamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BitType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoubleType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollateType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetaColumnDef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StructData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrayData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_types_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_types_proto_msgTypes[16].OneofWrappers = []interface{}{
		(*DataType_IntData)(nil),
		(*DataType_SmallIntData)(nil),
		(*DataType_BigIntData)(nil),
		(*DataType_DecimalData)(nil),
		(*DataType_CharData)(nil),
		(*DataType_VarcharData)(nil),
		(*DataType_CustomData)(nil),
		(*DataType_ArrayData)(nil),
		(*DataType_StructData)(nil),
		(*DataType_UUIDData)(nil),
		(*DataType_TimestampData)(nil),
		(*DataType_BooleanData)(nil),
		(*DataType_DateData)(nil),
		(*DataType_TimeData)(nil),
		(*DataType_DoubleData)(nil),
		(*DataType_FloatData)(nil),
		(*DataType_RealData)(nil),
		(*DataType_TextData)(nil),
		(*DataType_BitData)(nil),
		(*DataType_RegclassData)(nil),
		(*DataType_ByteaData)(nil),
		(*DataType_CollateData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_types_proto_goTypes,
		DependencyIndexes: file_proto_types_proto_depIdxs,
		EnumInfos:         file_proto_types_proto_enumTypes,
		MessageInfos:      file_proto_types_proto_msgTypes,
	}.Build()
	File_proto_types_proto = out.File
	file_proto_types_proto_rawDesc = nil
	file_proto_types_proto_goTypes = nil
	file_proto_types_proto_depIdxs = nil
}
