// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/types.proto

package xmeta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataTypeSingle int32

const (
	DataTypeSingle_DataTypeSingleUnknown DataTypeSingle = 0
	DataTypeSingle_Double                DataTypeSingle = 1
	DataTypeSingle_Boolean               DataTypeSingle = 2
	DataTypeSingle_Time                  DataTypeSingle = 3
	DataTypeSingle_Date                  DataTypeSingle = 4
	DataTypeSingle_Bytea                 DataTypeSingle = 5
	DataTypeSingle_Text                  DataTypeSingle = 6
	DataTypeSingle_Regclass              DataTypeSingle = 7
	DataTypeSingle_UUID                  DataTypeSingle = 8
	DataTypeSingle_Year                  DataTypeSingle = 9
)

// Enum value maps for DataTypeSingle.
var (
	DataTypeSingle_name = map[int32]string{
		0: "DataTypeSingleUnknown",
		1: "Double",
		2: "Boolean",
		3: "Time",
		4: "Date",
		5: "Bytea",
		6: "Text",
		7: "Regclass",
		8: "UUID",
		9: "Year",
	}
	DataTypeSingle_value = map[string]int32{
		"DataTypeSingleUnknown": 0,
		"Double":                1,
		"Boolean":               2,
		"Time":                  3,
		"Date":                  4,
		"Bytea":                 5,
		"Text":                  6,
		"Regclass":              7,
		"UUID":                  8,
		"Year":                  9,
	}
)

func (x DataTypeSingle) Enum() *DataTypeSingle {
	p := new(DataTypeSingle)
	*p = x
	return p
}

func (x DataTypeSingle) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataTypeSingle) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[0].Descriptor()
}

func (DataTypeSingle) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[0]
}

func (x DataTypeSingle) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataTypeSingle.Descriptor instead.
func (DataTypeSingle) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{0}
}

// Foreign Key referential actions (shared across dialects)
type ReferentialAction int32

const (
	ReferentialAction_ReferentialAction_Unknown    ReferentialAction = 0
	ReferentialAction_ReferentialAction_NoAction   ReferentialAction = 1
	ReferentialAction_ReferentialAction_Restrict   ReferentialAction = 2
	ReferentialAction_ReferentialAction_Cascade    ReferentialAction = 3
	ReferentialAction_ReferentialAction_SetNull    ReferentialAction = 4
	ReferentialAction_ReferentialAction_SetDefault ReferentialAction = 5
)

// Enum value maps for ReferentialAction.
var (
	ReferentialAction_name = map[int32]string{
		0: "ReferentialAction_Unknown",
		1: "ReferentialAction_NoAction",
		2: "ReferentialAction_Restrict",
		3: "ReferentialAction_Cascade",
		4: "ReferentialAction_SetNull",
		5: "ReferentialAction_SetDefault",
	}
	ReferentialAction_value = map[string]int32{
		"ReferentialAction_Unknown":    0,
		"ReferentialAction_NoAction":   1,
		"ReferentialAction_Restrict":   2,
		"ReferentialAction_Cascade":    3,
		"ReferentialAction_SetNull":    4,
		"ReferentialAction_SetDefault": 5,
	}
)

func (x ReferentialAction) Enum() *ReferentialAction {
	p := new(ReferentialAction)
	*p = x
	return p
}

func (x ReferentialAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReferentialAction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[1].Descriptor()
}

func (ReferentialAction) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[1]
}

func (x ReferentialAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReferentialAction.Descriptor instead.
func (ReferentialAction) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{1}
}

// Foreign Key match options (shared across dialects)
type MatchOption int32

const (
	MatchOption_MatchOption_Unknown MatchOption = 0
	MatchOption_MatchOption_Simple  MatchOption = 1
	MatchOption_MatchOption_Partial MatchOption = 2
	MatchOption_MatchOption_Full    MatchOption = 3
)

// Enum value maps for MatchOption.
var (
	MatchOption_name = map[int32]string{
		0: "MatchOption_Unknown",
		1: "MatchOption_Simple",
		2: "MatchOption_Partial",
		3: "MatchOption_Full",
	}
	MatchOption_value = map[string]int32{
		"MatchOption_Unknown": 0,
		"MatchOption_Simple":  1,
		"MatchOption_Partial": 2,
		"MatchOption_Full":    3,
	}
)

func (x MatchOption) Enum() *MatchOption {
	p := new(MatchOption)
	*p = x
	return p
}

func (x MatchOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchOption) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[2].Descriptor()
}

func (MatchOption) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[2]
}

func (x MatchOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchOption.Descriptor instead.
func (MatchOption) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{2}
}

// Null value indicator (for SQL expression tracking)
type NullValue int32

const (
	NullValue_NullValueUnknown NullValue = 0
	NullValue_NullValueConfirm NullValue = 1
)

// Enum value maps for NullValue.
var (
	NullValue_name = map[int32]string{
		0: "NullValueUnknown",
		1: "NullValueConfirm",
	}
	NullValue_value = map[string]int32{
		"NullValueUnknown": 0,
		"NullValueConfirm": 1,
	}
)

func (x NullValue) Enum() *NullValue {
	p := new(NullValue)
	*p = x
	return p
}

func (x NullValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NullValue) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[3].Descriptor()
}

func (NullValue) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[3]
}

func (x NullValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NullValue.Descriptor instead.
func (NullValue) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{3}
}

// Auto-increment indicator (MySQL AUTO_INCREMENT, etc.)
type AutoIncrement int32

const (
	AutoIncrement_AutoIncrementUnknown AutoIncrement = 0
	AutoIncrement_AutoIncrementConfirm AutoIncrement = 1
)

// Enum value maps for AutoIncrement.
var (
	AutoIncrement_name = map[int32]string{
		0: "AutoIncrementUnknown",
		1: "AutoIncrementConfirm",
	}
	AutoIncrement_value = map[string]int32{
		"AutoIncrementUnknown": 0,
		"AutoIncrementConfirm": 1,
	}
)

func (x AutoIncrement) Enum() *AutoIncrement {
	p := new(AutoIncrement)
	*p = x
	return p
}

func (x AutoIncrement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AutoIncrement) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[4].Descriptor()
}

func (AutoIncrement) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[4]
}

func (x AutoIncrement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AutoIncrement.Descriptor instead.
func (AutoIncrement) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{4}
}

// NOT NULL constraint indicator
type NotNullColumnSpec int32

const (
	NotNullColumnSpec_NotNullColumnSpecUnknown NotNullColumnSpec = 0
	NotNullColumnSpec_NotNullColumnSpecConfirm NotNullColumnSpec = 1
)

// Enum value maps for NotNullColumnSpec.
var (
	NotNullColumnSpec_name = map[int32]string{
		0: "NotNullColumnSpecUnknown",
		1: "NotNullColumnSpecConfirm",
	}
	NotNullColumnSpec_value = map[string]int32{
		"NotNullColumnSpecUnknown": 0,
		"NotNullColumnSpecConfirm": 1,
	}
)

func (x NotNullColumnSpec) Enum() *NotNullColumnSpec {
	p := new(NotNullColumnSpec)
	*p = x
	return p
}

func (x NotNullColumnSpec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotNullColumnSpec) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_types_proto_enumTypes[5].Descriptor()
}

func (NotNullColumnSpec) Type() protoreflect.EnumType {
	return &file_proto_types_proto_enumTypes[5]
}

func (x NotNullColumnSpec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotNullColumnSpec.Descriptor instead.
func (NotNullColumnSpec) EnumDescriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{5}
}

type ObjectName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Idents        []string               `protobuf:"bytes,1,rep,name=Idents,proto3" json:"Idents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectName) Reset() {
	*x = ObjectName{}
	mi := &file_proto_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectName) ProtoMessage() {}

func (x *ObjectName) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectName.ProtoReflect.Descriptor instead.
func (*ObjectName) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectName) GetIdents() []string {
	if x != nil {
		return x.Idents
	}
	return nil
}

type BigInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUnsigned    bool                   `protobuf:"varint,1,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BigInt) Reset() {
	*x = BigInt{}
	mi := &file_proto_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigInt) ProtoMessage() {}

func (x *BigInt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigInt.ProtoReflect.Descriptor instead.
func (*BigInt) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{1}
}

func (x *BigInt) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

type SmallInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUnsigned    bool                   `protobuf:"varint,1,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmallInt) Reset() {
	*x = SmallInt{}
	mi := &file_proto_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmallInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmallInt) ProtoMessage() {}

func (x *SmallInt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmallInt.ProtoReflect.Descriptor instead.
func (*SmallInt) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{2}
}

func (x *SmallInt) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

type Int struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUnsigned    bool                   `protobuf:"varint,1,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Int) Reset() {
	*x = Int{}
	mi := &file_proto_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Int) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int) ProtoMessage() {}

func (x *Int) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int.ProtoReflect.Descriptor instead.
func (*Int) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{3}
}

func (x *Int) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

type TinyInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUnsigned    bool                   `protobuf:"varint,1,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TinyInt) Reset() {
	*x = TinyInt{}
	mi := &file_proto_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TinyInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TinyInt) ProtoMessage() {}

func (x *TinyInt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TinyInt.ProtoReflect.Descriptor instead.
func (*TinyInt) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{4}
}

func (x *TinyInt) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

type MediumInt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUnsigned    bool                   `protobuf:"varint,1,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediumInt) Reset() {
	*x = MediumInt{}
	mi := &file_proto_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediumInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediumInt) ProtoMessage() {}

func (x *MediumInt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediumInt.ProtoReflect.Descriptor instead.
func (*MediumInt) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{5}
}

func (x *MediumInt) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

type Real struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsUnsigned    bool                   `protobuf:"varint,1,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Real) Reset() {
	*x = Real{}
	mi := &file_proto_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Real) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Real) ProtoMessage() {}

func (x *Real) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Real.ProtoReflect.Descriptor instead.
func (*Real) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{6}
}

func (x *Real) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

type Float struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint32                 `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	IsUnsigned    bool                   `protobuf:"varint,2,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Float) Reset() {
	*x = Float{}
	mi := &file_proto_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Float) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Float) ProtoMessage() {}

func (x *Float) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Float.ProtoReflect.Descriptor instead.
func (*Float) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{7}
}

func (x *Float) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Float) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

type Decimal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Precision     uint32                 `protobuf:"varint,1,opt,name=Precision,proto3" json:"Precision,omitempty"`
	Scale         uint32                 `protobuf:"varint,2,opt,name=Scale,proto3" json:"Scale,omitempty"`
	IsUnsigned    bool                   `protobuf:"varint,3,opt,name=IsUnsigned,proto3" json:"IsUnsigned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	mi := &file_proto_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{8}
}

func (x *Decimal) GetPrecision() uint32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *Decimal) GetScale() uint32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *Decimal) GetIsUnsigned() bool {
	if x != nil {
		return x.IsUnsigned
	}
	return false
}

type CharType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint32                 `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharType) Reset() {
	*x = CharType{}
	mi := &file_proto_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharType) ProtoMessage() {}

func (x *CharType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharType.ProtoReflect.Descriptor instead.
func (*CharType) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{9}
}

func (x *CharType) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type VarcharType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint32                 `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VarcharType) Reset() {
	*x = VarcharType{}
	mi := &file_proto_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VarcharType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarcharType) ProtoMessage() {}

func (x *VarcharType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarcharType.ProtoReflect.Descriptor instead.
func (*VarcharType) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{10}
}

func (x *VarcharType) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WithTimeZone  bool                   `protobuf:"varint,1,opt,name=WithTimeZone,proto3" json:"WithTimeZone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_proto_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{11}
}

func (x *Timestamp) GetWithTimeZone() bool {
	if x != nil {
		return x.WithTimeZone
	}
	return false
}

type BitType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint32                 `protobuf:"varint,1,opt,name=Size,proto3" json:"Size,omitempty"`
	Varying       bool                   `protobuf:"varint,2,opt,name=Varying,proto3" json:"Varying,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BitType) Reset() {
	*x = BitType{}
	mi := &file_proto_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BitType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BitType) ProtoMessage() {}

func (x *BitType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BitType.ProtoReflect.Descriptor instead.
func (*BitType) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{12}
}

func (x *BitType) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BitType) GetVarying() bool {
	if x != nil {
		return x.Varying
	}
	return false
}

type DoubleType struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsDoublePrecision bool                   `protobuf:"varint,1,opt,name=is_double_precision,json=isDoublePrecision,proto3" json:"is_double_precision,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DoubleType) Reset() {
	*x = DoubleType{}
	mi := &file_proto_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleType) ProtoMessage() {}

func (x *DoubleType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleType.ProtoReflect.Descriptor instead.
func (*DoubleType) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{13}
}

func (x *DoubleType) GetIsDoublePrecision() bool {
	if x != nil {
		return x.IsDoublePrecision
	}
	return false
}

type CollateType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *DataType              `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	CollationName string                 `protobuf:"bytes,2,opt,name=CollationName,proto3" json:"CollationName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollateType) Reset() {
	*x = CollateType{}
	mi := &file_proto_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollateType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollateType) ProtoMessage() {}

func (x *CollateType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollateType.ProtoReflect.Descriptor instead.
func (*CollateType) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{14}
}

func (x *CollateType) GetType() *DataType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *CollateType) GetCollationName() string {
	if x != nil {
		return x.CollationName
	}
	return ""
}

type StructData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*MetaColumnDef       `protobuf:"bytes,1,rep,name=Fields,proto3" json:"Fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructData) Reset() {
	*x = StructData{}
	mi := &file_proto_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructData) ProtoMessage() {}

func (x *StructData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructData.ProtoReflect.Descriptor instead.
func (*StructData) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{15}
}

func (x *StructData) GetFields() []*MetaColumnDef {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ArrayData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *DataType              `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayData) Reset() {
	*x = ArrayData{}
	mi := &file_proto_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayData) ProtoMessage() {}

func (x *ArrayData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayData.ProtoReflect.Descriptor instead.
func (*ArrayData) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{16}
}

func (x *ArrayData) GetType() *DataType {
	if x != nil {
		return x.Type
	}
	return nil
}

// MySQL ENUM type
type EnumType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumType) Reset() {
	*x = EnumType{}
	mi := &file_proto_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumType) ProtoMessage() {}

func (x *EnumType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumType.ProtoReflect.Descriptor instead.
func (*EnumType) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{17}
}

func (x *EnumType) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// MySQL SET type
type SetType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetType) Reset() {
	*x = SetType{}
	mi := &file_proto_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetType) ProtoMessage() {}

func (x *SetType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetType.ProtoReflect.Descriptor instead.
func (*SetType) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{18}
}

func (x *SetType) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Primary Key / Unique constraint for a column
type UniqueColumnSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPrimaryKey  bool                   `protobuf:"varint,1,opt,name=IsPrimaryKey,proto3" json:"IsPrimaryKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniqueColumnSpec) Reset() {
	*x = UniqueColumnSpec{}
	mi := &file_proto_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueColumnSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueColumnSpec) ProtoMessage() {}

func (x *UniqueColumnSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueColumnSpec.ProtoReflect.Descriptor instead.
func (*UniqueColumnSpec) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{19}
}

func (x *UniqueColumnSpec) GetIsPrimaryKey() bool {
	if x != nil {
		return x.IsPrimaryKey
	}
	return false
}

// Foreign key column reference expression
type ReferenceKeyExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TableName     string                 `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Columns       []string               `protobuf:"bytes,2,rep,name=Columns,proto3" json:"Columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceKeyExpr) Reset() {
	*x = ReferenceKeyExpr{}
	mi := &file_proto_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceKeyExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceKeyExpr) ProtoMessage() {}

func (x *ReferenceKeyExpr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceKeyExpr.ProtoReflect.Descriptor instead.
func (*ReferenceKeyExpr) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{20}
}

func (x *ReferenceKeyExpr) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *ReferenceKeyExpr) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

// Column-level REFERENCES constraint (FOREIGN KEY)
type ReferencesColumnSpec struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TableName         *ObjectName            `protobuf:"bytes,1,opt,name=TableName,proto3" json:"TableName,omitempty"`
	Columns           []string               `protobuf:"bytes,2,rep,name=Columns,proto3" json:"Columns,omitempty"`
	OnDelete          ReferentialAction      `protobuf:"varint,3,opt,name=OnDelete,proto3,enum=sqlmeta.ReferentialAction" json:"OnDelete,omitempty"`
	OnUpdate          ReferentialAction      `protobuf:"varint,4,opt,name=OnUpdate,proto3,enum=sqlmeta.ReferentialAction" json:"OnUpdate,omitempty"`
	Match             MatchOption            `protobuf:"varint,5,opt,name=Match,proto3,enum=sqlmeta.MatchOption" json:"Match,omitempty"`
	Deferrable        bool                   `protobuf:"varint,6,opt,name=Deferrable,proto3" json:"Deferrable,omitempty"`
	InitiallyDeferred bool                   `protobuf:"varint,7,opt,name=InitiallyDeferred,proto3" json:"InitiallyDeferred,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReferencesColumnSpec) Reset() {
	*x = ReferencesColumnSpec{}
	mi := &file_proto_types_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferencesColumnSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferencesColumnSpec) ProtoMessage() {}

func (x *ReferencesColumnSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferencesColumnSpec.ProtoReflect.Descriptor instead.
func (*ReferencesColumnSpec) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{21}
}

func (x *ReferencesColumnSpec) GetTableName() *ObjectName {
	if x != nil {
		return x.TableName
	}
	return nil
}

func (x *ReferencesColumnSpec) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ReferencesColumnSpec) GetOnDelete() ReferentialAction {
	if x != nil {
		return x.OnDelete
	}
	return ReferentialAction_ReferentialAction_Unknown
}

func (x *ReferencesColumnSpec) GetOnUpdate() ReferentialAction {
	if x != nil {
		return x.OnUpdate
	}
	return ReferentialAction_ReferentialAction_Unknown
}

func (x *ReferencesColumnSpec) GetMatch() MatchOption {
	if x != nil {
		return x.Match
	}
	return MatchOption_MatchOption_Unknown
}

func (x *ReferencesColumnSpec) GetDeferrable() bool {
	if x != nil {
		return x.Deferrable
	}
	return false
}

func (x *ReferencesColumnSpec) GetInitiallyDeferred() bool {
	if x != nil {
		return x.InitiallyDeferred
	}
	return false
}

// Table-level UNIQUE/PRIMARY KEY constraint
type UniqueTableConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsPrimary     bool                   `protobuf:"varint,1,opt,name=IsPrimary,proto3" json:"IsPrimary,omitempty"`
	Columns       []string               `protobuf:"bytes,2,rep,name=Columns,proto3" json:"Columns,omitempty"`
	IndexName     string                 `protobuf:"bytes,3,opt,name=IndexName,proto3" json:"IndexName,omitempty"`
	IsJustIndex   bool                   `protobuf:"varint,4,opt,name=IsJustIndex,proto3" json:"IsJustIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UniqueTableConstraint) Reset() {
	*x = UniqueTableConstraint{}
	mi := &file_proto_types_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UniqueTableConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UniqueTableConstraint) ProtoMessage() {}

func (x *UniqueTableConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UniqueTableConstraint.ProtoReflect.Descriptor instead.
func (*UniqueTableConstraint) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{22}
}

func (x *UniqueTableConstraint) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *UniqueTableConstraint) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *UniqueTableConstraint) GetIndexName() string {
	if x != nil {
		return x.IndexName
	}
	return ""
}

func (x *UniqueTableConstraint) GetIsJustIndex() bool {
	if x != nil {
		return x.IsJustIndex
	}
	return false
}

// Table-level FOREIGN KEY constraint
type ReferentialTableConstraint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Columns           []string               `protobuf:"bytes,1,rep,name=Columns,proto3" json:"Columns,omitempty"`
	KeyExpr           *ReferenceKeyExpr      `protobuf:"bytes,2,opt,name=KeyExpr,proto3" json:"KeyExpr,omitempty"`
	OnDelete          ReferentialAction      `protobuf:"varint,3,opt,name=OnDelete,proto3,enum=sqlmeta.ReferentialAction" json:"OnDelete,omitempty"`
	OnUpdate          ReferentialAction      `protobuf:"varint,4,opt,name=OnUpdate,proto3,enum=sqlmeta.ReferentialAction" json:"OnUpdate,omitempty"`
	Match             MatchOption            `protobuf:"varint,5,opt,name=Match,proto3,enum=sqlmeta.MatchOption" json:"Match,omitempty"`
	Deferrable        bool                   `protobuf:"varint,6,opt,name=Deferrable,proto3" json:"Deferrable,omitempty"`
	InitiallyDeferred bool                   `protobuf:"varint,7,opt,name=InitiallyDeferred,proto3" json:"InitiallyDeferred,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReferentialTableConstraint) Reset() {
	*x = ReferentialTableConstraint{}
	mi := &file_proto_types_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferentialTableConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferentialTableConstraint) ProtoMessage() {}

func (x *ReferentialTableConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferentialTableConstraint.ProtoReflect.Descriptor instead.
func (*ReferentialTableConstraint) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{23}
}

func (x *ReferentialTableConstraint) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ReferentialTableConstraint) GetKeyExpr() *ReferenceKeyExpr {
	if x != nil {
		return x.KeyExpr
	}
	return nil
}

func (x *ReferentialTableConstraint) GetOnDelete() ReferentialAction {
	if x != nil {
		return x.OnDelete
	}
	return ReferentialAction_ReferentialAction_Unknown
}

func (x *ReferentialTableConstraint) GetOnUpdate() ReferentialAction {
	if x != nil {
		return x.OnUpdate
	}
	return ReferentialAction_ReferentialAction_Unknown
}

func (x *ReferentialTableConstraint) GetMatch() MatchOption {
	if x != nil {
		return x.Match
	}
	return MatchOption_MatchOption_Unknown
}

func (x *ReferentialTableConstraint) GetDeferrable() bool {
	if x != nil {
		return x.Deferrable
	}
	return false
}

func (x *ReferentialTableConstraint) GetInitiallyDeferred() bool {
	if x != nil {
		return x.InitiallyDeferred
	}
	return false
}

type DataType struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to TypeClause:
	//
	//	*DataType_IntData
	//	*DataType_SmallIntData
	//	*DataType_BigIntData
	//	*DataType_DecimalData
	//	*DataType_CharData
	//	*DataType_VarcharData
	//	*DataType_CustomData
	//	*DataType_ArrayData
	//	*DataType_StructData
	//	*DataType_UUIDData
	//	*DataType_TimestampData
	//	*DataType_BooleanData
	//	*DataType_DateData
	//	*DataType_TimeData
	//	*DataType_DoubleData
	//	*DataType_FloatData
	//	*DataType_RealData
	//	*DataType_TextData
	//	*DataType_BitData
	//	*DataType_RegclassData
	//	*DataType_ByteaData
	//	*DataType_CollateData
	//	*DataType_EnumData
	//	*DataType_SetData
	//	*DataType_TinyIntData
	//	*DataType_MediumIntData
	//	*DataType_YearData
	TypeClause    isDataType_TypeClause `protobuf_oneof:"TypeClause"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataType) Reset() {
	*x = DataType{}
	mi := &file_proto_types_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataType) ProtoMessage() {}

func (x *DataType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataType.ProtoReflect.Descriptor instead.
func (*DataType) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{24}
}

func (x *DataType) GetTypeClause() isDataType_TypeClause {
	if x != nil {
		return x.TypeClause
	}
	return nil
}

func (x *DataType) GetIntData() *Int {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_IntData); ok {
			return x.IntData
		}
	}
	return nil
}

func (x *DataType) GetSmallIntData() *SmallInt {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_SmallIntData); ok {
			return x.SmallIntData
		}
	}
	return nil
}

func (x *DataType) GetBigIntData() *BigInt {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_BigIntData); ok {
			return x.BigIntData
		}
	}
	return nil
}

func (x *DataType) GetDecimalData() *Decimal {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_DecimalData); ok {
			return x.DecimalData
		}
	}
	return nil
}

func (x *DataType) GetCharData() *CharType {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_CharData); ok {
			return x.CharData
		}
	}
	return nil
}

func (x *DataType) GetVarcharData() *VarcharType {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_VarcharData); ok {
			return x.VarcharData
		}
	}
	return nil
}

func (x *DataType) GetCustomData() *ObjectName {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_CustomData); ok {
			return x.CustomData
		}
	}
	return nil
}

func (x *DataType) GetArrayData() *ArrayData {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_ArrayData); ok {
			return x.ArrayData
		}
	}
	return nil
}

func (x *DataType) GetStructData() *StructData {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_StructData); ok {
			return x.StructData
		}
	}
	return nil
}

func (x *DataType) GetUUIDData() DataTypeSingle {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_UUIDData); ok {
			return x.UUIDData
		}
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

func (x *DataType) GetTimestampData() *Timestamp {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_TimestampData); ok {
			return x.TimestampData
		}
	}
	return nil
}

func (x *DataType) GetBooleanData() DataTypeSingle {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_BooleanData); ok {
			return x.BooleanData
		}
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

func (x *DataType) GetDateData() DataTypeSingle {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_DateData); ok {
			return x.DateData
		}
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

func (x *DataType) GetTimeData() DataTypeSingle {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_TimeData); ok {
			return x.TimeData
		}
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

func (x *DataType) GetDoubleData() *DoubleType {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_DoubleData); ok {
			return x.DoubleData
		}
	}
	return nil
}

func (x *DataType) GetFloatData() *Float {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_FloatData); ok {
			return x.FloatData
		}
	}
	return nil
}

func (x *DataType) GetRealData() *Real {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_RealData); ok {
			return x.RealData
		}
	}
	return nil
}

func (x *DataType) GetTextData() DataTypeSingle {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_TextData); ok {
			return x.TextData
		}
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

func (x *DataType) GetBitData() *BitType {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_BitData); ok {
			return x.BitData
		}
	}
	return nil
}

func (x *DataType) GetRegclassData() DataTypeSingle {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_RegclassData); ok {
			return x.RegclassData
		}
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

func (x *DataType) GetByteaData() DataTypeSingle {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_ByteaData); ok {
			return x.ByteaData
		}
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

func (x *DataType) GetCollateData() *CollateType {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_CollateData); ok {
			return x.CollateData
		}
	}
	return nil
}

func (x *DataType) GetEnumData() *EnumType {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_EnumData); ok {
			return x.EnumData
		}
	}
	return nil
}

func (x *DataType) GetSetData() *SetType {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_SetData); ok {
			return x.SetData
		}
	}
	return nil
}

func (x *DataType) GetTinyIntData() *TinyInt {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_TinyIntData); ok {
			return x.TinyIntData
		}
	}
	return nil
}

func (x *DataType) GetMediumIntData() *MediumInt {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_MediumIntData); ok {
			return x.MediumIntData
		}
	}
	return nil
}

func (x *DataType) GetYearData() DataTypeSingle {
	if x != nil {
		if x, ok := x.TypeClause.(*DataType_YearData); ok {
			return x.YearData
		}
	}
	return DataTypeSingle_DataTypeSingleUnknown
}

type isDataType_TypeClause interface {
	isDataType_TypeClause()
}

type DataType_IntData struct {
	IntData *Int `protobuf:"bytes,1,opt,name=IntData,proto3,oneof"`
}

type DataType_SmallIntData struct {
	SmallIntData *SmallInt `protobuf:"bytes,2,opt,name=SmallIntData,proto3,oneof"`
}

type DataType_BigIntData struct {
	BigIntData *BigInt `protobuf:"bytes,3,opt,name=BigIntData,proto3,oneof"`
}

type DataType_DecimalData struct {
	DecimalData *Decimal `protobuf:"bytes,4,opt,name=DecimalData,proto3,oneof"`
}

type DataType_CharData struct {
	CharData *CharType `protobuf:"bytes,8,opt,name=CharData,proto3,oneof"`
}

type DataType_VarcharData struct {
	VarcharData *VarcharType `protobuf:"bytes,9,opt,name=VarcharData,proto3,oneof"`
}

type DataType_CustomData struct {
	CustomData *ObjectName `protobuf:"bytes,10,opt,name=CustomData,proto3,oneof"`
}

type DataType_ArrayData struct {
	ArrayData *ArrayData `protobuf:"bytes,11,opt,name=ArrayData,proto3,oneof"`
}

type DataType_StructData struct {
	StructData *StructData `protobuf:"bytes,12,opt,name=StructData,proto3,oneof"`
}

type DataType_UUIDData struct {
	UUIDData DataTypeSingle `protobuf:"varint,14,opt,name=UUIDData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

type DataType_TimestampData struct {
	TimestampData *Timestamp `protobuf:"bytes,15,opt,name=TimestampData,proto3,oneof"`
}

type DataType_BooleanData struct {
	BooleanData DataTypeSingle `protobuf:"varint,13,opt,name=BooleanData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

type DataType_DateData struct {
	DateData DataTypeSingle `protobuf:"varint,16,opt,name=DateData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

type DataType_TimeData struct {
	TimeData DataTypeSingle `protobuf:"varint,17,opt,name=TimeData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

type DataType_DoubleData struct {
	DoubleData *DoubleType `protobuf:"bytes,18,opt,name=DoubleData,proto3,oneof"`
}

type DataType_FloatData struct {
	FloatData *Float `protobuf:"bytes,19,opt,name=FloatData,proto3,oneof"`
}

type DataType_RealData struct {
	RealData *Real `protobuf:"bytes,20,opt,name=RealData,proto3,oneof"`
}

type DataType_TextData struct {
	TextData DataTypeSingle `protobuf:"varint,21,opt,name=TextData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

type DataType_BitData struct {
	BitData *BitType `protobuf:"bytes,22,opt,name=BitData,proto3,oneof"`
}

type DataType_RegclassData struct {
	RegclassData DataTypeSingle `protobuf:"varint,23,opt,name=RegclassData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

type DataType_ByteaData struct {
	ByteaData DataTypeSingle `protobuf:"varint,24,opt,name=ByteaData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

type DataType_CollateData struct {
	CollateData *CollateType `protobuf:"bytes,25,opt,name=CollateData,proto3,oneof"`
}

type DataType_EnumData struct {
	EnumData *EnumType `protobuf:"bytes,26,opt,name=EnumData,proto3,oneof"`
}

type DataType_SetData struct {
	SetData *SetType `protobuf:"bytes,27,opt,name=SetData,proto3,oneof"`
}

type DataType_TinyIntData struct {
	TinyIntData *TinyInt `protobuf:"bytes,28,opt,name=TinyIntData,proto3,oneof"`
}

type DataType_MediumIntData struct {
	MediumIntData *MediumInt `protobuf:"bytes,29,opt,name=MediumIntData,proto3,oneof"`
}

type DataType_YearData struct {
	YearData DataTypeSingle `protobuf:"varint,30,opt,name=YearData,proto3,enum=sqlmeta.DataTypeSingle,oneof"`
}

func (*DataType_IntData) isDataType_TypeClause() {}

func (*DataType_SmallIntData) isDataType_TypeClause() {}

func (*DataType_BigIntData) isDataType_TypeClause() {}

func (*DataType_DecimalData) isDataType_TypeClause() {}

func (*DataType_CharData) isDataType_TypeClause() {}

func (*DataType_VarcharData) isDataType_TypeClause() {}

func (*DataType_CustomData) isDataType_TypeClause() {}

func (*DataType_ArrayData) isDataType_TypeClause() {}

func (*DataType_StructData) isDataType_TypeClause() {}

func (*DataType_UUIDData) isDataType_TypeClause() {}

func (*DataType_TimestampData) isDataType_TypeClause() {}

func (*DataType_BooleanData) isDataType_TypeClause() {}

func (*DataType_DateData) isDataType_TypeClause() {}

func (*DataType_TimeData) isDataType_TypeClause() {}

func (*DataType_DoubleData) isDataType_TypeClause() {}

func (*DataType_FloatData) isDataType_TypeClause() {}

func (*DataType_RealData) isDataType_TypeClause() {}

func (*DataType_TextData) isDataType_TypeClause() {}

func (*DataType_BitData) isDataType_TypeClause() {}

func (*DataType_RegclassData) isDataType_TypeClause() {}

func (*DataType_ByteaData) isDataType_TypeClause() {}

func (*DataType_CollateData) isDataType_TypeClause() {}

func (*DataType_EnumData) isDataType_TypeClause() {}

func (*DataType_SetData) isDataType_TypeClause() {}

func (*DataType_TinyIntData) isDataType_TypeClause() {}

func (*DataType_MediumIntData) isDataType_TypeClause() {}

func (*DataType_YearData) isDataType_TypeClause() {}

// Metadata-only column constraint (with string-based CHECK expression)
type MetaColumnConstraintSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MetaColumnConstraintSpecClause:
	//
	//	*MetaColumnConstraintSpec_UniqueItem
	//	*MetaColumnConstraintSpec_CheckExpression
	//	*MetaColumnConstraintSpec_ReferenceItem
	//	*MetaColumnConstraintSpec_NotNullItem
	MetaColumnConstraintSpecClause isMetaColumnConstraintSpec_MetaColumnConstraintSpecClause `protobuf_oneof:"MetaColumnConstraintSpecClause"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *MetaColumnConstraintSpec) Reset() {
	*x = MetaColumnConstraintSpec{}
	mi := &file_proto_types_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaColumnConstraintSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaColumnConstraintSpec) ProtoMessage() {}

func (x *MetaColumnConstraintSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaColumnConstraintSpec.ProtoReflect.Descriptor instead.
func (*MetaColumnConstraintSpec) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{25}
}

func (x *MetaColumnConstraintSpec) GetMetaColumnConstraintSpecClause() isMetaColumnConstraintSpec_MetaColumnConstraintSpecClause {
	if x != nil {
		return x.MetaColumnConstraintSpecClause
	}
	return nil
}

func (x *MetaColumnConstraintSpec) GetUniqueItem() *UniqueColumnSpec {
	if x != nil {
		if x, ok := x.MetaColumnConstraintSpecClause.(*MetaColumnConstraintSpec_UniqueItem); ok {
			return x.UniqueItem
		}
	}
	return nil
}

func (x *MetaColumnConstraintSpec) GetCheckExpression() string {
	if x != nil {
		if x, ok := x.MetaColumnConstraintSpecClause.(*MetaColumnConstraintSpec_CheckExpression); ok {
			return x.CheckExpression
		}
	}
	return ""
}

func (x *MetaColumnConstraintSpec) GetReferenceItem() *ReferencesColumnSpec {
	if x != nil {
		if x, ok := x.MetaColumnConstraintSpecClause.(*MetaColumnConstraintSpec_ReferenceItem); ok {
			return x.ReferenceItem
		}
	}
	return nil
}

func (x *MetaColumnConstraintSpec) GetNotNullItem() NotNullColumnSpec {
	if x != nil {
		if x, ok := x.MetaColumnConstraintSpecClause.(*MetaColumnConstraintSpec_NotNullItem); ok {
			return x.NotNullItem
		}
	}
	return NotNullColumnSpec_NotNullColumnSpecUnknown
}

type isMetaColumnConstraintSpec_MetaColumnConstraintSpecClause interface {
	isMetaColumnConstraintSpec_MetaColumnConstraintSpecClause()
}

type MetaColumnConstraintSpec_UniqueItem struct {
	UniqueItem *UniqueColumnSpec `protobuf:"bytes,1,opt,name=UniqueItem,proto3,oneof"`
}

type MetaColumnConstraintSpec_CheckExpression struct {
	CheckExpression string `protobuf:"bytes,2,opt,name=CheckExpression,proto3,oneof"` // e.g., "amount > 0"
}

type MetaColumnConstraintSpec_ReferenceItem struct {
	ReferenceItem *ReferencesColumnSpec `protobuf:"bytes,3,opt,name=ReferenceItem,proto3,oneof"`
}

type MetaColumnConstraintSpec_NotNullItem struct {
	NotNullItem NotNullColumnSpec `protobuf:"varint,4,opt,name=NotNullItem,proto3,enum=sqlmeta.NotNullColumnSpec,oneof"`
}

func (*MetaColumnConstraintSpec_UniqueItem) isMetaColumnConstraintSpec_MetaColumnConstraintSpecClause() {
}

func (*MetaColumnConstraintSpec_CheckExpression) isMetaColumnConstraintSpec_MetaColumnConstraintSpecClause() {
}

func (*MetaColumnConstraintSpec_ReferenceItem) isMetaColumnConstraintSpec_MetaColumnConstraintSpecClause() {
}

func (*MetaColumnConstraintSpec_NotNullItem) isMetaColumnConstraintSpec_MetaColumnConstraintSpecClause() {
}

// Metadata-only column constraint wrapper
type MetaColumnConstraint struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Name          string                    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Spec          *MetaColumnConstraintSpec `protobuf:"bytes,2,opt,name=Spec,proto3" json:"Spec,omitempty"`
	NotEnforced   bool                      `protobuf:"varint,3,opt,name=NotEnforced,proto3" json:"NotEnforced,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaColumnConstraint) Reset() {
	*x = MetaColumnConstraint{}
	mi := &file_proto_types_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaColumnConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaColumnConstraint) ProtoMessage() {}

func (x *MetaColumnConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaColumnConstraint.ProtoReflect.Descriptor instead.
func (*MetaColumnConstraint) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{26}
}

func (x *MetaColumnConstraint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetaColumnConstraint) GetSpec() *MetaColumnConstraintSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *MetaColumnConstraint) GetNotEnforced() bool {
	if x != nil {
		return x.NotEnforced
	}
	return false
}

// Metadata-only column definition (with string-based DEFAULT value)
type MetaColumnDef struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	DataType      *DataType               `protobuf:"bytes,2,opt,name=DataType,proto3" json:"DataType,omitempty"`
	DefaultValue  string                  `protobuf:"bytes,3,opt,name=DefaultValue,proto3" json:"DefaultValue,omitempty"` // e.g., "CURRENT_TIMESTAMP", "0"
	MyDecos       []AutoIncrement         `protobuf:"varint,4,rep,packed,name=MyDecos,proto3,enum=sqlmeta.AutoIncrement" json:"MyDecos,omitempty"`
	Constraints   []*MetaColumnConstraint `protobuf:"bytes,5,rep,name=Constraints,proto3" json:"Constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaColumnDef) Reset() {
	*x = MetaColumnDef{}
	mi := &file_proto_types_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaColumnDef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaColumnDef) ProtoMessage() {}

func (x *MetaColumnDef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaColumnDef.ProtoReflect.Descriptor instead.
func (*MetaColumnDef) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{27}
}

func (x *MetaColumnDef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetaColumnDef) GetDataType() *DataType {
	if x != nil {
		return x.DataType
	}
	return nil
}

func (x *MetaColumnDef) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *MetaColumnDef) GetMyDecos() []AutoIncrement {
	if x != nil {
		return x.MyDecos
	}
	return nil
}

func (x *MetaColumnDef) GetConstraints() []*MetaColumnConstraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

// Metadata-only table constraint (with string-based CHECK expression)
type MetaTableConstraintSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MetaTableConstraintSpecClause:
	//
	//	*MetaTableConstraintSpec_ReferenceItem
	//	*MetaTableConstraintSpec_CheckExpression
	//	*MetaTableConstraintSpec_UniqueItem
	MetaTableConstraintSpecClause isMetaTableConstraintSpec_MetaTableConstraintSpecClause `protobuf_oneof:"MetaTableConstraintSpecClause"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *MetaTableConstraintSpec) Reset() {
	*x = MetaTableConstraintSpec{}
	mi := &file_proto_types_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaTableConstraintSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaTableConstraintSpec) ProtoMessage() {}

func (x *MetaTableConstraintSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaTableConstraintSpec.ProtoReflect.Descriptor instead.
func (*MetaTableConstraintSpec) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{28}
}

func (x *MetaTableConstraintSpec) GetMetaTableConstraintSpecClause() isMetaTableConstraintSpec_MetaTableConstraintSpecClause {
	if x != nil {
		return x.MetaTableConstraintSpecClause
	}
	return nil
}

func (x *MetaTableConstraintSpec) GetReferenceItem() *ReferentialTableConstraint {
	if x != nil {
		if x, ok := x.MetaTableConstraintSpecClause.(*MetaTableConstraintSpec_ReferenceItem); ok {
			return x.ReferenceItem
		}
	}
	return nil
}

func (x *MetaTableConstraintSpec) GetCheckExpression() string {
	if x != nil {
		if x, ok := x.MetaTableConstraintSpecClause.(*MetaTableConstraintSpec_CheckExpression); ok {
			return x.CheckExpression
		}
	}
	return ""
}

func (x *MetaTableConstraintSpec) GetUniqueItem() *UniqueTableConstraint {
	if x != nil {
		if x, ok := x.MetaTableConstraintSpecClause.(*MetaTableConstraintSpec_UniqueItem); ok {
			return x.UniqueItem
		}
	}
	return nil
}

type isMetaTableConstraintSpec_MetaTableConstraintSpecClause interface {
	isMetaTableConstraintSpec_MetaTableConstraintSpecClause()
}

type MetaTableConstraintSpec_ReferenceItem struct {
	ReferenceItem *ReferentialTableConstraint `protobuf:"bytes,1,opt,name=ReferenceItem,proto3,oneof"`
}

type MetaTableConstraintSpec_CheckExpression struct {
	CheckExpression string `protobuf:"bytes,2,opt,name=CheckExpression,proto3,oneof"` // e.g., "amount > 0"
}

type MetaTableConstraintSpec_UniqueItem struct {
	UniqueItem *UniqueTableConstraint `protobuf:"bytes,3,opt,name=UniqueItem,proto3,oneof"`
}

func (*MetaTableConstraintSpec_ReferenceItem) isMetaTableConstraintSpec_MetaTableConstraintSpecClause() {
}

func (*MetaTableConstraintSpec_CheckExpression) isMetaTableConstraintSpec_MetaTableConstraintSpecClause() {
}

func (*MetaTableConstraintSpec_UniqueItem) isMetaTableConstraintSpec_MetaTableConstraintSpecClause() {
}

// Metadata-only table constraint wrapper
type MetaTableConstraint struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Name          string                   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Spec          *MetaTableConstraintSpec `protobuf:"bytes,2,opt,name=Spec,proto3" json:"Spec,omitempty"`
	NotEnforced   bool                     `protobuf:"varint,3,opt,name=NotEnforced,proto3" json:"NotEnforced,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaTableConstraint) Reset() {
	*x = MetaTableConstraint{}
	mi := &file_proto_types_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaTableConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaTableConstraint) ProtoMessage() {}

func (x *MetaTableConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaTableConstraint.ProtoReflect.Descriptor instead.
func (*MetaTableConstraint) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{29}
}

func (x *MetaTableConstraint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetaTableConstraint) GetSpec() *MetaTableConstraintSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *MetaTableConstraint) GetNotEnforced() bool {
	if x != nil {
		return x.NotEnforced
	}
	return false
}

// Metadata-only table element (column or constraint)
type MetaTableElement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MetaTableElementClause:
	//
	//	*MetaTableElement_ColumnDefElement
	//	*MetaTableElement_TableConstraintElement
	MetaTableElementClause isMetaTableElement_MetaTableElementClause `protobuf_oneof:"MetaTableElementClause"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MetaTableElement) Reset() {
	*x = MetaTableElement{}
	mi := &file_proto_types_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaTableElement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaTableElement) ProtoMessage() {}

func (x *MetaTableElement) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaTableElement.ProtoReflect.Descriptor instead.
func (*MetaTableElement) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{30}
}

func (x *MetaTableElement) GetMetaTableElementClause() isMetaTableElement_MetaTableElementClause {
	if x != nil {
		return x.MetaTableElementClause
	}
	return nil
}

func (x *MetaTableElement) GetColumnDefElement() *MetaColumnDef {
	if x != nil {
		if x, ok := x.MetaTableElementClause.(*MetaTableElement_ColumnDefElement); ok {
			return x.ColumnDefElement
		}
	}
	return nil
}

func (x *MetaTableElement) GetTableConstraintElement() *MetaTableConstraint {
	if x != nil {
		if x, ok := x.MetaTableElementClause.(*MetaTableElement_TableConstraintElement); ok {
			return x.TableConstraintElement
		}
	}
	return nil
}

type isMetaTableElement_MetaTableElementClause interface {
	isMetaTableElement_MetaTableElementClause()
}

type MetaTableElement_ColumnDefElement struct {
	ColumnDefElement *MetaColumnDef `protobuf:"bytes,1,opt,name=ColumnDefElement,proto3,oneof"`
}

type MetaTableElement_TableConstraintElement struct {
	TableConstraintElement *MetaTableConstraint `protobuf:"bytes,2,opt,name=TableConstraintElement,proto3,oneof"`
}

func (*MetaTableElement_ColumnDefElement) isMetaTableElement_MetaTableElementClause() {}

func (*MetaTableElement_TableConstraintElement) isMetaTableElement_MetaTableElementClause() {}

// Metadata-only struct type (uses MetaColumnDef for fields)
type MetaStructData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*MetaColumnDef       `protobuf:"bytes,1,rep,name=Fields,proto3" json:"Fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaStructData) Reset() {
	*x = MetaStructData{}
	mi := &file_proto_types_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaStructData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaStructData) ProtoMessage() {}

func (x *MetaStructData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaStructData.ProtoReflect.Descriptor instead.
func (*MetaStructData) Descriptor() ([]byte, []int) {
	return file_proto_types_proto_rawDescGZIP(), []int{31}
}

func (x *MetaStructData) GetFields() []*MetaColumnDef {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_proto_types_proto protoreflect.FileDescriptor

const file_proto_types_proto_rawDesc = "" +
	"\n" +
	"\x11proto/types.proto\x12\asqlmeta\"$\n" +
	"\n" +
	"ObjectName\x12\x16\n" +
	"\x06Idents\x18\x01 \x03(\tR\x06Idents\"(\n" +
	"\x06BigInt\x12\x1e\n" +
	"\n" +
	"IsUnsigned\x18\x01 \x01(\bR\n" +
	"IsUnsigned\"*\n" +
	"\bSmallInt\x12\x1e\n" +
	"\n" +
	"IsUnsigned\x18\x01 \x01(\bR\n" +
	"IsUnsigned\"%\n" +
	"\x03Int\x12\x1e\n" +
	"\n" +
	"IsUnsigned\x18\x01 \x01(\bR\n" +
	"IsUnsigned\")\n" +
	"\aTinyInt\x12\x1e\n" +
	"\n" +
	"IsUnsigned\x18\x01 \x01(\bR\n" +
	"IsUnsigned\"+\n" +
	"\tMediumInt\x12\x1e\n" +
	"\n" +
	"IsUnsigned\x18\x01 \x01(\bR\n" +
	"IsUnsigned\"&\n" +
	"\x04Real\x12\x1e\n" +
	"\n" +
	"IsUnsigned\x18\x01 \x01(\bR\n" +
	"IsUnsigned\";\n" +
	"\x05Float\x12\x12\n" +
	"\x04Size\x18\x01 \x01(\rR\x04Size\x12\x1e\n" +
	"\n" +
	"IsUnsigned\x18\x02 \x01(\bR\n" +
	"IsUnsigned\"]\n" +
	"\aDecimal\x12\x1c\n" +
	"\tPrecision\x18\x01 \x01(\rR\tPrecision\x12\x14\n" +
	"\x05Scale\x18\x02 \x01(\rR\x05Scale\x12\x1e\n" +
	"\n" +
	"IsUnsigned\x18\x03 \x01(\bR\n" +
	"IsUnsigned\"\x1e\n" +
	"\bCharType\x12\x12\n" +
	"\x04Size\x18\x01 \x01(\rR\x04Size\"!\n" +
	"\vVarcharType\x12\x12\n" +
	"\x04Size\x18\x01 \x01(\rR\x04Size\"/\n" +
	"\tTimestamp\x12\"\n" +
	"\fWithTimeZone\x18\x01 \x01(\bR\fWithTimeZone\"7\n" +
	"\aBitType\x12\x12\n" +
	"\x04Size\x18\x01 \x01(\rR\x04Size\x12\x18\n" +
	"\aVarying\x18\x02 \x01(\bR\aVarying\"<\n" +
	"\n" +
	"DoubleType\x12.\n" +
	"\x13is_double_precision\x18\x01 \x01(\bR\x11isDoublePrecision\"Z\n" +
	"\vCollateType\x12%\n" +
	"\x04Type\x18\x01 \x01(\v2\x11.sqlmeta.DataTypeR\x04Type\x12$\n" +
	"\rCollationName\x18\x02 \x01(\tR\rCollationName\"<\n" +
	"\n" +
	"StructData\x12.\n" +
	"\x06Fields\x18\x01 \x03(\v2\x16.sqlmeta.MetaColumnDefR\x06Fields\"2\n" +
	"\tArrayData\x12%\n" +
	"\x04Type\x18\x01 \x01(\v2\x11.sqlmeta.DataTypeR\x04Type\"\"\n" +
	"\bEnumType\x12\x16\n" +
	"\x06Values\x18\x01 \x03(\tR\x06Values\"!\n" +
	"\aSetType\x12\x16\n" +
	"\x06Values\x18\x01 \x03(\tR\x06Values\"6\n" +
	"\x10UniqueColumnSpec\x12\"\n" +
	"\fIsPrimaryKey\x18\x01 \x01(\bR\fIsPrimaryKey\"J\n" +
	"\x10ReferenceKeyExpr\x12\x1c\n" +
	"\tTableName\x18\x01 \x01(\tR\tTableName\x12\x18\n" +
	"\aColumns\x18\x02 \x03(\tR\aColumns\"\xcd\x02\n" +
	"\x14ReferencesColumnSpec\x121\n" +
	"\tTableName\x18\x01 \x01(\v2\x13.sqlmeta.ObjectNameR\tTableName\x12\x18\n" +
	"\aColumns\x18\x02 \x03(\tR\aColumns\x126\n" +
	"\bOnDelete\x18\x03 \x01(\x0e2\x1a.sqlmeta.ReferentialActionR\bOnDelete\x126\n" +
	"\bOnUpdate\x18\x04 \x01(\x0e2\x1a.sqlmeta.ReferentialActionR\bOnUpdate\x12*\n" +
	"\x05Match\x18\x05 \x01(\x0e2\x14.sqlmeta.MatchOptionR\x05Match\x12\x1e\n" +
	"\n" +
	"Deferrable\x18\x06 \x01(\bR\n" +
	"Deferrable\x12,\n" +
	"\x11InitiallyDeferred\x18\a \x01(\bR\x11InitiallyDeferred\"\x8f\x01\n" +
	"\x15UniqueTableConstraint\x12\x1c\n" +
	"\tIsPrimary\x18\x01 \x01(\bR\tIsPrimary\x12\x18\n" +
	"\aColumns\x18\x02 \x03(\tR\aColumns\x12\x1c\n" +
	"\tIndexName\x18\x03 \x01(\tR\tIndexName\x12 \n" +
	"\vIsJustIndex\x18\x04 \x01(\bR\vIsJustIndex\"\xd5\x02\n" +
	"\x1aReferentialTableConstraint\x12\x18\n" +
	"\aColumns\x18\x01 \x03(\tR\aColumns\x123\n" +
	"\aKeyExpr\x18\x02 \x01(\v2\x19.sqlmeta.ReferenceKeyExprR\aKeyExpr\x126\n" +
	"\bOnDelete\x18\x03 \x01(\x0e2\x1a.sqlmeta.ReferentialActionR\bOnDelete\x126\n" +
	"\bOnUpdate\x18\x04 \x01(\x0e2\x1a.sqlmeta.ReferentialActionR\bOnUpdate\x12*\n" +
	"\x05Match\x18\x05 \x01(\x0e2\x14.sqlmeta.MatchOptionR\x05Match\x12\x1e\n" +
	"\n" +
	"Deferrable\x18\x06 \x01(\bR\n" +
	"Deferrable\x12,\n" +
	"\x11InitiallyDeferred\x18\a \x01(\bR\x11InitiallyDeferred\"\xc2\v\n" +
	"\bDataType\x12(\n" +
	"\aIntData\x18\x01 \x01(\v2\f.sqlmeta.IntH\x00R\aIntData\x127\n" +
	"\fSmallIntData\x18\x02 \x01(\v2\x11.sqlmeta.SmallIntH\x00R\fSmallIntData\x121\n" +
	"\n" +
	"BigIntData\x18\x03 \x01(\v2\x0f.sqlmeta.BigIntH\x00R\n" +
	"BigIntData\x124\n" +
	"\vDecimalData\x18\x04 \x01(\v2\x10.sqlmeta.DecimalH\x00R\vDecimalData\x12/\n" +
	"\bCharData\x18\b \x01(\v2\x11.sqlmeta.CharTypeH\x00R\bCharData\x128\n" +
	"\vVarcharData\x18\t \x01(\v2\x14.sqlmeta.VarcharTypeH\x00R\vVarcharData\x125\n" +
	"\n" +
	"CustomData\x18\n" +
	" \x01(\v2\x13.sqlmeta.ObjectNameH\x00R\n" +
	"CustomData\x122\n" +
	"\tArrayData\x18\v \x01(\v2\x12.sqlmeta.ArrayDataH\x00R\tArrayData\x125\n" +
	"\n" +
	"StructData\x18\f \x01(\v2\x13.sqlmeta.StructDataH\x00R\n" +
	"StructData\x125\n" +
	"\bUUIDData\x18\x0e \x01(\x0e2\x17.sqlmeta.DataTypeSingleH\x00R\bUUIDData\x12:\n" +
	"\rTimestampData\x18\x0f \x01(\v2\x12.sqlmeta.TimestampH\x00R\rTimestampData\x12;\n" +
	"\vBooleanData\x18\r \x01(\x0e2\x17.sqlmeta.DataTypeSingleH\x00R\vBooleanData\x125\n" +
	"\bDateData\x18\x10 \x01(\x0e2\x17.sqlmeta.DataTypeSingleH\x00R\bDateData\x125\n" +
	"\bTimeData\x18\x11 \x01(\x0e2\x17.sqlmeta.DataTypeSingleH\x00R\bTimeData\x125\n" +
	"\n" +
	"DoubleData\x18\x12 \x01(\v2\x13.sqlmeta.DoubleTypeH\x00R\n" +
	"DoubleData\x12.\n" +
	"\tFloatData\x18\x13 \x01(\v2\x0e.sqlmeta.FloatH\x00R\tFloatData\x12+\n" +
	"\bRealData\x18\x14 \x01(\v2\r.sqlmeta.RealH\x00R\bRealData\x125\n" +
	"\bTextData\x18\x15 \x01(\x0e2\x17.sqlmeta.DataTypeSingleH\x00R\bTextData\x12,\n" +
	"\aBitData\x18\x16 \x01(\v2\x10.sqlmeta.BitTypeH\x00R\aBitData\x12=\n" +
	"\fRegclassData\x18\x17 \x01(\x0e2\x17.sqlmeta.DataTypeSingleH\x00R\fRegclassData\x127\n" +
	"\tByteaData\x18\x18 \x01(\x0e2\x17.sqlmeta.DataTypeSingleH\x00R\tByteaData\x128\n" +
	"\vCollateData\x18\x19 \x01(\v2\x14.sqlmeta.CollateTypeH\x00R\vCollateData\x12/\n" +
	"\bEnumData\x18\x1a \x01(\v2\x11.sqlmeta.EnumTypeH\x00R\bEnumData\x12,\n" +
	"\aSetData\x18\x1b \x01(\v2\x10.sqlmeta.SetTypeH\x00R\aSetData\x124\n" +
	"\vTinyIntData\x18\x1c \x01(\v2\x10.sqlmeta.TinyIntH\x00R\vTinyIntData\x12:\n" +
	"\rMediumIntData\x18\x1d \x01(\v2\x12.sqlmeta.MediumIntH\x00R\rMediumIntData\x125\n" +
	"\bYearData\x18\x1e \x01(\x0e2\x17.sqlmeta.DataTypeSingleH\x00R\bYearDataB\f\n" +
	"\n" +
	"TypeClause\"\xac\x02\n" +
	"\x18MetaColumnConstraintSpec\x12;\n" +
	"\n" +
	"UniqueItem\x18\x01 \x01(\v2\x19.sqlmeta.UniqueColumnSpecH\x00R\n" +
	"UniqueItem\x12*\n" +
	"\x0fCheckExpression\x18\x02 \x01(\tH\x00R\x0fCheckExpression\x12E\n" +
	"\rReferenceItem\x18\x03 \x01(\v2\x1d.sqlmeta.ReferencesColumnSpecH\x00R\rReferenceItem\x12>\n" +
	"\vNotNullItem\x18\x04 \x01(\x0e2\x1a.sqlmeta.NotNullColumnSpecH\x00R\vNotNullItemB \n" +
	"\x1eMetaColumnConstraintSpecClause\"\x83\x01\n" +
	"\x14MetaColumnConstraint\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x125\n" +
	"\x04Spec\x18\x02 \x01(\v2!.sqlmeta.MetaColumnConstraintSpecR\x04Spec\x12 \n" +
	"\vNotEnforced\x18\x03 \x01(\bR\vNotEnforced\"\xe9\x01\n" +
	"\rMetaColumnDef\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12-\n" +
	"\bDataType\x18\x02 \x01(\v2\x11.sqlmeta.DataTypeR\bDataType\x12\"\n" +
	"\fDefaultValue\x18\x03 \x01(\tR\fDefaultValue\x120\n" +
	"\aMyDecos\x18\x04 \x03(\x0e2\x16.sqlmeta.AutoIncrementR\aMyDecos\x12?\n" +
	"\vConstraints\x18\x05 \x03(\v2\x1d.sqlmeta.MetaColumnConstraintR\vConstraints\"\xf5\x01\n" +
	"\x17MetaTableConstraintSpec\x12K\n" +
	"\rReferenceItem\x18\x01 \x01(\v2#.sqlmeta.ReferentialTableConstraintH\x00R\rReferenceItem\x12*\n" +
	"\x0fCheckExpression\x18\x02 \x01(\tH\x00R\x0fCheckExpression\x12@\n" +
	"\n" +
	"UniqueItem\x18\x03 \x01(\v2\x1e.sqlmeta.UniqueTableConstraintH\x00R\n" +
	"UniqueItemB\x1f\n" +
	"\x1dMetaTableConstraintSpecClause\"\x81\x01\n" +
	"\x13MetaTableConstraint\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x124\n" +
	"\x04Spec\x18\x02 \x01(\v2 .sqlmeta.MetaTableConstraintSpecR\x04Spec\x12 \n" +
	"\vNotEnforced\x18\x03 \x01(\bR\vNotEnforced\"\xca\x01\n" +
	"\x10MetaTableElement\x12D\n" +
	"\x10ColumnDefElement\x18\x01 \x01(\v2\x16.sqlmeta.MetaColumnDefH\x00R\x10ColumnDefElement\x12V\n" +
	"\x16TableConstraintElement\x18\x02 \x01(\v2\x1c.sqlmeta.MetaTableConstraintH\x00R\x16TableConstraintElementB\x18\n" +
	"\x16MetaTableElementClause\"@\n" +
	"\x0eMetaStructData\x12.\n" +
	"\x06Fields\x18\x01 \x03(\v2\x16.sqlmeta.MetaColumnDefR\x06Fields*\x8f\x01\n" +
	"\x0eDataTypeSingle\x12\x19\n" +
	"\x15DataTypeSingleUnknown\x10\x00\x12\n" +
	"\n" +
	"\x06Double\x10\x01\x12\v\n" +
	"\aBoolean\x10\x02\x12\b\n" +
	"\x04Time\x10\x03\x12\b\n" +
	"\x04Date\x10\x04\x12\t\n" +
	"\x05Bytea\x10\x05\x12\b\n" +
	"\x04Text\x10\x06\x12\f\n" +
	"\bRegclass\x10\a\x12\b\n" +
	"\x04UUID\x10\b\x12\b\n" +
	"\x04Year\x10\t*\xd2\x01\n" +
	"\x11ReferentialAction\x12\x1d\n" +
	"\x19ReferentialAction_Unknown\x10\x00\x12\x1e\n" +
	"\x1aReferentialAction_NoAction\x10\x01\x12\x1e\n" +
	"\x1aReferentialAction_Restrict\x10\x02\x12\x1d\n" +
	"\x19ReferentialAction_Cascade\x10\x03\x12\x1d\n" +
	"\x19ReferentialAction_SetNull\x10\x04\x12 \n" +
	"\x1cReferentialAction_SetDefault\x10\x05*m\n" +
	"\vMatchOption\x12\x17\n" +
	"\x13MatchOption_Unknown\x10\x00\x12\x16\n" +
	"\x12MatchOption_Simple\x10\x01\x12\x17\n" +
	"\x13MatchOption_Partial\x10\x02\x12\x14\n" +
	"\x10MatchOption_Full\x10\x03*7\n" +
	"\tNullValue\x12\x14\n" +
	"\x10NullValueUnknown\x10\x00\x12\x14\n" +
	"\x10NullValueConfirm\x10\x01*C\n" +
	"\rAutoIncrement\x12\x18\n" +
	"\x14AutoIncrementUnknown\x10\x00\x12\x18\n" +
	"\x14AutoIncrementConfirm\x10\x01*O\n" +
	"\x11NotNullColumnSpec\x12\x1c\n" +
	"\x18NotNullColumnSpecUnknown\x10\x00\x12\x1c\n" +
	"\x18NotNullColumnSpecConfirm\x10\x01B\"Z github.com/genelet/sqlmeta/xmetab\x06proto3"

var (
	file_proto_types_proto_rawDescOnce sync.Once
	file_proto_types_proto_rawDescData []byte
)

func file_proto_types_proto_rawDescGZIP() []byte {
	file_proto_types_proto_rawDescOnce.Do(func() {
		file_proto_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_types_proto_rawDesc), len(file_proto_types_proto_rawDesc)))
	})
	return file_proto_types_proto_rawDescData
}

var file_proto_types_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_proto_types_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_proto_types_proto_goTypes = []any{
	(DataTypeSingle)(0),                // 0: sqlmeta.DataTypeSingle
	(ReferentialAction)(0),             // 1: sqlmeta.ReferentialAction
	(MatchOption)(0),                   // 2: sqlmeta.MatchOption
	(NullValue)(0),                     // 3: sqlmeta.NullValue
	(AutoIncrement)(0),                 // 4: sqlmeta.AutoIncrement
	(NotNullColumnSpec)(0),             // 5: sqlmeta.NotNullColumnSpec
	(*ObjectName)(nil),                 // 6: sqlmeta.ObjectName
	(*BigInt)(nil),                     // 7: sqlmeta.BigInt
	(*SmallInt)(nil),                   // 8: sqlmeta.SmallInt
	(*Int)(nil),                        // 9: sqlmeta.Int
	(*TinyInt)(nil),                    // 10: sqlmeta.TinyInt
	(*MediumInt)(nil),                  // 11: sqlmeta.MediumInt
	(*Real)(nil),                       // 12: sqlmeta.Real
	(*Float)(nil),                      // 13: sqlmeta.Float
	(*Decimal)(nil),                    // 14: sqlmeta.Decimal
	(*CharType)(nil),                   // 15: sqlmeta.CharType
	(*VarcharType)(nil),                // 16: sqlmeta.VarcharType
	(*Timestamp)(nil),                  // 17: sqlmeta.Timestamp
	(*BitType)(nil),                    // 18: sqlmeta.BitType
	(*DoubleType)(nil),                 // 19: sqlmeta.DoubleType
	(*CollateType)(nil),                // 20: sqlmeta.CollateType
	(*StructData)(nil),                 // 21: sqlmeta.StructData
	(*ArrayData)(nil),                  // 22: sqlmeta.ArrayData
	(*EnumType)(nil),                   // 23: sqlmeta.EnumType
	(*SetType)(nil),                    // 24: sqlmeta.SetType
	(*UniqueColumnSpec)(nil),           // 25: sqlmeta.UniqueColumnSpec
	(*ReferenceKeyExpr)(nil),           // 26: sqlmeta.ReferenceKeyExpr
	(*ReferencesColumnSpec)(nil),       // 27: sqlmeta.ReferencesColumnSpec
	(*UniqueTableConstraint)(nil),      // 28: sqlmeta.UniqueTableConstraint
	(*ReferentialTableConstraint)(nil), // 29: sqlmeta.ReferentialTableConstraint
	(*DataType)(nil),                   // 30: sqlmeta.DataType
	(*MetaColumnConstraintSpec)(nil),   // 31: sqlmeta.MetaColumnConstraintSpec
	(*MetaColumnConstraint)(nil),       // 32: sqlmeta.MetaColumnConstraint
	(*MetaColumnDef)(nil),              // 33: sqlmeta.MetaColumnDef
	(*MetaTableConstraintSpec)(nil),    // 34: sqlmeta.MetaTableConstraintSpec
	(*MetaTableConstraint)(nil),        // 35: sqlmeta.MetaTableConstraint
	(*MetaTableElement)(nil),           // 36: sqlmeta.MetaTableElement
	(*MetaStructData)(nil),             // 37: sqlmeta.MetaStructData
}
var file_proto_types_proto_depIdxs = []int32{
	30, // 0: sqlmeta.CollateType.Type:type_name -> sqlmeta.DataType
	33, // 1: sqlmeta.StructData.Fields:type_name -> sqlmeta.MetaColumnDef
	30, // 2: sqlmeta.ArrayData.Type:type_name -> sqlmeta.DataType
	6,  // 3: sqlmeta.ReferencesColumnSpec.TableName:type_name -> sqlmeta.ObjectName
	1,  // 4: sqlmeta.ReferencesColumnSpec.OnDelete:type_name -> sqlmeta.ReferentialAction
	1,  // 5: sqlmeta.ReferencesColumnSpec.OnUpdate:type_name -> sqlmeta.ReferentialAction
	2,  // 6: sqlmeta.ReferencesColumnSpec.Match:type_name -> sqlmeta.MatchOption
	26, // 7: sqlmeta.ReferentialTableConstraint.KeyExpr:type_name -> sqlmeta.ReferenceKeyExpr
	1,  // 8: sqlmeta.ReferentialTableConstraint.OnDelete:type_name -> sqlmeta.ReferentialAction
	1,  // 9: sqlmeta.ReferentialTableConstraint.OnUpdate:type_name -> sqlmeta.ReferentialAction
	2,  // 10: sqlmeta.ReferentialTableConstraint.Match:type_name -> sqlmeta.MatchOption
	9,  // 11: sqlmeta.DataType.IntData:type_name -> sqlmeta.Int
	8,  // 12: sqlmeta.DataType.SmallIntData:type_name -> sqlmeta.SmallInt
	7,  // 13: sqlmeta.DataType.BigIntData:type_name -> sqlmeta.BigInt
	14, // 14: sqlmeta.DataType.DecimalData:type_name -> sqlmeta.Decimal
	15, // 15: sqlmeta.DataType.CharData:type_name -> sqlmeta.CharType
	16, // 16: sqlmeta.DataType.VarcharData:type_name -> sqlmeta.VarcharType
	6,  // 17: sqlmeta.DataType.CustomData:type_name -> sqlmeta.ObjectName
	22, // 18: sqlmeta.DataType.ArrayData:type_name -> sqlmeta.ArrayData
	21, // 19: sqlmeta.DataType.StructData:type_name -> sqlmeta.StructData
	0,  // 20: sqlmeta.DataType.UUIDData:type_name -> sqlmeta.DataTypeSingle
	17, // 21: sqlmeta.DataType.TimestampData:type_name -> sqlmeta.Timestamp
	0,  // 22: sqlmeta.DataType.BooleanData:type_name -> sqlmeta.DataTypeSingle
	0,  // 23: sqlmeta.DataType.DateData:type_name -> sqlmeta.DataTypeSingle
	0,  // 24: sqlmeta.DataType.TimeData:type_name -> sqlmeta.DataTypeSingle
	19, // 25: sqlmeta.DataType.DoubleData:type_name -> sqlmeta.DoubleType
	13, // 26: sqlmeta.DataType.FloatData:type_name -> sqlmeta.Float
	12, // 27: sqlmeta.DataType.RealData:type_name -> sqlmeta.Real
	0,  // 28: sqlmeta.DataType.TextData:type_name -> sqlmeta.DataTypeSingle
	18, // 29: sqlmeta.DataType.BitData:type_name -> sqlmeta.BitType
	0,  // 30: sqlmeta.DataType.RegclassData:type_name -> sqlmeta.DataTypeSingle
	0,  // 31: sqlmeta.DataType.ByteaData:type_name -> sqlmeta.DataTypeSingle
	20, // 32: sqlmeta.DataType.CollateData:type_name -> sqlmeta.CollateType
	23, // 33: sqlmeta.DataType.EnumData:type_name -> sqlmeta.EnumType
	24, // 34: sqlmeta.DataType.SetData:type_name -> sqlmeta.SetType
	10, // 35: sqlmeta.DataType.TinyIntData:type_name -> sqlmeta.TinyInt
	11, // 36: sqlmeta.DataType.MediumIntData:type_name -> sqlmeta.MediumInt
	0,  // 37: sqlmeta.DataType.YearData:type_name -> sqlmeta.DataTypeSingle
	25, // 38: sqlmeta.MetaColumnConstraintSpec.UniqueItem:type_name -> sqlmeta.UniqueColumnSpec
	27, // 39: sqlmeta.MetaColumnConstraintSpec.ReferenceItem:type_name -> sqlmeta.ReferencesColumnSpec
	5,  // 40: sqlmeta.MetaColumnConstraintSpec.NotNullItem:type_name -> sqlmeta.NotNullColumnSpec
	31, // 41: sqlmeta.MetaColumnConstraint.Spec:type_name -> sqlmeta.MetaColumnConstraintSpec
	30, // 42: sqlmeta.MetaColumnDef.DataType:type_name -> sqlmeta.DataType
	4,  // 43: sqlmeta.MetaColumnDef.MyDecos:type_name -> sqlmeta.AutoIncrement
	32, // 44: sqlmeta.MetaColumnDef.Constraints:type_name -> sqlmeta.MetaColumnConstraint
	29, // 45: sqlmeta.MetaTableConstraintSpec.ReferenceItem:type_name -> sqlmeta.ReferentialTableConstraint
	28, // 46: sqlmeta.MetaTableConstraintSpec.UniqueItem:type_name -> sqlmeta.UniqueTableConstraint
	34, // 47: sqlmeta.MetaTableConstraint.Spec:type_name -> sqlmeta.MetaTableConstraintSpec
	33, // 48: sqlmeta.MetaTableElement.ColumnDefElement:type_name -> sqlmeta.MetaColumnDef
	35, // 49: sqlmeta.MetaTableElement.TableConstraintElement:type_name -> sqlmeta.MetaTableConstraint
	33, // 50: sqlmeta.MetaStructData.Fields:type_name -> sqlmeta.MetaColumnDef
	51, // [51:51] is the sub-list for method output_type
	51, // [51:51] is the sub-list for method input_type
	51, // [51:51] is the sub-list for extension type_name
	51, // [51:51] is the sub-list for extension extendee
	0,  // [0:51] is the sub-list for field type_name
}

func init() { file_proto_types_proto_init() }
func file_proto_types_proto_init() {
	if File_proto_types_proto != nil {
		return
	}
	file_proto_types_proto_msgTypes[24].OneofWrappers = []any{
		(*DataType_IntData)(nil),
		(*DataType_SmallIntData)(nil),
		(*DataType_BigIntData)(nil),
		(*DataType_DecimalData)(nil),
		(*DataType_CharData)(nil),
		(*DataType_VarcharData)(nil),
		(*DataType_CustomData)(nil),
		(*DataType_ArrayData)(nil),
		(*DataType_StructData)(nil),
		(*DataType_UUIDData)(nil),
		(*DataType_TimestampData)(nil),
		(*DataType_BooleanData)(nil),
		(*DataType_DateData)(nil),
		(*DataType_TimeData)(nil),
		(*DataType_DoubleData)(nil),
		(*DataType_FloatData)(nil),
		(*DataType_RealData)(nil),
		(*DataType_TextData)(nil),
		(*DataType_BitData)(nil),
		(*DataType_RegclassData)(nil),
		(*DataType_ByteaData)(nil),
		(*DataType_CollateData)(nil),
		(*DataType_EnumData)(nil),
		(*DataType_SetData)(nil),
		(*DataType_TinyIntData)(nil),
		(*DataType_MediumIntData)(nil),
		(*DataType_YearData)(nil),
	}
	file_proto_types_proto_msgTypes[25].OneofWrappers = []any{
		(*MetaColumnConstraintSpec_UniqueItem)(nil),
		(*MetaColumnConstraintSpec_CheckExpression)(nil),
		(*MetaColumnConstraintSpec_ReferenceItem)(nil),
		(*MetaColumnConstraintSpec_NotNullItem)(nil),
	}
	file_proto_types_proto_msgTypes[28].OneofWrappers = []any{
		(*MetaTableConstraintSpec_ReferenceItem)(nil),
		(*MetaTableConstraintSpec_CheckExpression)(nil),
		(*MetaTableConstraintSpec_UniqueItem)(nil),
	}
	file_proto_types_proto_msgTypes[30].OneofWrappers = []any{
		(*MetaTableElement_ColumnDefElement)(nil),
		(*MetaTableElement_TableConstraintElement)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_types_proto_rawDesc), len(file_proto_types_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_types_proto_goTypes,
		DependencyIndexes: file_proto_types_proto_depIdxs,
		EnumInfos:         file_proto_types_proto_enumTypes,
		MessageInfos:      file_proto_types_proto_msgTypes,
	}.Build()
	File_proto_types_proto = out.File
	file_proto_types_proto_goTypes = nil
	file_proto_types_proto_depIdxs = nil
}
